#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
# vim: set ts=4 sw=4 et:
#
# mkiso
# Created: 2023/09/18 - 09:05
# Altered: 2024/12/17 - 12:43
# Updated: sáb 25 abr 2026 18:59:09 -04
#
# Copyright (c) 2009-2015 Juan Romero Pardines.
# Copyright (c) 2019-2026 Vilmar Catafesta <vcatafesta@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#-
#xbps-install -U -r /tmp/fakeroot --repository=https://repo-fastly.voidlinux.org/current bash -S

export LANGUAGE="${LANGUAGE:-pt_BR}"
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=mkiso
export TERM=${TERM:-xterm}
export TERM=${TERM:-xterm-256color}

# Armazenar os aliases atuais em uma variável
OLD_ALIASES=$(alias)
# Desativar todos os aliases
unalias -a

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
#set -x
#set -e
shopt -s extglob

#system
readonly APP="${0##*/}"
readonly _VERSION_='0.04.25-20260425'
readonly distro=$(uname -n)
readonly DEPENDENCIES=(rsync sed grep cat umount losetup tput chroot mkfs.vfat tee)

# Restaurar os aliases quando o script terminar
trap "eval \"$OLD_ALIASES\"" EXIT
#trap 'error_out $? $LINENO' INT TERM 0
trap 'umount_pseudofs' EXIT INT TERM HUP

umask 022
declare -g MAKE_X=false
declare -g MAKE_XFCE_BASE=false
declare -g MAKE_XFCE=false
declare -g MAKE_AWESOME=false
declare -g MAKE_ENLIGHTENMENT=false
declare -g MAKE_FLUXBOX=false
declare -g MAKE_PLASMA=false
declare -g MAKE_GNOME=false
declare -g MAKE_CINNAMON=false
declare -g MAKE_MATE=false
declare -g MAKE_FULL_X=false
declare -g LBIND=false
declare -g QUIET=false
declare -gi STEP_COUNT=59
declare -gi njobs=59
declare -g VOL_ID='VOIDBR_LIVE'
declare -g title
declare -g INITRAM_COMPRESSION=xz
declare -g SQUASHFS_COMPRESSION=xz
declare -g SQUASHFS_COMPRESSION=zstd
#declare -g KEEP_BUILDDIR=true
declare -g name='base'

sh_choose_packages_base() {
	print_step "Selecionando pacotes essenciais"
	declare -a INCLUDE_DIRS=()
	declare -g PROGNAME=$(basename "$0")
	declare -g REQUIRED_PKGS="base-files dash bash bash-completion coreutils sed tar gawk syslinux grub-i386-efi grub-x86_64-efi memtest86+ squashfs-tools xorriso"
	declare -g INITRAMFS_PKGS="binutils device-mapper dhclient dracut dracut-network"
	ADDITIONAL_PKGS+=" voidbr-vinstall"
	ADDITIONAL_PKGS+=" voidbr-grub-theme"
	ADDITIONAL_PKGS+=" void-install"
	ADDITIONAL_PKGS+=" voidbr-utils"
	ADDITIONAL_PKGS+=" chili-utils"
	ADDITIONAL_PKGS+=" grc ncurses dialog gettext curl wget git pv nano parted e2fsprogs bc"
	ADDITIONAL_PKGS+=" xz zstd pigz cryptsetup lvm2 wireless_tools wpa_supplicant socklog-void chrony"
	ADDITIONAL_PKGS+=" openssh"
	ADDITIONAL_PKGS+=" dhcpcd"
	ADDITIONAL_PKGS+=" NetworkManager"
	ADDITIONAL_PKGS+=" plymouth"
	ADDITIONAL_PKGS+=" htop"
	ADDITIONAL_PKGS+=" tree"
	ADDITIONAL_PKGS+=" rsync"
	ADDITIONAL_PKGS+=" tmate"
	ADDITIONAL_PKGS+=" duf"
	ADDITIONAL_PKGS+=" umc"
	ADDITIONAL_PKGS+=" fzf"
	ADDITIONAL_PKGS+=" exa"

	ACONFIG_PKGS+=(voidbr-base-config)
	ACONFIG_PKGS+=(voidbr-plymouth-theme)
	AEXTRA_PKGS+=" vim "
	AEXTRA_PKGS+=" fastfetch"

	#	ADDITIONAL_PKGS+=" openresolv" ADDITIONAL_PKGS+=" github-cli"
	#	ADDITIONAL_PKGS+=" libgcc"
	#	ADDITIONAL_PKGS+=" github-cli"
	#	ADDITIONAL_PKGS+=" iputils"
	#	ADDITIONAL_PKGS+=" net-tools"
	#	ADDITIONAL_PKGS+=" plymouth-data"
	#	ADDITIONAL_PKGS+=" acpi acpid"
	#	ADDITIONAL_PKGS+=" xtools"
	#	ADDITIONAL_PKGS+=" grub-btrfs-runit"
	#	ADDITIONAL_PKGS+=" cifs-utils"
	#	ADDITIONAL_PKGS+=" ntfs-3g"
	#	ADDITIONAL_PKGS+=" porg"
	#   ADDITIONAL_PKGS+=" wifi-firmware"
	#   ADDITIONAL_PKGS+=" rtl8812au-dkms rtl8821cu-dkms rtl8822bu-dkms"
	#	ADDITIONAL_PKGS+=" pacman fakeroot bsdtar"
}

sh_choose_packages_common_X() {
	print_step "Selecionando pacotes X Common"
	COMMON_PKGS="xorg xorg-apps xorg-fonts xterm dbus dbus-x11 elogind dbus-elogind polkit-elogind xdg-user-dirs"
	COMMON_PKGS+=" cool-retro-term"
	COMMON_PKGS+=" firefox firefox-i18n-pt-BR"
	COMMON_PKGS+=" noto-fonts-emoji"
	COMMON_PKGS+=" ttf-ubuntu-font-family"
	COMMON_PKGS+=" font-iosevka"
	COMMON_PKGS+=" nerd-fonts-symbols-ttf"
	COMMON_PKGS+=" nerd-fonts-symbols-ttf"
	COMMON_PKGS+=" font-awesome"
	COMMON_PKGS+=" Adapta"
	COMMON_PKGS+=" adwaita-icon-theme"
	COMMON_PKGS+=" adwaita-plus"
	COMMON_PKGS+=" network-manager-applet"
	COMMON_PKGS+=" xfce4-terminal"
	COMMON_PKGS+=" pulseaudio pavucontrol pasystray gst-plugins-bad1 gst-plugins-good1 gst-plugins-ugly1 gst-plugins-base1"
	COMMON_PKGS+=" xfce4-pulseaudio-plugin"
	COMMON_PKGS+=" gparted"
	COMMON_PKGS+=" octoxbps"
	COMMON_PKGS+=" mate-calc"
	COMMON_PKGS+=" 7zip p7zip file-roller"
	COMMON_PKGS+=" avahi avahi-discover"
	COMMON_PKGS+=" gvfs gvfs-smb gvfs-cdda inetutils iputils"
	if $MAKE_GNOME; then
		COMMON_PKGS+=" gdm" #seg 04 mai 2026 11:12:38 -04
	else
		COMMON_PKGS+=" lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings arc-theme papirus-icon-theme dejavu-fonts-ttf"
		AEXTRA_COMMON_PKGS+=" voidbr-lightdm-themes"
	fi
	COMMON_PKGS+=" sddm"
	COMMON_PKGS+=" libavif libheif gdk-pixbuf libheif-pixbuf-loader"
	COMMON_PKGS+=" xorg-server-xwayland" #seg 04 mai 2026 11:12:38 -04

	AEXTRA_COMMON_PKGS+=" voidbr-wallpapers"
	AEXTRA_COMMON_PKGS+=" voidbr-tokyo-theme"
	AEXTRA_COMMON_PKGS+=" voidbr-professional-theme"
	AEXTRA_COMMON_PKGS+=" voidbr-beauty-icons"
	AEXTRA_COMMON_PKGS+=" sddm voidbr-sddm-themes"
	AEXTRA_COMMON_PKGS+=" voidbr-sddm-themes"
	AEXTRA_COMMON_PKGS+=" voidbr-xfce-theme-dracula"

	#	COMMON_PKGS+=" brave-bin"
	#   COMMON_PKGS+=" fonts-roboto-ttf"
	#   COMMON_PKGS+=" liberation-fonts-ttf"
	#   COMMON_PKGS+=" dejavu-fonts-ttf"
	#   COMMON_PKGS+=" fonts-droid-ttf"
	#   COMMON_PKGS+=" fonts-croscore-ttf"
	#   COMMON_PKGS+=" terminus-font"
	#   COMMON_PKGS+=" font-emoji-one-color"
	#   COMMON_PKGS+=" google-fonts-ttf"
	#	COMMON_PKGS+=" cool-retro-term"
	#	COMMON_PKGS+=" rxvt-unicode"
	#	COMMON_PKGS+=" blueberry"
	#	COMMON_PKGS+=" bluez"
	#	COMMON_PKGS+=" bluez-deprecated"
	#	COMMON_PKGS+=" bluez-alsa"
	#	COMMON_PKGS+=" bluedevil"
	#	COMMON_PKGS+=" blueman"
	#	COMMON_PKGS+=" bluez-cups"
	#	COMMON_PKGS+=" gnome-bluetooth1"
	#	COMMON_PKGS+=" pipewire wireplumber pulseaudio-utils alsa-pipewire libspa-bluetooth libjack-pipewire"
	#	COMMON_PKGS+=" orca"
	#	COMMON_PKGS+=" inxi"
	#	COMMON_PKGS+=" setxkbmap"
	#	COMMON_PKGS+=" numlockx"
	#	COMMON_PKGS+=" nitrogen"
	#	COMMON_PKGS+=" mate-notification-daemon"
	#	COMMON_PKGS+=" lxdm lxdm-theme-vdojo"
	#   COMMON_PKGS+=" lxappearance lxinput lxrandr lxtask"
	#   COMMON_PKGS+=" slim"
	#   COMMON_PKGS+=" lightdm"
	#	COMMON_PKGS+=" xarchiver zip unzip bzip2"
	#	COMMON_PKGS+=" libreoffice libreoffice-i18n-pt-BR"
	#	COMMON_PKGS+=" irqbalance"
	#	COMMON_PKGS+=" cups system-config-printer system-config-printer-udev splix"
	#	COMMON_PKGS+=" vlc celluloid"
	#	COMMON_PKGS+=" bat cmatrix xkill menulibre mugshot ocs-url"
	#	COMMON_PKGS+=" nvme-cli"
	#	COMMON_PKGS+=" remmina remmina-kwallet"
}

sh_choose_packages_awesome() {
	print_step "Selecionando pacotes Awesome"
	ADDITIONAL_PKGS+=" awesome"
	ADDITIONAL_PKGS+=" polybar"
	ADDITIONAL_PKGS+=" pcmanfm"
}

sh_choose_packages_plasma() {
	print_step "Selecionando pacotes KDE Plasma"
	ADDITIONAL_PKGS+=" kde5"
	ADDITIONAL_PKGS+=" konsole"
	ADDITIONAL_PKGS+=" kate"
	ADDITIONAL_PKGS+=" dolphin"

	ACONFIG_PKGS+=(voidbr-plasma-config)
}

sh_choose_packages_gnome() {
	print_step "Selecionando pacotes GNOME"
	#gnome
	ADISTRO_PKGS+=" gnome"
	ADISTRO_PKGS+=" gnome-keyring"
	ADISTRO_PKGS+=" voidbr-change-gnome-wallpaper"
	ACONFIG_PKGS+=(voidbr-gnome-config)
}

sh_choose_packages_fluxbox() {
	print_step "Selecionando pacotes FLUXBOX"
	ADISTRO_PKGS+=" fluxbox"
	ADISTRO_PKGS+=" polybar"
	ADISTRO_PKGS+=" pcmanfm"
	ADISTRO_PKGS+=" xdgmenumaker"
}

sh_choose_packages_enlightenment() {
	print_step "Selecionando pacotes Enlightenment"
	ADISTRO_PKGS+=" enlightenment"
	ADISTRO_PKGS+=" efl"
	ADISTRO_PKGS+=" rage"
	ADISTRO_PKGS+=" terminology"
	ADISTRO_PKGS+=" exquisite"
	ADISTRO_PKGS+=" connman"

	ACONFIG_PKGS+=(voidbr-enlightenment-config)

}

sh_choose_packages_xfce_base() {
	print_step "Selecionando pacotes XFCE Base"
	ADISTRO_PKGS+=" xfce4"
	ADISTRO_PKGS+=" Thunar"
	ADISTRO_PKGS+=" xfce4-plugins"
	ADISTRO_PKGS+=" xfce4-screenshooter"
	ADISTRO_PKGS+=" xfce4-dict"
	ADISTRO_PKGS+=" xfce4-datetime-plugin"
}

sh_choose_packages_xfce() {
	print_step "Selecionando pacotes XFCE"
	ADISTRO_PKGS+=" thunar-archive-plugin"
	ADISTRO_PKGS+=" thunar-volman"
	ADISTRO_PKGS+=" plank"
	#	ADISTRO_PKGS+=" brother-brlaser"
	#	ADISTRO_PKGS+=" cups-pdf"

	AEXTRA_PKGS+=" voidbr-xfwm-axiom-theme"
	ACONFIG_PKGS+=(voidbr-xfce-config)
	ACONFIG_PKGS+=(voidbr-xfce-theme-dracula)

}

sh_choose_packages_cinnamon() {
	print_step "Selecionando pacotes CINNAMON"
	ADISTRO_PKGS+=" cinnamon-all"
	ADISTRO_PKGS+=" plank"
	ADISTRO_PKGS+=" playerctl"

	ACONFIG_PKGS+=(voidbr-cinnamon-config)

}

sh_choose_packages_mate() {
	print_step "Selecionando pacotes MATE"
	#mate-extra está conflitando atril com libxreader do Cinnamon
	#atril também está orfão
	ADISTRO_PKGS+=" mate engrampa eom mate-applets mate-calc mate-indicator-applet mate-media mate-power-manager mate-sensors-applet mate-screensaver mate-system-monitor mate-terminal mate-utils mozo pluma caja-extensions yelp"
	ADISTRO_PKGS+=" xreader" # substitui atril
	ADISTRO_PKGS+=" plank"
	ADISTRO_PKGS+=" brisk-menu"
	ADISTRO_PKGS+=" mate-backgrounds"
	ADISTRO_PKGS+=" mate-common"

	AEXTRA_PKGS+=" mate-icon-theme-faenza mate-media"
	AEXTRA_PKGS+=" mate-netbook mate-power-manager mate-screensaver mate-sensors-applet mate-system-monitor mate-terminal"
	AEXTRA_PKGS+=" mate-utils caja-image-converter caja-open-terminal caja-sendto caja-share caja-wallpaper caja-xattr-tags"
	AEXTRA_PKGS+=" engrampa eom mozo pluma plank brisk-menu"

	ACONFIG_PKGS+=(voidbr-mate-config)

}

sh_setEnvironment() {
	declare -g BOOTLOG="/tmp/void-mklive-$(sh_diahora).log"
	declare -g LOGGER='/dev/tty8'
}

sh_setLanguage() {
	cmsg_CommandNotFound=$(gettext "não encontrei o comando")
	cmsg_ImpossivelContinuar=$(gettext "IMPOSSÍVEL CONTINUAR")
	cmsg_ImpossivelContinuar1=$(gettext "Esse script precisa dos comandos listados acima")
	cmsg_ImpossivelContinuar2=$(gettext "Instale-os e/ou verifique se estão no seu")
	cmsg_InstCommand=$(gettext "Instalar o(s) comando(s)")
	cmsg_RunNew=$(gettext "INFO: Rode novamente o aplicativo")
	cmsg_RunNewErro=$(gettext "ERRO na instalação dos comandos. Tente manualmente")
}

readconf() {
	if [[ $LC_DEFAULT -eq 0 ]]; then
		read -r -p "$@ [S/n]"
	else
		read -r -p "$@ [Y/n]"
	fi
	[[ ${REPLY^} == "" ]] && return 0
	[[ ${REPLY^} == N ]] && return 1 || return 0
}

sh_checkDependencies() {
	local d
	local errorFound=false
	declare -a missing

	for d in "${DEPENDENCIES[@]}"; do
		if [[ -z $(command -v "$d") ]]; then
			missing+=("$d")
			errorFound=true
			printf '%s\n' "${red}${cmsg_ERRO}${reset}: ${cmsg_CommandNotFound} ${cyan}'$d'${reset}"
		fi
	done
	if $errorFound; then
		echo "${yellow}--------------${cmsg_ImpossivelContinuar}-------------${reset}"
		echo "${cmsg_ImpossivelContinuar1}" >&2
		echo "${cmsg_ImpossivelContinuar2} \$PATH" >&2
		echo "${yellow}-----------------------------------------------${reset}"

		if [[ "$distro" = @(void|void-live|voidlinux) ]]; then
			echo
			if readconf "${yellow}${cmsg_InstCommand} '${cyan}${missing[*]}${reset}' ?"; then
				if xbps-install -Sy "${missing[@]}" -R $XBPS_REPOSITORY; then
					errorFound=false
					sh_checkDependencies
				else
					die "${cmsg_RunNewErro}"
				fi
			fi
		else
			die "${cmsg_ERRO}: ${cmsg_InstalacaoAbortada}..."
		fi
	fi
}

sh_setVarColors() {
	reset=$(tput sgr0)
	rst=$(tput sgr0)
	# Definir os estilos de texto como variáveis
	bold=$(tput bold)
	underline=$(tput smul)   # Início do sublinhado
	nounderline=$(tput rmul) # Fim do sublinhado
	reverse=$(tput rev)      # Inverte as cores de fundo e texto
	# Definir as cores ANSI como variáveis
	black=$(tput bold)$(tput setaf 0)
	red=$(tput bold)$(tput setaf 196)
	green=$(tput bold)$(tput setaf 2)
	yellow=$(tput bold)$(tput setaf 3)
	blue=$(tput setaf 4)
	pink=$(tput setaf 5)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	gray=$(tput setaf 8)
	orange=$(tput setaf 202)
	purple=$(tput setaf 125)
	violet=$(tput setaf 61)
	light_red=$(tput setaf 9)
	light_green=$(tput setaf 10)
	light_yellow=$(tput setaf 11)
	light_blue=$(tput setaf 12)
	light_magenta=$(tput setaf 13)
	light_cyan=$(tput setaf 14)
	bright_white=$(tput setaf 15)
}

die() {
	local script_name0="${0##*/}[${FUNCNAME[0]}]:${BASH_LINENO[0]}"
	local script_name1="${0##*/}[${FUNCNAME[1]}]:${BASH_LINENO[1]}"
	local script_name2="${0##*/}[${FUNCNAME[2]}]:${BASH_LINENO[2]}"
	info_msg "ERROR: ${script_name0} $@"
	error_out 1 $LINENO
}

info_msg() {
	printf "${yellow}$@${reset}\n"
}

msgDot() {
	local s="$*"
	MSG_PAD=50 # largura antes do :

	if [[ "$s" == *:* ]]; then
		local left="${s%%:*}"
		local right="${s#*:}"

		printf "=>%s[%s/%s]%s %-*s : %s%s%s\n" \
			"$cyan" "$CURRENT_STEP" "$STEP_COUNT" "$reset" \
			"$MSG_PAD" "$left" \
			"$yellow" "$right" "$reset"
	else
		printf "=>%s[%s/%s]%s %s\n" \
			"$cyan" "$CURRENT_STEP" "$STEP_COUNT" "$reset" \
			"$s"
	fi
}

print_step() {
	local script_name0="${0##*/}[${FUNCNAME[0]}]:${BASH_LINENO[0]}"
	local script_name1="${0##*/}[${FUNCNAME[1]}]:${BASH_LINENO[1]}"
	local script_name2="${0##*/}[${FUNCNAME[2]}]:${BASH_LINENO[2]}"
	CURRENT_STEP=$((CURRENT_STEP + 1))
	#info_msg "$script_name1=>$cyan[${CURRENT_STEP}/${STEP_COUNT}]$reset $@"
	#	info_msg "=>$cyan[${CURRENT_STEP}/${STEP_COUNT}]$reset $@"
	#	msg "=>$cyan[${CURRENT_STEP}/${STEP_COUNT}]$reset $@"
	msgDot "$*"
}

mount_pseudofs() {
	[[ $LBIND -eq 0 ]] || return 0
	for f in proc sys dev; do
		local target="$ROOTFS/$f"
		print_step "Montando pseudo FS: $target"
		mkdir -p "$target"
		mount --rbind "/$f" "$target"
		# ESSENCIAL: evita propagação de desmontagem para o host
		mount --make-rslave "$target"
	done
	LBIND=1
}

umount_pseudofs() {
	[[ $LBIND -eq 1 ]] || return 0
	for f in dev proc sys; do
		local target="$ROOTFS/$f"
		mountpoint -q "$target" || continue
		print_step "Desmontando pseudo FS: $target"
		umount -R "$target" 2>/dev/null || umount -l "$target"
	done
	LBIND=0
}

mount_pseudofsOLD() {
	[[ $LBIND -eq 0 ]] || return 0
	for f in sys dev proc; do
		print_step "Montando pseudo FS : $ROOTFS/$f"
		mkdir -p "$ROOTFS/$f"
		mount --rbind "/$f" "$ROOTFS/$f"
	done
	LBIND=1
}

umount_pseudofsOLD() {
	[[ $LBIND -eq 1 ]] || return 0
	for f in proc dev sys; do
		print_step "Desmontando pseudo FS: ${ROOTFS}/$f"
		mount --make-rslave "$ROOTFS/$f" 2>/dev/null
		umount "$ROOTFS/$f" 2>/dev/null || umount -l "$ROOTFS/$f" 2>/dev/null
	done
	LBIND=0
}

error_out() {
	trap - INT TERM 0
	umount_pseudofs || exit "${1:-0}"
	#	[ -d "$BUILDDIR" ] && [ -z "$KEEP_BUILDDIR" ] && rm -rf --one-file-system "$BUILDDIR"
	exit "${1:-0}"
}

copy_void_keys() {
	mkdir -p "$1"/var/db/xbps/keys
	cp keys/*.plist "$1"/var/db/xbps/keys
}

copy_dracut_files() {
	mkdir -p "$1"/usr/lib/dracut/modules.d/01vmklive
	cp dracut/vmklive/* "$1"/usr/lib/dracut/modules.d/01vmklive/
	# autologin none
	if $MAKE_FULL_X; then
		touch "$1"/usr/lib/dracut/modules.d/01vmklive/noautologin
	fi
}

copy_autoinstaller_files() {
	mkdir -p "$1"/usr/lib/dracut/modules.d/01autoinstaller
	cp dracut/autoinstaller/* "$1"/usr/lib/dracut/modules.d/01autoinstaller/
}

install_prereqs() {
	#	print_step "Instalando software para gerar a imagem de disco..."
	#	{
	#		LC_ALL=C XBPS_ARCH=$ARCH "$XBPS_INSTALL_CMD" -r "$VOIDHOSTDIR" ${XBPS_REPOSITORY} -c "$XBPS_HOST_CACHEDIR" -y $REQUIRED_PKGS -S
	#	} 2>&1 | tee -i -a "$BOOTLOG" >$([[ "$QUIET" == false ]] && echo /dev/stdout || echo "$LOGGER")
	#	result="${PIPESTATUS[0]}"
	#	[ $result -ne 0 ] && die "Failed to install required software, exiting..."

	cmd_logger "Instalando software para gerar a imagem de disco..." "
        LC_ALL=C \
        XBPS_ARCH=$ARCH "$XBPS_INSTALL_CMD" \
        --rootdir "$VOIDHOSTDIR" ${XBPS_REPOSITORY} \
        --cachedir "$XBPS_HOST_CACHEDIR" \
        --yes $REQUIRED_PKGS \
        --update \
        --sync
    "
}

cmd_install() {
	local PKGS="$*"
	LC_ALL=C \
		XBPS_ARCH=$BASE_ARCH \
		$XBPS_INSTALL_CMD \
		--unpack-only \
		--rootdir "$ROOTFS" ${XBPS_REPOSITORY} \
		--cachedir "$XBPS_CACHEDIR" \
		--update \
		--force --force \
		--yes $PKGS
}

install_packages() {
	cmd_logger "Instalando xbps pkg" '
        cmd_install -yu xbps
    '
	cmd_logger "Running dry-run for packages list selected..." '
		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" \
			--rootdir "$ROOTFS" ${XBPS_REPOSITORY} \
			--cachedir "$XBPS_CACHEDIR" \
			--unpack-only \
            --update \
			--yes \
			--dry-run $PACKAGE_LIST $INITRAMFS_PKGS
    '

	mount_pseudofs

	cmd_logger "Instalando void meta pkgs : $PACKAGE_LIST" '
        cmd_install $PACKAGE_LIST
    '

	cmd_logger "Instalando void meta pkgs : $INITRAMFS_PKGS" '
        cmd_install $INITRAMFS_PKGS
    '

	cmd_logger "Instalando void meta pkgs : ADDITIONAL" '
        cmd_install $ADDITIONAL_PKGS
	'

	if [[ -n $COMMON_PKGS ]]; then
		cmd_logger "Instalando void meta pkgs : COMMON" '
            cmd_install $COMMON_PKGS
		'
	fi

	if [[ -n $ADISTRO_PKGS ]]; then
		cmd_logger "Instalando void meta pkgs : ADISTRO" '
		    cmd_install $ADISTRO_PKGS
		'
	fi

	if [[ -n $AEXTRA_COMMON_PKGS ]]; then
		cmd_logger "Instalando void meta pkgs : AEXTRA_COMMON_PKGS" '
            cmd_install $AEXTRA_COMMON_PKGS
		'
	fi

	if [[ -n $ACONFIG_PKGS ]]; then
		for pkg in "${ACONFIG_PKGS[@]}"; do
			cmd_logger "Instalando void meta pkgs : $pkg" '
                cmd_install "$pkg"
    		'
		done
	fi

	if [[ -n $AEXTRA_PKGS ]]; then
		cmd_logger "Instalando void meta pkgs : AEXTRA" '
            cmd_install $AEXTRA_PKGS
		'
	fi
	#    sh_reconfigure_pass1

}

ignore_packages() {
	mkdir -p "$ROOTFS"/etc/xbps.d
	for pkg in $IGNORE_PKGS; do
		echo "ignorepkg=$pkg" >>"$ROOTFS"/etc/xbps.d/mkiso-ignore.conf
	done
}

install_skel_root() {
	cmd_logger "Copiando skel para usuario root" '
		cp -Rpva $ROOTFS/etc/skel/.bash* $ROOTFS/root/
		cp -Rpva $ROOTFS/etc/skel/.git-prompt.sh $ROOTFS/root/
		cp -Rpva $ROOTFS/etc/skel/.dircolors $ROOTFS/root/
        #rsync -a $ROOTFS/etc/skel/.config/neofetch/config.conf $ROOTFS/root/.config/neofetch/
    '
}

sh_reconfigure_pass1() {
	cmd_logger "Reconfigurando o ambiente - pass 1" '
		xbps-reconfigure -r "$ROOTFS" -f base-files >/dev/null 2>&1
		chroot "$ROOTFS" env -i xbps-reconfigure -f base-files

		# Enable choosen UTF-8 locale and generate it into the target rootfs.
		if [ -f "$ROOTFS"/etc/default/libc-locales ]; then
			sed -e "s/\#\(${LOCALE}.*\)/\1/g" -i "$ROOTFS"/etc/default/libc-locales
		fi
	'
}

sh_reconfigure_pass2() {
	cmd_logger "Reconfigurando o ambiente - pass 2" '
        chroot "$ROOTFS" env -i xbps-reconfigure -a
	'
}

finish_clean() {
	# Cleanup and remove useless stuff.
	xbps-remove -r "$ROOTFS" -Ooy >/dev/null 2>&1
	rm -rf "$ROOTFS"/var/cache/* "$ROOTFS"/run/* "$ROOTFS"/var/run/*
}

copy_include_directories() {
	for includedir in "${INCLUDE_DIRS[@]}"; do
		info_msg "=> copying include directory '$includedir' ..."
		find "$includedir" -mindepth 1 -maxdepth 1 -exec cp -rfpPv {} "$ROOTFS"/ \;
	done
}

configure_plymouth() {
	print_step "Configurando plymouth em: $ROOTFS/etc/dracut.conf.d/plymouth.conf"
	mkdir -p "$ROOTFS/etc/dracut.conf.d"
	echo 'add_dracutmodules+=" plymouth "' >"$ROOTFS/etc/dracut.conf.d/plymouth.conf"
	print_step "Configurando tema plymouth : voidbr"
	#chroot "$ROOTFS" env -i plymouth-set-default-theme fade-in
	#chroot "$ROOTFS" env -i plymouth-set-default-theme voidx
	chroot "$ROOTFS" env -i plymouth-set-default-theme voidbr
	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Falha ao configurar tema"

	print_step "Criando wrapper plymouth $ROOTFS/usr/bin/plymouth-show-log-voidlinux.sh"
	mkdir -p "$ROOTFS/usr/bin"
	cat <<'EOF' >"$ROOTFS/usr/bin/plymouth-show-log-voidlinux.sh"
#!/usr/bin/env bash

file=/var/log/boot.log
# Exibe uma mensagem inicial usando o Plymouth
plymouth display-message --text="Booting Void Linux"
desg -f daemon,user,auth | while read -r line; do
  # Exibe as últimas 50 caracteres da linha usando o Plymouth
  plymouth display-message --text="${line:0:50}"
  echo "${line:0:50}"
  sleep 0.2
  if ! plymouth --ping; then
    echo "Plymouth morreu, saindo..."
    break
  fi
done
# Exibe uma mensagem de encerramento caso o Plymouth morra
plymouth display-message --text="Initialization completed"
EOF

	# Torna o script executável
	chmod +x "$ROOTFS/usr/bin/plymouth-show-log-voidlinux.sh"
	file="$ROOTFS/etc/runit/1"
	grep -q plymouth-show-log-voidlinux "$file" || sed -i '/^#!/a\
[ -r /usr/bin/plymouth-show-log-voidlinux.sh ] && . /usr/bin/plymouth-show-log-voidlinux.sh
    ' "$file"

}

configure_service_boot_logger() {
	print_step "Configurando serviço boot-logger em: $ROOTFS/etc/sv/"
	mkdir -p "$ROOTFS/etc/sv/boot-logger"
	tee "$ROOTFS/etc/sv/boot-logger/run" >/dev/null <<'EOF'
#!/bin/sh
LOG_FILE="/var/log/boot.log"
# garante diretório
mkdir -p /var/log
# evita sobrescrever sempre (append)
exec dmesg -w >> "$LOG_FILE" 2>&1
EOF
	chmod +x "$ROOTFS/etc/sv/boot-logger/run"
	# link simbólico no runit
	ln -sf "/etc/sv/boot-logger" "$ROOTFS/etc/runit/runsvdir/default/"
}

configure_service_plymouth_log() {
	print_step "Configurando serviço plymouth-log em: $ROOTFS/etc/sv/"
	mkdir -p "$ROOTFS/etc/sv/plymouth-log"
	tee "$ROOTFS/etc/sv/plymouth-log/run" >/dev/null <<EOF
#!/bin/sh
[ -r ./conf ] && . ./conf
exec /usr/bin/plymouth-show-log-voidlinux.sh
EOF
	chmod +x "$ROOTFS/etc/sv/plymouth-log/run"
	ln -sf "/etc/sv/plymouth-log" "$ROOTFS/etc/runit/runsvdir/default/"
}

configure_service_plymouth_stop() {
	print_step "Configurando serviço plymouth-stop em: $ROOTFS/etc/sv"
	mkdir -p "$ROOTFS/etc/sv/plymouth-stop"
	tee "$ROOTFS/etc/sv/plymouth-stop/run" >/dev/null <<EOF
#!/bin/sh
[ -r ./conf ] && . ./conf
exec /usr/bin/plymouth --quit
EOF
	chmod +x "$ROOTFS/etc/sv/plymouth-stop/run"
	ln -sf "/etc/sv/plymouth-stop" "$ROOTFS/etc/runit/runsvdir/default/"
}

configure_etc_runit_core_services_quit_plymouth() {
	print_step "Configurando script plymouth-stop em: $ROOTFS/etc/runit/core-services/"
	tee "$ROOTFS/etc/runit/core-services/99-voidbr-plymouth-quit.sh" >/dev/null <<EOF
#!/bin/sh
if command -v plymouth >/dev/null; then
    plymouth quit
fi
EOF
	chmod +x "$ROOTFS/etc/runit/core-services/99-voidbr-plymouth-quit.sh"
}

generate_initramfs() {
	local _args

	# Garantia de segurança: verifica se KERNELVERSION está definida e se o diretório de módulos existe no ROOTFS
	if [ -z "$KERNELVERSION" ] || [ ! -d "$ROOTFS/lib/modules/$KERNELVERSION" ]; then
		# Tenta autodetectar a versão real instalada no chroot para não quebrar o script
		local detected_kver=$(ls "$ROOTFS/lib/modules" | head -n1)
		if [ -n "$detected_kver" ]; then
			KERNELVERSION="$detected_kver"
		else
			die "Erro: Kernel não foi encontrado instalado em $ROOTFS/lib/modules!"
		fi
	fi

	print_step "Gerando imagem initramfs ($INITRAMFS_COMPRESSION): ${yellow}$BOOT_DIR/initrd"
	{
		copy_dracut_files "$ROOTFS"
		copy_autoinstaller_files "$ROOTFS"

		# Executa o dracut preservando o ambiente necessário para evitar o erro de 'dwarning: command not found'
		chroot "$ROOTFS" /usr/bin/dracut -N --"${INITRAMFS_COMPRESSION}" --add-drivers "ahci" --force-add "vmklive autoinstaller" --omit systemd "/boot/initrd" $KERNELVERSION
		result="${PIPESTATUS[0]}"
		[ $result -ne 0 ] && die "Failed to generate the initramfs"

		# Verifica se o arquivo de initrd foi realmente gerado antes de tentar mover ou copiar
		if [ ! -f "$ROOTFS/boot/initrd" ]; then
			die "Erro crítico: O arquivo $ROOTFS/boot/initrd não foi gerado pelo dracut!"
		fi

		mv "$ROOTFS"/boot/initrd "$BOOT_DIR"
		cp "$ROOTFS"/boot/vmlinuz-$KERNELVERSION "$BOOT_DIR"/vmlinuz
		cp -Rpva "$ROOTFS"/boot/grub/themes "$BOOT_DIR/grub/"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

cleanup_rootfs() {
	print_step "Limpando rootfs..."
	for f in ${INITRAMFS_PKGS}; do
		revdeps=$(xbps-query -r "$ROOTFS" -X $f)
		if [ -n "$revdeps" ]; then
			xbps-pkgdb -r "$ROOTFS" -m auto $f
		else
			xbps-remove -r "$ROOTFS" -Ry ${f} >/dev/null 2>&1
		fi
	done
	rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01vmklive
	rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01autoinstaller
}

generate_isolinux_boot() {
	print_step "Gerando suporte isolinux para systema : PC-BIOS"
	cp -f "$SYSLINUX_DATADIR"/isolinux.bin "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/ldlinux.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/libcom32.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/vesamenu.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/libutil.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/chain.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/reboot.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/poweroff.c32 "$ISOLINUX_DIR"
	cp -f isolinux/isolinux.cfg.in "$ISOLINUX_DIR"/isolinux.cfg
	cp -f ${SPLASH_IMAGE} "$ISOLINUX_DIR"

	sed -i -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
		-e "s|@@KERNVER@@|${KERNELVERSION}|" \
		-e "s|@@KEYMAP@@|${KEYMAP}|" \
		-e "s|@@ARCH@@|$BASE_ARCH|" \
		-e "s|@@LOCALE@@|${LOCALE}|" \
		-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
		-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
		"$ISOLINUX_DIR"/isolinux.cfg

	# include memtest86+
	#cp -f "$VOIDHOSTDIR"/boot/memtest.bin "$BOOT_DIR"
	cp -f "$VOIDHOSTDIR"/boot/memtest86+/memtest.bin "$BOOT_DIR"
}

generate_grub_efi_boot() {
	print_step "Gerando suporte GRUB para sistema : EFI"
	{
		cp -f grub/grub.cfg "$GRUB_DIR"
		cp -f grub/grub_void.cfg.in "$GRUB_DIR"/grub_void.cfg
		sed -i -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
			-e "s|@@KERNVER@@|${KERNELVERSION}|" \
			-e "s|@@KEYMAP@@|${KEYMAP}|" \
			-e "s|@@ARCH@@|$BASE_ARCH|" \
			-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
			-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
			-e "s|@@LOCALE@@|${LOCALE}|" "$GRUB_DIR"/grub_void.cfg
		mkdir -p "$GRUB_DIR"/fonts
		cp -f "$GRUB_DATADIR"/unicode.pf2 "$GRUB_DIR"/fonts
		cp -fr "VOIDHOSTDIR"/unicode.pf2 "$GRUB_DIR"/fonts

		modprobe -q loop || :

		# Create EFI vfat image.
		truncate -s 32M "$GRUB_DIR"/efiboot.img
		mkfs.vfat -F12 -S 512 -n "grub_uefi" "$GRUB_DIR/efiboot.img"

		GRUB_EFI_TMPDIR="$(mktemp --tmpdir="$HOME" -d)"
		LOOP_DEVICE="$(losetup --show --find "${GRUB_DIR}"/efiboot.img)"
		mount -o rw,flush -t vfat "${LOOP_DEVICE}" "${GRUB_EFI_TMPDIR}"

		cp -a "$IMAGEDIR"/boot "$VOIDHOSTDIR"
		xbps-uchroot "$VOIDHOSTDIR" grub-mkstandalone -- \
			--directory="/usr/lib/grub/i386-efi" \
			--format="i386-efi" \
			--output="/tmp/bootia32.efi" \
			"boot/grub/grub.cfg"
		if [ $? -ne 0 ]; then
			umount "$GRUB_EFI_TMPDIR"
			losetup --detach "${LOOP_DEVICE}"
			die "Failed to generate EFI loader"
		fi
		mkdir -p "${GRUB_EFI_TMPDIR}"/EFI/BOOT
		cp -f "$VOIDHOSTDIR"/tmp/bootia32.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTIA32.EFI
		xbps-uchroot "$VOIDHOSTDIR" grub-mkstandalone -- \
			--directory="/usr/lib/grub/x86_64-efi" \
			--format="x86_64-efi" \
			--output="/tmp/bootx64.efi" \
			"boot/grub/grub.cfg"
		if [ $? -ne 0 ]; then
			umount "$GRUB_EFI_TMPDIR"
			losetup --detach "${LOOP_DEVICE}"
			die "Failed to generate EFI loader"
		fi
		cp -f "$VOIDHOSTDIR"/tmp/bootx64.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTX64.EFI
		umount "$GRUB_EFI_TMPDIR"
		losetup --detach "${LOOP_DEVICE}"
		rm -rf "$GRUB_EFI_TMPDIR"

		# include memtest86+
		cp -f "$VOIDHOSTDIR"/boot/memtest.efi "$BOOT_DIR"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

get_compression_options() {
	local param
	case $1 in
	gzip) param=" -noappend -comp gzip -Xcompression-level 1" ;;
	xz) param=" -noappend -b 1048576 -comp xz -Xdict-size 100%" ;;
	zstd) param=" -noappend -b 1M -comp zstd -Xcompression-level 3" ;;
	lzma) param=" -noappend -b 1M -comp lzma" ;;
	lz4) param=" -noappend -b 1M -comp lz4 -Xhc" ;;
	esac
	echo "$param"
}

generate_squashfs() {
	local options=$(get_compression_options "$SQUASHFS_COMPRESSION")

	umount_pseudofs
	print_step "Gerando image squashfs ($SQUASHFS_COMPRESSION) de rootfs: ${yellow}$IMAGEDIR/LiveOS/squashfs.img"
	{
		ROOTFS_SIZE=$(du --apparent-size -sm "$ROOTFS" | awk '{print $1}')
		mkdir -p "$BUILDDIR/tmp/LiveOS"
		truncate -s "$((ROOTFS_SIZE + ROOTFS_SIZE))M" "$BUILDDIR"/tmp/LiveOS/ext3fs.img
		mkdir -p "$BUILDDIR/tmp-rootfs"
		mkfs.ext3 -F -m1 "$BUILDDIR/tmp/LiveOS/ext3fs.img" 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		mount -o loop "$BUILDDIR/tmp/LiveOS/ext3fs.img" "$BUILDDIR/tmp-rootfs"
		cp -a "$ROOTFS"/* "$BUILDDIR"/tmp-rootfs/
		umount -f "$BUILDDIR/tmp-rootfs"
		mkdir -p "$IMAGEDIR/LiveOS"

		#       "$VOIDHOSTDIR"/usr/bin/mksquashfs "$BUILDDIR"/tmp "$IMAGEDIR"/LiveOS/squashfs.img -comp "${SQUASHFS_COMPRESSION}" || die "Failed to generate squashfs image"
		#       "$VOIDHOSTDIR"/usr/bin/mksquashfs "$BUILDDIR"/tmp "$IMAGEDIR"/LiveOS/squashfs.img "$options" || die "Failed to generate squashfs image"
		"$VOIDHOSTDIR"/usr/bin/mksquashfs "$BUILDDIR"/tmp "$IMAGEDIR"/LiveOS/squashfs.img -noappend -b 1M -comp zstd -Xcompression-level 3 || die "Failed to generate squashfs image"

		chmod 444 "$IMAGEDIR/LiveOS/squashfs.img"
		#       [ -z "$KEEP_BUILDDIR" ] && rm -rf "$ROOTFS"
		rm -rf "$BUILDDIR/tmp-rootfs"
		rm -rf "$BUILDDIR/tmp"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

generate_iso_image() {
	print_step "Gerando imagem ISO: ${yellow}$OUTPUT_FILE"
	{
		"$VOIDHOSTDIR"/usr/bin/xorriso \
			-as mkisofs \
			-iso-level 3 -rock -joliet \
			-max-iso9660-filenames -omit-period \
			-omit-version-number -relaxed-filenames -allow-lowercase \
			-volid "$VOL_ID" \
			-eltorito-boot boot/isolinux/isolinux.bin \
			-eltorito-catalog boot/isolinux/boot.cat \
			-no-emul-boot -boot-load-size 4 -boot-info-table \
			-eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot \
			-isohybrid-mbr "$SYSLINUX_DATADIR"/isohdpfx.bin \
			-output "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	hsize=$(du -sh "$OUTPUT_FILE" | awk '{print $1}')
	info_msg "Iso file created: ${green}$(readlink -f "$OUTPUT_FILE") ($hsize) successfully.${reset}"
}

usage() {
	sh_setVarColors
	cat <<EOF
${bold}Usage:${rst} $PROGNAME [options]

${green}Generates a basic live ISO image of Void Linux.${rst}
This ISO image can be written to a CD/DVD-ROM or any USB stick.
To generate a more complete live ISO image, use build-x86-images.sh.${rst}

${bold}OPTIONS${rst}
  -a <arch>          ${cyan}Set XBPS_ARCH in the ISO image${rst}
  -b <system-pkg>    ${cyan}Set an alternative base package${rst} (default: base-system)
  -r <repo>          ${cyan}Use this XBPS repository${rst} (can be used multiple times)
  -c <cachedir>      ${cyan}XBPS cache directory${rst} (default: ./xbps-cachedir-<arch>)
  -k <keymap>        ${cyan}Default keymap${rst} (default: us)
  -l <locale>        ${cyan}Default locale${rst} (default: en_US.UTF-8)

  -i <type>          ${cyan}Initramfs compression${rst} (lz4|gzip|bzip2|xz|zstd|lzma|lzo)
  -s <type>          ${cyan}Squashfs compression${rst} (lz4|gzip|bzip2|xz|zstd|lzma|lzo)

  -o <file>          ${cyan}Output ISO filename${rst}
  -p "<pkg> ..."     ${cyan}Additional packages${rst}
  -g "<pkg> ..."     ${cyan}Ignore packages${rst}
  -I <dir>           ${cyan}Include directory into ROOTFS${rst}

  -S "<service> ..." ${cyan}Enable services${rst}
  -C "<arg> ..."     ${cyan}Extra kernel cmdline args${rst}
  -T <title>         ${cyan}Bootloader title${rst} (default: Void Linux)
  -v linux<ver>      ${cyan}Custom kernel version${rst}

  -K                 ${yellow}Do not remove builddir${rst}
  -n                 ${yellow}Reuse existing squashfs${rst}
  -Q                 ${yellow}Quiet mode${rst}

${bold}Desktop presets:${rst}
  -W  ${green}AWESOME${rst}
  -N  ${green}CINNAMON${rst}
  -E  ${green}ENLIGHTENMENT${rst}
  -F  ${green}FLUXBOX${rst}
  -G  ${green}GNOME${rst}
  -P  ${green}KDE PLASMA${rst}
  -X  ${green}XFCE (base)${rst}
  -Y  ${green}XFCE${rst}
  -M  ${green}MATE${rst}
  -A  ${green}ALL X${rst}

  -h                 Show this help and exit
  -V                 Show version and exit
EOF
}

sh_config_distroname() {
	declare -ga name
	print_step "Configurando distro name"
	if $MAKE_FULL_X; then
		title='VoidBR Linux Live Full X'
		VOL_ID='VOIDBR_LIVE_FULLX'
		name='fullx'
	elif $MAKE_ENLIGHTENMENT; then
		title='VoidBR Linux Live Enlightenment'
		VOL_ID='VOIDBR_LIVE_ENLIGHTENMENT'
		name='enlightenment'
	elif $MAKE_AWESOME; then
		title='VoidBR Linux Live Awesome'
		VOL_ID='VOIDBR_LIVE_AWESOME'
		name='awesome'
	elif $MAKE_FLUXBOX; then
		title='VoidBR Linux Live Fluxbox'
		VOL_ID='VOIDBR_LIVE_FLUXBOX'
		name='fluxbox'
	elif $MAKE_PLASMA; then
		title='VoidBR Linux Live KDE Plasma'
		VOL_ID='VOIDBR_LIVE_PLASMA'
		name='plasma'
	elif $MAKE_GNOME; then
		title='VoidBR Linux Live GNOME'
		VOL_ID='VOIDBR_LIVE_GNOME'
		name='gnome'
	elif $MAKE_XFCE_BASE; then
		title='VoidBR Linux Live Xfce Base'
		VOL_ID='VOIDBR_LIVE_XFCE_BASE'
		name='xfce-base'
	elif $MAKE_XFCE; then
		title='VoidBR Linux Live XFCE'
		VOL_ID='VOIDBR_LIVE_XFCE'
		name='xfce'
	elif $MAKE_CINNAMON; then
		title='VoidBR Linux Live Cinnamon'
		VOL_ID='VOIDBR_LIVE_CINNAMON'
		name='cinnamon'
	elif $MAKE_MATE; then
		title='VoidBR Linux Live Mate'
		VOL_ID='VOIDBR_LIVE_MATE'
		name='mate'
	else
		title='VoidBR Linux Live Base'
		VOL_ID='VOIDBR_LIVE_BASE'
		name='base'
	fi
}

sh_print_resume() {
	replicate
	print_step "Building ISO    => ${yellow}${title}${reset}"
	print_step "Profile         => ${yellow}${name}${reset}"
	print_step "ROOTDIR         => ${yellow}${ROOTDIR}${reset}"
	print_step "ROOTFS          => ${yellow}${ROOTFS}${reset}"
	print_step "VOIDHOSTDIR     => ${yellow}${VOIDHOSTDIR}${reset}"
	print_step "ARCH            => ${yellow}${ARCH}${reset}"
	print_step "Output file ISO => ${yellow}${OUTPUT_FILE}${reset}"
	print_step "Compression SFS => ${yellow}${SQUASHFS_COMPRESSION}${reset}"
	print_step "Compression RAM => ${yellow}${INITRAM_COMPRESSION}${reset}"
	print_step "ISO LABEL       => ${yellow}${VOL_ID}${reset}"
	replicate
}

cmd_logger() {
  local cmd="$*"
	local msg="$1"
	local check_error="$3"

	print_step "$msg"
  #! $quiet msg_tab "${cyan}[⚙   ] [running] : ${reset} $cmd"
	{
		eval "$2"
		#   } 2>&1 | tee -i -a "$BOOTLOG" >$([[ "$QUIET" == false ]] && echo /dev/stdout || echo "$LOGGER")
	} \
		1> >(tee -i -a "$BOOTLOG" >>"$LOGGER") \
		2> >(tee -i -a "$BOOTLOG" >$([[ "$QUIET" == false ]] && echo /dev/stderr || echo /dev/null))
	local result="${PIPESTATUS[0]}"
	[[ -z $check_error ]] && check_error=1
	[[ $check_error -eq 0 ]] && return
	[[ $result -ne 0 ]] && die "FAILED... $msg - exiting..."
}

sh_configure_packages() {
	#	sh_config_distroname
	sh_choose_packages_base
	if $MAKE_X; then
		sh_choose_packages_common_X
		if $MAKE_FULL_X; then
			STEP_COUNT=72
			sh_choose_packages_xfce_base
			sh_choose_packages_xfce
			sh_choose_packages_gnome
			sh_choose_packages_plasma
			sh_choose_packages_cinnamon
			sh_choose_packages_mate
			sh_choose_packages_awesome
			sh_choose_packages_enlightenment
			sh_choose_packages_fluxbox
		elif $MAKE_ENLIGHTENMENT; then
			sh_choose_packages_enlightenment
		elif $MAKE_AWESOME; then
			sh_choose_packages_awesome
		elif $MAKE_FLUXBOX; then
			sh_choose_packages_fluxbox
		elif $MAKE_PLASMA; then
			sh_choose_packages_plasma
		elif $MAKE_GNOME; then
			sh_choose_packages_gnome
		elif $MAKE_XFCE_BASE; then
			sh_choose_packages_xfce_base
		elif $MAKE_XFCE; then
			sh_choose_packages_xfce_base
			sh_choose_packages_xfce
		elif $MAKE_CINNAMON; then
			sh_choose_packages_cinnamon
		elif $MAKE_MATE; then
			sh_choose_packages_mate
		fi
	fi
}

sh_configure_rootfs() {
	# Configure dracut to use overlayfs for the writable overlay.
	BOOT_CMDLINE="$BOOT_CMDLINE rd.live.overlay.overlayfs=1 "
	ARCH=$(xbps-uhelper arch)

	# Set defaults
	: ${BASE_ARCH:=$(xbps-uhelper arch 2>/dev/null || uname -m)}
	: ${XBPS_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${BASE_ARCH}}
	: ${XBPS_HOST_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${ARCH}}
	: ${KEYMAP:=br-abnt2}
	: ${LOCALE:=pt_BR.UTF-8}
	: ${INITRAMFS_COMPRESSION:=xz}
	: ${SQUASHFS_COMPRESSION:=zstd}
	: ${BASE_SYSTEM_PKG:=base-system}
	: ${BOOT_TITLE:="$title"}

	# Required packages in the image for a working system.
	PACKAGE_LIST="$BASE_SYSTEM_PKG $PACKAGE_LIST"

	#mount -o remount,size=18G,mode=1777 tmpfs /tmp
	#ROOTDIR='/tmp'
	#mount -o remount,size=18G,mode=1777 tmpfs /dev/shm
	#ROOTDIR='/dev/shm'
	#mount /dev/nvme0n1p2 /mnt/voidlinux
	#ROOTDIR='/mnt/voidlinux/@/lixo'
	ROOTDIR="/lfs/voidlinux"

	if [ -n "$ROOTDIR" ]; then
		BUILDDIR="$ROOTDIR/$name"
		#		[ -d "$BUILDDIR" ] && [ -z "$KEEP_BUILDDIR" ] && rm -rf --one-file-system "$BUILDDIR"
		mkdir -p "$BUILDDIR"
	else
		BUILDDIR=$(mktemp --tmpdir="$(pwd -P)" -d)
	fi

	BUILDDIR=$(readlink -f "$BUILDDIR")
	IMAGEDIR="$BUILDDIR/image"
	#	ROOTFS="$IMAGEDIR/rootfs"
	ROOTFS="$BUILDDIR/rootfs"
	#	VOIDHOSTDIR="$BUILDDIR/void-host"
	VOIDHOSTDIR="$ROOTDIR/void-host"
	BOOT_DIR="$IMAGEDIR/boot"
	ISOLINUX_DIR="$BOOT_DIR/isolinux"
	GRUB_DIR="$BOOT_DIR/grub"
	ISOLINUX_CFG="$ISOLINUX_DIR/isolinux.cfg"

	sh_create_etc_xbps_d_conf_00_repository_main_conf

	[ "${#INCLUDE_DIRS[@]}" -gt 0 ] && STEP_COUNT=$((STEP_COUNT + 1))
	[ -n "${IGNORE_PKGS}" ] && STEP_COUNT=$((STEP_COUNT + 1))

	: ${SYSLINUX_DATADIR:="$VOIDHOSTDIR"/usr/lib/syslinux}
	: ${GRUB_DATADIR:="$VOIDHOSTDIR"/usr/share/grub}
	: ${SPLASH_IMAGE:=data/splash.png}
	: ${XBPS_INSTALL_UNPACK_ONLY:=xbps-install --unpack-only --yes --ignore-file-conflicts}
	: ${XBPS_INSTALL_CMD:=xbps-install}
	: ${XBPS_REMOVE_CMD:=xbps-remove}
	: ${XBPS_QUERY_CMD:=xbps-query}
	: ${XBPS_RINDEX_CMD:=xbps-rindex}
	: ${XBPS_UHELPER_CMD:=xbps-uhelper}
	: ${XBPS_RECONFIGURE_CMD:=xbps-reconfigure}
	: ${OUTPUT_FILE="voidbr-live-$name-${BASE_ARCH}-$(uname -r)-$(sh_diahora).iso"}
	mkdir -p "$ROOTFS" "$VOIDHOSTDIR" "$ISOLINUX_DIR" "$GRUB_DIR"

  # Validação de espaço em disco inserida antes do resumo e do início das instalações
	verificar_espaco_livre

	sh_print_resume

}

sh_configure_linux() {
	print_step "Configurando kernel"
	# Get linux version for ISO - If linux version option specified use
	if [ -n "$LINUX_VERSION" ]; then
		if ! echo "$LINUX_VERSION" | grep "linux[0-9._]\+"; then
			die "-v option must be in format linux<version>"
		fi
		_linux_series="$LINUX_VERSION"
		PACKAGE_LIST="$PACKAGE_LIST $LINUX_VERSION"
	else # Otherwise find latest stable version from linux meta-package
		_linux_series=$(
			XBPS_ARCH=$BASE_ARCH $XBPS_QUERY_CMD \
				--rootdir "$ROOTFS" ${XBPS_REPOSITORY:=-R} \
				--deps linux |
				grep 'linux[0-9._]\+'
		)
	fi

	_kver=$(
		XBPS_ARCH=$BASE_ARCH $XBPS_QUERY_CMD \
			--rootdir "$ROOTFS" ${XBPS_REPOSITORY:=-R} \
			--property pkgver ${_linux_series}
	)
	KERNELVERSION=$(
		$XBPS_UHELPER_CMD getpkgversion ${_kver}
	)
	if [ "$?" -ne "0" ]; then
		die "Failed to find kernel package version"
	fi
	OUTPUT_FILE="voidbr-live-$name-${BASE_ARCH}-${KERNELVERSION}-$(sh_diahora).iso"
	{
		echo "KERNELVERSION=$KERNELVERSION"
		echo "OUTPUT_FILE=$OUTPUT_FILE"
	} >kernel-${name}.txt

	print_step "Kernel Version: $KERNELVERSION"

}

sh_install_rootfs() {
	replicate
	cmd_logger "Sincronizando dados do repositório XBPS..." "
		copy_void_keys "$ROOTFS"
		copy_void_keys "$VOIDHOSTDIR"
		LC_ALL=C XBPS_ARCH=$BASE_ARCH $XBPS_INSTALL_CMD -Sy -r "$ROOTFS" -R ${XBPS_REPOSITORY}
		LC_ALL=C XBPS_ARCH=$ARCH $XBPS_INSTALL_CMD -Sy -r "$VOIDHOSTDIR" -R ${XBPS_REPOSITORY}
    "
	sh_configure_linux

	#	: ${OUTPUT_FILE="voidbr-live-$name-${BASE_ARCH}-${KERNELVERSION}-$(sh_diahora).iso"}
	install_prereqs

	mkdir -p "$ROOTFS"/etc
	[ -s data/motd ] && cp data/motd "$ROOTFS"/etc
	[ -s data/issue ] && cp data/issue "$ROOTFS"/etc

	if [ -n "$IGNORE_PKGS" ]; then
		print_step "Ignoring packages in the rootfs: ${IGNORE_PKGS} ..."
		ignore_packages
	fi

	print_step "Instalando pacotes void em $ROOTFS..."
	install_packages
	install_skel_root
	sh_reconfigure_pass2
	finish_clean
}

enable_services() {
	SERVICE_LIST="$*"
	for service in $SERVICE_LIST; do
		print_step "Ativando serviço : $service"
		if ! [ -e $ROOTFS/etc/sv/$service ]; then
			info_msg "service $service not in $ROOTFS/etc/sv"
			continue
		fi
		ln -sf /etc/sv/$service $ROOTFS/etc/runit/runsvdir/default/
	done
}

sh_make_iso() {
	mount_pseudofs
	#dica: No Void, com dbus ativo, o elogind e o polkitd sobem automaticamente.
	#      Você não precisa ativar os serviços deles no runit.
	: ${DEFAULT_SERVICE_LIST:=agetty-tty1 agetty-tty2 agetty-tty3 agetty-tty4 agetty-tty5 agetty-tty6 dbus socklog-unix nanoklogd udevd sshd NetworkManager dhcpcd chronyd}
	if $MAKE_X; then
		if $MAKE_GNOME; then
			: ${ADDITIONAL_SERVICE_LIST:=gdm avahi-daemon}
		else
			: ${ADDITIONAL_SERVICE_LIST:=lightdm avahi-daemon}
		fi
	fi

	if $MAKE_ENLIGHTENMENT; then
		: ${EXTRA_SERVICE_LIST:=acpid connmand}
	fi

	enable_services ${DEFAULT_SERVICE_LIST} ${SERVICE_LIST} ${ADDITIONAL_SERVICE_LIST} ${EXTRA_SERVICE_LIST}

	if [ "${#INCLUDE_DIRS[@]}" -gt 0 ]; then
		print_step "Copying directory structures into the rootfs ..."
		copy_include_directories
	fi

	print_step "Substituir 'CDLABEL=VOID_LIVE' por 'CDLABEL=$VOL_ID' em ./grub/grub_void.cfg.in e ./isolinux/isolinux.cfg.in"
	for file in ./grub/grub_void.cfg.in ./isolinux/isolinux.cfg.in; do
		sudo sed -i "s/CDLABEL=[^ ]*/CDLABEL=${VOL_ID}/g" "$file"
	done

	configure_plymouth
	#configure_service_boot_logger
	#configure_service_plymouth_log
	#configure_service_plymouth_stop
	configure_etc_runit_core_services_quit_plymouth
	generate_initramfs
	generate_isolinux_boot
	generate_grub_efi_boot
	cleanup_rootfs
	local conf="$ROOTFS/etc/xbps.d/00-repository-main.conf"
	sh_remove_etc_xbps_00_repository_main_conf
	generate_squashfs
	#	generate_iso_image
}

sh_remove_etc_xbps_00_repository_main_conf() {
	local conf="$ROOTFS/etc/xbps.d/00-repository-main.conf"
	rm -f $conf
}

verificar_espaco_livre() {
	# Garante que há pelo menos 15GB livres no diretório de compilação
	local espaco_livre=$(df -m "$ROOTDIR" | awk 'NR==2 {print $4}')
	if [ "$espaco_livre" -lt 15360 ]; then
		die "Espaço insuficiente em $ROOTDIR. São necessários pelo menos 15GB livres."
	fi
}

automatic=false
new_args=()
for arg in "$@"; do
	if [[ "$arg" == "--automatic" ]]; then
		automatic=true
		continue
	fi
	new_args+=("$arg")
done

# substitui os argumentos atuais
set -- "${new_args[@]}"

for arg in "$@"; do
	case "$arg" in
	-h | --help)
		usage
		exit 0
		;;
	esac
done

# shellcheck source=./lib.sh
source ./lib.sh

# main()
#
sh_setVarColors
sh_setEnvironment
sh_setLanguage
sh_checkDependencies

while getopts "a:b:r:c:C:T:Kk:l:i:I:S:s:o:p:g:v:VhXxYyQqWwNnEeFfAGPmM" opt; do
	case $opt in
	a) BASE_ARCH="$OPTARG" ;;
	b) BASE_SYSTEM_PKG="$OPTARG" ;;
	r) XBPS_REPOSITORY="--repository=$OPTARG $XBPS_REPOSITORY" ;;
	c) XBPS_CACHEDIR="$OPTARG" ;;
	g) IGNORE_PKGS="$IGNORE_PKGS $OPTARG" ;;
	K) KEEP_BUILDDIR=1 ;;
	k) KEYMAP="$OPTARG" ;;
	l) LOCALE="$OPTARG" ;;
	I) INCLUDE_DIRS+=("$OPTARG") ;;
	i) INITRAMFS_COMPRESSION="$OPTARG" ;;
	s) SQUASHFS_COMPRESSION="$OPTARG" ;;
	S) SERVICE_LIST="$SERVICE_LIST $OPTARG" ;;
	o) OUTPUT_FILE="$OPTARG" ;;
	p) PACKAGE_LIST="$PACKAGE_LIST $OPTARG" ;;
	C) BOOT_CMDLINE="$OPTARG" ;;
	T) BOOT_TITLE="$OPTARG" ;;
	x | X)
		MAKE_X=true
		MAKE_XFCE_BASE=true
		;;
	y | Y)
		MAKE_X=true
		MAKE_XFCE=true
		;;
	n | N)
		MAKE_X=true
		MAKE_CINNAMON=true
		;;
	m | M)
		MAKE_X=true
		MAKE_MATE=true
		;;
	w | W)
		MAKE_X=true
		MAKE_AWESOME=true
		;;
	e | E)
		MAKE_X=true
		MAKE_ENLIGHTENMENT=true
		;;
	f | F)
		MAKE_X=true
		MAKE_FLUXBOX=true
		;;
	G)
		MAKE_X=true
		MAKE_GNOME=true
		;;
	P)
		MAKE_X=true
		MAKE_PLASMA=true
		;;
	A)
		MAKE_X=true
		MAKE_FULL_X=true
		;;
	q | Q) QUIET=true ;;
	v) LINUX_VERSION="$OPTARG" ;;
	V)
		version
		exit 0
		;;
	h)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

# Check for root permissions.
if [ "$(id -u)" -ne 0 ]; then
	die "Must be run as root, exiting..."
fi

sh_config_distroname
sh_configure_rootfs
umount_pseudofs
sh_configure_packages
sh_install_rootfs
sh_make_iso
generate_iso_image
