#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
# vim: set ts=4 sw=4 et:
#
# mkiso
#
# Created: 2023/09/18 - 09:05
# Updated: seg 07 set 2026 06:13:23 -04
#
# Copyright (c) 2019-2026 Vilmar Catafesta <vcatafesta@gmail.com>
# Copyright (c) 2009-2015 Juan Romero Pardines.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#xbps-install -U -r /tmp/fakeroot --repository=https://repo-fastly.voidlinux.org/current bash -S

export LANGUAGE="${LANGUAGE:-pt_BR}"
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=mkiso
export TERM=${TERM:-xterm}
export TERM=${TERM:-xterm-256color}

# Armazenar os aliases atuais em uma variável
OLD_ALIASES=$(alias)
# Desativar todos os aliases
unalias -a

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
#set -x
#set -e
shopt -s extglob

#system
readonly APP="${0##*/}"
readonly _VERSION_='0.08.28-20260828'

# Guarda os argumentos originais ANTES de qualquer filtragem, para que uma
# eventual re-execução via elevate_to_root() (sh_checkroot) preserve exatamente
# o que o usuário digitou, incluindo --automatic.
ORIGINAL_ARGS=("$@")

# Pre-parse de --automatic e --bootloader: precisa acontecer ANTES do
# source ./lib.sh, pois select_mirrors_dialog() (chamada automaticamente
# ao carregar lib.sh) usa a variável $automatic internamente, e getopts
# não lida com opções longas (por isso o filtro manual aqui).
automatic=false
declare -g BOOTLOADER="grub"
new_args=()
for arg in "$@"; do
	if [[ "$arg" == "--automatic" ]]; then
		automatic=true
		continue
	fi
	if [[ "$arg" == --bootloader=* ]]; then
		BOOTLOADER="${arg#--bootloader=}"
		continue
	fi
	new_args+=("$arg")
done
set -- "${new_args[@]}"

case "$BOOTLOADER" in
grub | limine) ;;
*)
	echo "ERRO: --bootloader inválido: '$BOOTLOADER' (use 'grub' ou 'limine')" >&2
	exit 1
	;;
esac

# shellcheck source=./lib.sh
source ./lib.sh

readonly distro=$(detect_distro)
readonly DEPENDENCIES=(rsync sed grep cat umount losetup tput chroot mkfs.vfat tee)

# Eleva privilégios automaticamente se necessário (re-executa como root via
# sudo/su, preservando os argumentos originais).
sh_checkroot "${ORIGINAL_ARGS[@]}"

cleanup() {
	umount_pseudofs
	# Restaurar os aliases quando o script terminar
	eval "$OLD_ALIASES"
}
trap 'cleanup' EXIT
trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM HUP

umask 022
declare -g MAKE_X=false
declare -g MAKE_XFCE_BASE=false
declare -g MAKE_XFCE=false
declare -g MAKE_AWESOME=false
declare -g MAKE_ENLIGHTENMENT=false
declare -g MAKE_PLASMA=false
declare -g MAKE_PLASMA_LOUVORJA_PIANO=false
declare -g MAKE_GNOME=false
declare -g MAKE_CINNAMON=false
declare -g MAKE_MATE=false
declare -g MAKE_SWAY=false
declare -g MAKE_MANGO=false
declare -g MAKE_HYPRLAND=false
declare -g MAKE_FLUXBOX=false
declare -g MAKE_ONLY_XORG=false
declare -g MAKE_FULL_X=false
declare -g LBIND=false
declare -gi STEP_COUNT=59
declare -gi njobs=59
declare -g VOL_ID='VOIDBR_LIVE'
declare -g title
declare -g INITRAM_COMPRESSION=xz
declare -g SQUASHFS_COMPRESSION=zstd
#declare -g KEEP_BUILDDIR=true
declare -g name='base'
declare -g QUIET=false
declare -a INCLUDE_DIRS=()
declare -g REQUIRED_PKGS=
declare -g INITRAMFS_PKGS=
declare -g COMMON_PKGS=
declare -g AEXTRA_PKGS=
declare -g BASE_PKGS=

sh_choose_packages_base() {
	sh_choose_required_packages
	sh_choose_additional_packages
	sh_choose_voidbr_base_packages
}

sh_choose_required_packages() {
	print_step "Selecionando pacotes essenciais"
	REQUIRED_PKGS+=" base-files"
	REQUIRED_PKGS+=" voidbr-vinstall"
	REQUIRED_PKGS+=" coreutils"
	REQUIRED_PKGS+=" binutils"
	# REQUIRED_PKGS+=" dash"
	REQUIRED_PKGS+=" bash"
	REQUIRED_PKGS+=" syslinux"
	REQUIRED_PKGS+=" grub-i386-efi"
	REQUIRED_PKGS+=" grub-x86_64-efi"
	if [ "$BOOTLOADER" = "limine" ]; then
		REQUIRED_PKGS+=" limine"
	fi
	REQUIRED_PKGS+=" memtest86+"
	REQUIRED_PKGS+=" squashfs-tools"
	REQUIRED_PKGS+=" xorriso"
	REQUIRED_PKGS+=" plymouth"
	#
	INITRAMFS_PKGS+=" device-mapper"
	INITRAMFS_PKGS+=" dhclient"
	INITRAMFS_PKGS+=" dracut"
	INITRAMFS_PKGS+=" dracut-network"
	#
	#BASE_PKGS+=" voidbr-utils"
	#BASE_PKGS+=" voidbr-base-config"
	#
}

sh_choose_additional_packages() {
	ADDITIONAL_PKGS+=" voidbr-xbps"
	ADDITIONAL_PKGS+=" bash-completion"
	#	ADDITIONAL_PKGS+=" coreutils"
	ADDITIONAL_PKGS+=" sed"
	ADDITIONAL_PKGS+=" tar"
	ADDITIONAL_PKGS+=" gawk"
	ADDITIONAL_PKGS+=" NetworkManager iw"
	ADDITIONAL_PKGS+=" wireless_tools"
	ADDITIONAL_PKGS+=" wpa_supplicant"
	ADDITIONAL_PKGS+=" grc"
	ADDITIONAL_PKGS+=" ncurses"
	ADDITIONAL_PKGS+=" dialog"
	ADDITIONAL_PKGS+=" gettext"
	ADDITIONAL_PKGS+=" pv"
	ADDITIONAL_PKGS+=" curl"
	ADDITIONAL_PKGS+=" wget"
	#	ADDITIONAL_PKGS+=" git"
	ADDITIONAL_PKGS+=" nano"
	ADDITIONAL_PKGS+=" bc"
	ADDITIONAL_PKGS+=" parted"
	ADDITIONAL_PKGS+=" gptfdisk"
	ADDITIONAL_PKGS+=" e2fsprogs"
	ADDITIONAL_PKGS+=" lvm2"
	ADDITIONAL_PKGS+=" xfsprogs"
	ADDITIONAL_PKGS+=" jfsutils"
	ADDITIONAL_PKGS+=" btrfs-progs"
	ADDITIONAL_PKGS+=" f2fs-tools"
	ADDITIONAL_PKGS+=" nilfs-utils"
	ADDITIONAL_PKGS+=" ntfs-3g"
	ADDITIONAL_PKGS+=" xz"
	ADDITIONAL_PKGS+=" zstd"
	ADDITIONAL_PKGS+=" pigz"
	ADDITIONAL_PKGS+=" cryptsetup"
	ADDITIONAL_PKGS+=" socklog-void chrony"
	ADDITIONAL_PKGS+=" openssh"
	ADDITIONAL_PKGS+=" dhcpcd"
	ADDITIONAL_PKGS+=" htop"
	ADDITIONAL_PKGS+=" tree"
	ADDITIONAL_PKGS+=" rsync"
	#	ADDITIONAL_PKGS+=" tmate"
	ADDITIONAL_PKGS+=" duf"
	ADDITIONAL_PKGS+=" umc"
	ADDITIONAL_PKGS+=" fzf"
	ADDITIONAL_PKGS+=" eza"
	ADDITIONAL_PKGS+=" fastfetch"
	ADDITIONAL_PKGS+=" grub"
	ADDITIONAL_PKGS+=" grub-i386-efi"
	ADDITIONAL_PKGS+=" grub-x86_64-efi"
	ADDITIONAL_PKGS+=" limine"
	ADDITIONAL_PKGS+=" voidbr-limine-config"
	ADDITIONAL_PKGS+=" inxi"
	ADDITIONAL_PKGS+=" terminus-font"
	#
	ASKEL_PKGS+=(voidbr-base-config)
	ASKEL_PKGS+=(voidbr-nano-config)
}

sh_choose_voidbr_base_packages() {
	ADDITIONAL_PKGS+=" void-install"
	ADDITIONAL_PKGS+=" voidbr-vinstall"
	ADDITIONAL_PKGS+=" voidbr-grub-theme"
	ADDITIONAL_PKGS+=" voidbr-utils"
	ADDITIONAL_PKGS+=" chili-utils"
	ADDITIONAL_PKGS+=" chili-clonedisk"
	#
	ACONFIG_PKGS+=(voidbr-plymouth-theme)
}

sh_choose_voidbr_X_packages() {
	AEXTRA_COMMON_PKGS+=" voidbr-wallpapers"
	AEXTRA_COMMON_PKGS+=" voidbr-tokyo-theme"
	AEXTRA_COMMON_PKGS+=" voidbr-webapps"
	AEXTRA_COMMON_PKGS+=" chili-iso2usb"
	AEXTRA_COMMON_PKGS+=" voidbr-iso-writer"
}

##############################################################################
# Temas extras que só fazem sentido em DEs X11 tradicionais (XFCE, Plasma,
# GNOME, MATE, Cinnamon, Awesome, Enlightenment, Fluxbox, --xorg, --fullx).
# Hyprland/Mango/Sway NÃO chamam esta função — já usam o tema próprio que
# vem embutido no respectivo meta-pacote (voidbr-hyprland etc.).
##############################################################################
sh_choose_voidbr_x11_themes() {
	AEXTRA_COMMON_PKGS+=" voidbr-professional-theme"
	AEXTRA_COMMON_PKGS+=" voidbr-beauty-icons"
	AEXTRA_COMMON_PKGS+=" voidbr-dracula-theme"
}

##############################################################################
# Escolha do display manager, unificada num único lugar (antes estava
# metade em common_x11, metade em common_wayland — GNOME sempre usa gdm;
# Hyprland/Mango/Sway (Wayland puro) usam sddm; os demais DEs X11 (XFCE,
# Plasma, MATE, Cinnamon, Awesome, Enlightenment, Fluxbox) usam lightdm.
##############################################################################
sh_choose_packages_display_manager() {
	print_step "Selecionando display manager"
	if $MAKE_HYPRLAND || $MAKE_MANGO || $MAKE_SWAY || $MAKE_GNOME; then
		COMMON_PKGS+=" sddm"
		AEXTRA_COMMON_PKGS+=" voidbr-sddm-themes"
	else
		COMMON_PKGS+=" lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings"
		COMMON_PKGS+=" arc-theme"
		COMMON_PKGS+=" papirus-icon-theme"
		COMMON_PKGS+=" dejavu-fonts-ttf"
		AEXTRA_COMMON_PKGS+=" voidbr-lightdm-themes"
	fi
}

##############################################################################
# Pacotes comuns a QUALQUER ISO com ambiente gráfico, seja ela X11 ou
# Wayland puro (Hyprland/Mango/Sway). Nada aqui é específico de servidor
# gráfico — é a base de sessão (dbus/elogind/polkit), gerência de pastas
# XDG e suporte a imagens usado por qualquer toolkit gráfico.
##############################################################################
sh_choose_packages_common_gui_base() {
	print_step "Selecionando pacotes comuns de GUI (X11 + Wayland)"
	COMMON_PKGS+=" dbus-elogind elogind polkit-elogind"
	COMMON_PKGS+=" xdg-user-dirs xdg-user-dirs-gtk"
	COMMON_PKGS+=" libavif libheif gdk-pixbuf libheif-pixbuf-loader"
}

##############################################################################
# Pacotes exclusivos de ambientes que rodam sobre Xorg de verdade:
# XFCE, Plasma, GNOME, MATE, Cinnamon, Awesome, Enlightenment, Fluxbox e o
# modo --xorg/install (sessão X pura, sem DE). Hyprland, Mango e Sway NÃO
# chamam esta função (exceto no modo --fullx, que precisa das duas pilhas).
##############################################################################
sh_choose_packages_common_x11() {
	print_step "Selecionando pacotes X11 (Xorg)"
	COMMON_PKGS+=" xorg xorg-apps xorg-fonts xorg-server-xwayland"
	COMMON_PKGS+=" xauth xterm"
	COMMON_PKGS+=" dbus-x11"
	COMMON_PKGS+=" xfce4-terminal"
}

##############################################################################
# CÓDIGO MORTO — mantido só como referência, não é mais chamada por
# sh_configure_packages(). Hyprland/Sway/Mango já recebem isso via
# depends="voidbr-gui-common voidbr-wayland-common" do próprio meta-pacote.
##############################################################################
sh_choose_packages_common_wayland() {
	print_step "Selecionando pacotes Wayland (Hyprland/Mango/Sway)"
	COMMON_PKGS+=" xorg-server-xwayland xauth"
}

##############################################################################
# Pacotes "avançados" comuns: navegador, fontes, applet de rede, pilha de
# áudio, utilitários (gparted/octoxbps/arquivadores/gvfs). Não dependem de
# Xorg — servem tanto para sessões X11 quanto Wayland — por isso não têm
# mais "_X_" no nome. Pulado no modo --xorg/install (sessão mínima).
# OBS: função mantida só pro pipeline legado (GNOME/Cinnamon/MATE/Awesome/
# Enlightenment), que ainda não tem meta-pacote próprio. As outras 6 DEs
# (Hyprland/Sway/Mango/Fluxbox/Plasma/XFCE) já recebem isso via
# depends="voidbr-gui-common ..." do próprio meta-pacote.
##############################################################################
sh_choose_packages_common_advanced() {
	print_step "Selecionando pacotes Common Advanced"
	COMMON_PKGS+=" firefox firefox-i18n-pt-BR"
	COMMON_PKGS+=" terminus-font"
	COMMON_PKGS+=" noto-fonts-emoji"
	COMMON_PKGS+=" ttf-ubuntu-font-family"
	COMMON_PKGS+=" font-iosevka"
	COMMON_PKGS+=" nerd-fonts-symbols-ttf"
	COMMON_PKGS+=" ttf-jetbrains-mono-nerd"
	COMMON_PKGS+=" font-awesome"
	COMMON_PKGS+=" Adapta"
	COMMON_PKGS+=" adwaita-icon-theme"
	COMMON_PKGS+=" adwaita-plus"
	COMMON_PKGS+=" network-manager-applet"
	COMMON_PKGS+=" pulseaudio pavucontrol pasystray gst-plugins-bad1 gst-plugins-good1 gst-plugins-ugly1 gst-plugins-base1 alsa-plugins-pulseaudio alsa-utils"
	COMMON_PKGS+=" pipewire wireplumber alsa-pipewire pulseaudio-utils pavucontrol libspa-bluetooth libjack-pipewire alsa-plugins-pulseaudio alsa-utils"
	COMMON_PKGS+=" gparted"
	COMMON_PKGS+=" octoxbps"
	COMMON_PKGS+=" mate-calc"
	COMMON_PKGS+=" 7zip p7zip file-roller"
	COMMON_PKGS+=" gvfs gvfs-smb gvfs-cdda inetutils iputils"

	# COMMON_PKGS+=" avahi avahi-discover"
	#	COMMON_PKGS+=" brave-bin"
	# COMMON_PKGS+=" fonts-roboto-ttf"
	# COMMON_PKGS+=" liberation-fonts-ttf"
	# COMMON_PKGS+=" dejavu-fonts-ttf"
	# COMMON_PKGS+=" fonts-droid-ttf"
	# COMMON_PKGS+=" fonts-croscore-ttf"
	# COMMON_PKGS+=" font-emoji-one-color"
	# COMMON_PKGS+=" google-fonts-ttf"
	#	COMMON_PKGS+=" cool-retro-term"
	#	COMMON_PKGS+=" rxvt-unicode"
	#	COMMON_PKGS+=" blueberry"
	#	COMMON_PKGS+=" bluez"
	#	COMMON_PKGS+=" bluez-deprecated"
	#	COMMON_PKGS+=" bluez-alsa"
	#	COMMON_PKGS+=" bluedevil"
	#	COMMON_PKGS+=" blueman"
	#	COMMON_PKGS+=" bluez-cups"
	#	COMMON_PKGS+=" gnome-bluetooth1"
	#	COMMON_PKGS+=" orca"
	#	COMMON_PKGS+=" setxkbmap"
	#	COMMON_PKGS+=" numlockx"
	#	COMMON_PKGS+=" nitrogen"
	#	COMMON_PKGS+=" mate-notification-daemon"
	#	COMMON_PKGS+=" lxdm lxdm-theme-vdojo"
	# COMMON_PKGS+=" lxappearance lxinput lxrandr lxtask"
	# COMMON_PKGS+=" slim"
	# COMMON_PKGS+=" lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings"
	#	COMMON_PKGS+=" xarchiver zip unzip bzip2"
	#	COMMON_PKGS+=" libreoffice libreoffice-i18n-pt-BR"
	#	COMMON_PKGS+=" irqbalance"
	#	COMMON_PKGS+=" cups system-config-printer system-config-printer-udev splix"
	#	COMMON_PKGS+=" vlc"
	# COMMON_PKGS+=" celluloid"
	#	COMMON_PKGS+=" bat"
	# COMMON_PKGS+=" cmatrix"
	# COMMON_PKGS+=" xkill"
	# COMMON_PKGS+=" menulibre""
	# COMMON_PKGS+=" mugshot"
	# COMMON_PKGS+=" ocs-url"
	#	COMMON_PKGS+=" nvme-cli"
	#	COMMON_PKGS+=" remmina remmina-kwallet"
}

##############################################################################
# CÓDIGO MORTO daqui até sh_choose_packages_enlightenment (exclusive) —
# mantido só como referência. Plasma, XFCE e GNOME já têm meta-pacote
# próprio (voidbr-plasma, voidbr-xfce, voidbr-gnome).
##############################################################################
sh_choose_packages_plasma() {
	print_step "Selecionando pacotes KDE Plasma"
	ADDITIONAL_PKGS+=" kde5"
	ADDITIONAL_PKGS+=" konsole"
	ADDITIONAL_PKGS+=" kate"
	ADDITIONAL_PKGS+=" dolphin"
	#
	ASKEL_PKGS+=(voidbr-plasma-config)
}

sh_choose_packages_xfce_base() {
	print_step "Selecionando pacotes XFCE Base"
	ADISTRO_PKGS+=" xfce4"
	ADISTRO_PKGS+=" Thunar"
	ADISTRO_PKGS+=" xfce4-plugins"
	ADISTRO_PKGS+=" xfce4-screenshooter"
	ADISTRO_PKGS+=" xfce4-dict"
	ADISTRO_PKGS+=" xfce4-datetime-plugin"
}

sh_choose_packages_xfce() {
	print_step "Selecionando pacotes XFCE"
	ADISTRO_PKGS+=" thunar-archive-plugin"
	ADISTRO_PKGS+=" thunar-volman"
	ADISTRO_PKGS+=" plank"
	ADISTRO_PKGS+=" xfce4-pulseaudio-plugin"
	ADISTRO_PKGS+=" labwc"
	#	ADISTRO_PKGS+=" brother-brlaser"
	#	ADISTRO_PKGS+=" cups-pdf"

	AEXTRA_PKGS+=" voidbr-xfwm-axiom-theme"
	ACONFIG_PKGS+=(voidbr-dracula-theme)
	ASKEL_PKGS+=(voidbr-xfce-config)

}

sh_choose_packages_gnome() {
	print_step "Selecionando pacotes GNOME"
	ADISTRO_PKGS+=" gnome"
	ADISTRO_PKGS+=" gnome-keyring"
	ADISTRO_PKGS+=" accountsservice"
	ADISTRO_PKGS+=" voidbr-change-gnome-wallpaper"
	#
	ASKEL_PKGS+=(voidbr-gnome-config)
}

sh_choose_packages_awesome() {
	print_step "Selecionando pacotes Awesome"
	ADDITIONAL_PKGS+=" awesome"
	ADDITIONAL_PKGS+=" polybar"
	ADDITIONAL_PKGS+=" pcmanfm"
}

sh_choose_packages_enlightenment() {
	print_step "Selecionando pacotes Enlightenment"
	ADISTRO_PKGS+=" enlightenment"
	ADISTRO_PKGS+=" efl"
	ADISTRO_PKGS+=" rage"
	ADISTRO_PKGS+=" terminology"
	ADISTRO_PKGS+=" exquisite"
	ADISTRO_PKGS+=" connman"
	#
	ASKEL_PKGS+=(voidbr-enlightenment-config)
}

sh_choose_packages_cinnamon() {
	print_step "Selecionando pacotes CINNAMON"
	ADISTRO_PKGS+=" cinnamon-all"
	ADISTRO_PKGS+=" plank"
	ADISTRO_PKGS+=" playerctl"

	ASKEL_PKGS+=(voidbr-cinnamon-config)
}

sh_choose_packages_mate() {
	print_step "Selecionando pacotes MATE"
	#mate-extra está conflitando atril com libxreader do Cinnamon
	#atril também está orfão
	ADISTRO_PKGS+=" mate engrampa eom mate-applets mate-calc mate-indicator-applet mate-media mate-power-manager mate-sensors-applet mate-screensaver mate-system-monitor mate-terminal mate-utils mozo pluma caja-extensions yelp"
	ADISTRO_PKGS+=" xreader" # substitui atril
	ADISTRO_PKGS+=" plank"
	ADISTRO_PKGS+=" brisk-menu"
	ADISTRO_PKGS+=" mate-backgrounds"
	ADISTRO_PKGS+=" mate-common"

	AEXTRA_PKGS+=" mate-icon-theme-faenza mate-media"
	AEXTRA_PKGS+=" mate-netbook mate-power-manager mate-screensaver mate-sensors-applet mate-system-monitor mate-terminal"
	AEXTRA_PKGS+=" mate-utils caja-image-converter caja-open-terminal caja-sendto caja-share caja-wallpaper caja-xattr-tags"
	AEXTRA_PKGS+=" engrampa eom mozo pluma plank brisk-menu"

	ASKEL_PKGS+=(voidbr-mate-config)
}

##############################################################################
# CÓDIGO MORTO — mantido só como referência. Sway, Mango, Fluxbox e
# Hyprland já têm meta-pacote próprio (voidbr-sway, voidbr-mango,
# voidbr-fluxbox, voidbr-hyprland).
##############################################################################
sh_choose_packages_sway() {
	print_step "Selecionando pacotes SWAY"
	ADISTRO_PKGS+=" voidbr-sway"
	ASKEL_PKGS+=(voidbr-sway-config)
}

sh_choose_packages_mango() {
	print_step "Selecionando pacotes MANGO"
	ADISTRO_PKGS+=" voidbr-mango"
	ASKEL_PKGS+=(voidbr-mango-config)
	return
}

sh_choose_packages_fluxbox() {
	print_step "Selecionando pacotes FLUXBOX"
	ADISTRO_PKGS+=" voidbr-fluxbox"
	ASKEL_PKGS+=(voidbr-fluxbox-config)
}

sh_choose_packages_hyprland() {
	print_step "Selecionando pacotes HYPRLAND"
	ADISTRO_PKGS+=" voidbr-hyprland"
	ASKEL_PKGS+=(voidbr-hyprland-config)
}

sh_setEnvironment() {
	declare -g BOOTLOG="/tmp/void-mklive-$(sh_diahora).log"
	declare -g LOGGER='/dev/tty8'
	: "${COL_NC='\e[0m'}" # No Color
	: "${COL_LIGHT_GREEN='\e[1;32m'}"
	: "${COL_LIGHT_RED='\e[1;31m'}"
	: "${DONE="${COL_LIGHT_GREEN} done!${COL_NC}"}"
	: "${OVER="\\r\\033[K"}"
	: "${DOTPREFIX="  ${black}::${reset} "}"
	: "${clrkey=${light_white}}"
	: "${TICK="${clrkey}[${green}✓✓✓${clrkey}]${rst}"}"
	: "${CROSS="${clrkey}[${red}✗✗✗${clrkey}]${rst}"}"
	: "${MID="${clrkey}[${red}✗✗${green}✓${clrkey}]${rst}"}"
	: "${WARN="${clrkey}[${yellow}⚠  ${clrkey}]${yellow}"}"
	: "${INFO="${clrkey}[${yellow}➡  ${clrkey}]${rst}"}"

}

sh_setLanguage() {
	# Detecta o locale real do host (LC_ALL tem prioridade sobre LANG, como no
	# sistema de locale padrão) para decidir o idioma do prompt [S/n] vs [Y/n]
	# em readconf(). Não usamos $LANGUAGE aqui porque ela é forçada para
	# pt_BR logo no topo do script quando não definida, o que mascararia o
	# locale de verdade configurado no host.
	: "${LC_DEFAULT:=$([[ ${LC_ALL:-${LANG:-}} == pt_BR* ]] && echo 0 || echo 1)}"

	cmsg_ERRO=$(gettext "ERRO")
	cmsg_InstalacaoAbortada=$(gettext "Instalação abortada")
	cmsg_CommandNotFound=$(gettext "não encontrei o comando")
	cmsg_ImpossivelContinuar=$(gettext "IMPOSSÍVEL CONTINUAR")
	cmsg_ImpossivelContinuar1=$(gettext "Esse script precisa dos comandos listados acima")
	cmsg_ImpossivelContinuar2=$(gettext "Instale-os e/ou verifique se estão no seu")
	cmsg_InstCommand=$(gettext "Instalar o(s) comando(s)")
	cmsg_RunNew=$(gettext "INFO: Rode novamente o aplicativo")
	cmsg_RunNewErro=$(gettext "ERRO na instalação dos comandos. Tente manualmente")
}

sh_checkDependencies() {
	local d
	local errorFound=false
	declare -a missing

	for d in "${DEPENDENCIES[@]}"; do
		if [[ -z $(command -v "$d") ]]; then
			missing+=("$d")
			errorFound=true
			printf '%s\n' "${red}${cmsg_ERRO}${reset}: ${cmsg_CommandNotFound} ${cyan}'$d'${reset}"
		fi
	done
	if $errorFound; then
		echo "${yellow}--------------${cmsg_ImpossivelContinuar}-------------${reset}"
		echo "${cmsg_ImpossivelContinuar1}" >&2
		echo "${cmsg_ImpossivelContinuar2} \$PATH" >&2
		echo "${yellow}-----------------------------------------------${reset}"

		if [[ "$distro" = @(void|voidbr|void-live|voidlinux) ]]; then
			echo
			if readconf "${yellow}${cmsg_InstCommand} '${cyan}${missing[*]}${reset}' ?"; then
				if xbps-install -Sy "${missing[@]}" -R $XBPS_REPOSITORY; then
					errorFound=false
					sh_checkDependencies
				else
					die "${cmsg_RunNewErro}"
				fi
			fi
		else
			die "${cmsg_ERRO}: ${cmsg_InstalacaoAbortada}..."
		fi
	fi
}

sh_setVarColors() {
	reset=$(tput sgr0)
	rst=$(tput sgr0)
	# Definir os estilos de texto como variáveis
	bold=$(tput bold)
	underline=$(tput smul)   # Início do sublinhado
	nounderline=$(tput rmul) # Fim do sublinhado
	reverse=$(tput rev)      # Inverte as cores de fundo e texto
	# Definir as cores ANSI como variáveis
	black=$(tput bold)$(tput setaf 0)
	red=$(tput bold)$(tput setaf 196)
	green=$(tput bold)$(tput setaf 2)
	yellow=$(tput bold)$(tput setaf 3)
	blue=$(tput setaf 4)
	pink=$(tput setaf 5)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	gray=$(tput setaf 8)
	orange=$(tput setaf 202)
	purple=$(tput setaf 125)
	violet=$(tput setaf 61)
	light_red=$(tput setaf 9)
	light_green=$(tput setaf 10)
	light_yellow=$(tput setaf 11)
	light_blue=$(tput setaf 12)
	light_magenta=$(tput setaf 13)
	light_cyan=$(tput setaf 14)
	bright_white=$(tput setaf 15)
}

mount_pseudofs() {
	! $LBIND || return 0
	for f in proc sys dev; do
		local target="$ROOTFS/$f"
		print_step "Montando pseudo FS: $target"
		mkdir -p "$target"
		mount --rbind "/$f" "$target"
		# ESSENCIAL: evita propagação de desmontagem para o host
		mount --make-rslave "$target"
	done
	LBIND=true
}

umount_pseudofs() {
	$LBIND || return 0
	for f in dev proc sys; do
		local target="$ROOTFS/$f"
		mountpoint -q "$target" || continue
		print_step "Desmontando pseudo FS: $target"
		umount -R "$target" 2>/dev/null || umount -l "$target"
	done
	LBIND=false
}

error_out() {
	trap - INT TERM 0
	umount_pseudofs || exit "${1:-0}"
	#	[ -d "$BUILDDIR" ] && [ -z "$KEEP_BUILDDIR" ] && rm -rf --one-file-system "$BUILDDIR"
	exit "${1:-0}"
}

copy_dracut_files() {
	mkdir -p "$1"/usr/lib/dracut/modules.d/01vmklive
	cp dracut/vmklive/* "$1"/usr/lib/dracut/modules.d/01vmklive/
	# autologin none
	if $MAKE_FULL_X; then
		touch "$1"/usr/lib/dracut/modules.d/01vmklive/noautologin
	fi
}

copy_autoinstaller_files() {
	mkdir -p "$1"/usr/lib/dracut/modules.d/01autoinstaller
	cp dracut/autoinstaller/* "$1"/usr/lib/dracut/modules.d/01autoinstaller/
}

install_packages() {
	#	cmd_logger "Instalando pacote voidbr-xbps" '
	#    cmd_install -yu voidbr-xbps
	#  '

	mount_pseudofs

	# Todos os grupos "normais" (sem necessidade de --force) instalados em uma
	# UNICA transacao xbps-install, em vez de uma chamada separada por grupo.
	# Cada chamada de xbps-install reprocessa repodata e recalcula a arvore de
	# dependencias do zero -- unificar evita esse retrabalho repetido.
	local ALL_NORMAL_PKGS="$PACKAGE_LIST $INITRAMFS_PKGS $ADDITIONAL_PKGS $COMMON_PKGS $ADISTRO_PKGS $AEXTRA_COMMON_PKGS ${ACONFIG_PKGS[*]} $AEXTRA_PKGS"
	cmd_logger "Instalando pacotes (grupo unificado: PACKAGE_LIST+INITRAMFS_PKGS+ADDITIONAL_PKGS+COMMON_PKGS+ADISTRO_PKGS+AEXTRA_COMMON_PKGS+ACONFIG_PKGS+AEXTRA_PKGS) -> $ROOTFS" '
    cmd_install $ALL_NORMAL_PKGS
  '
	replicate '-'

	# ASKEL_PKGS continua em transacao SEPARADA de propósito: são pacotes de
	# config que precisam de --force --force (sobrescrevem arquivos que
	# conflitam com pacotes já instalados). Antes eram N chamadas (uma por
	# pacote); agora é 1 chamada só, com todos de uma vez.
	if [[ -n "${ASKEL_PKGS[*]}" ]]; then
		cmd_logger "Instalando pacotes ASKEL_PKGS (forçado, grupo unificado) -> $ROOTFS" '
      cmd_install_force "${ASKEL_PKGS[*]}"
    '
		replicate '-'
	fi
	#    sh_reconfigure_pass1

}

ignore_packages() {
	mkdir -p "$ROOTFS"/etc/xbps.d
	for pkg in $IGNORE_PKGS; do
		echo "ignorepkg=$pkg" >>"$ROOTFS"/etc/xbps.d/mkiso-ignore.conf
	done
}

install_skel_root() {
	cmd_logger "Copiando skel para usuario root" '
	  cp -Rpva $ROOTFS/etc/skel/.bash* $ROOTFS/root/ || true
		cp -Rpva $ROOTFS/etc/skel/.git-prompt.sh $ROOTFS/root/ || true
		cp -Rpva $ROOTFS/etc/skel/.dialogrc $ROOTFS/root/ || true
		cp -Rpva $ROOTFS/etc/skel/.dircolors $ROOTFS/root/ || true
		cp -Rpva $ROOTFS/etc/skel/.ps* $ROOTFS/root/ || true
    #rsync -a $ROOTFS/etc/skel/.config/neofetch/config.conf $ROOTFS/root/.config/neofetch/ || true
  '
}

sh_configure_void_install_desktop() {
	cmd_logger "Configurando /usr/share/xsessions/void-install.desktop" '
    mkdir -p "$ROOTFS/usr/share/xsessions"

    cat > "$ROOTFS/usr/share/xsessions/void-install.desktop" << "EOF"
[Desktop Entry]
Name=VoidBR Install
Comment=Executa o instalador VoidBR Linux
#Exec=xterm -fa "Monospace" -fs 11 -geometry 162x50 -e sudo bash void-install
#Exec=xfce4-terminal --font="Monospace" --geometry=162x50 --hide-menubar --hide-toolbar --disable-server -x sudo bash /usr/bin/void-install
Exec=void-install-launcher
Type=Application
DesktopNames=VoidInstall
EOF

    chmod 644 "$ROOTFS/usr/share/xsessions/void-install.desktop"
  '
}

sh_reconfigure_pass1() {
	cmd_logger "Reconfigurando o ambiente - pass 1" '
		xbps-reconfigure -r "$ROOTFS" -f base-files >/dev/null 2>&1
		chroot "$ROOTFS" env -i PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" xbps-reconfigure -f base-files

		# Enable choosen UTF-8 locale and generate it into the target rootfs.
		if [ -f "$ROOTFS"/etc/default/libc-locales ]; then
			sed -e "s/\#\(${LOCALE}.*\)/\1/g" -i "$ROOTFS"/etc/default/libc-locales
		fi
	'
}

sh_reconfigure_pass2() {
	cmd_logger "Reconfigurando o ambiente - pass 2" '
    chroot "$ROOTFS" env -i PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" MKISO_BUILD=1 xbps-reconfigure -a
	'
}

finish_clean() {
	local rootfs="${ROOTFS:?ROOTFS não definido}"
	# Cleanup and remove useless stuff.
	xbps-remove -r "$rootfs" -Ooy >/dev/null 2>&1
	rm -rf "$rootfs"/var/cache/* "$rootfs"/run/* "$rootfs"/var/run/*
}

copy_include_directories() {
	for includedir in "${INCLUDE_DIRS[@]}"; do
		info_msg "=> copying include directory '$includedir' ..."
		find "$includedir" -mindepth 1 -maxdepth 1 -exec cp -rfpPv {} "$ROOTFS"/ \;
	done
}

configure_plymouth() {
	print_step "Configurando plymouth : $ROOTFS/etc/dracut.conf.d/plymouth.conf"
	mkdir -p "$ROOTFS/etc/dracut.conf.d"
	echo 'add_dracutmodules+=" plymouth "' >"$ROOTFS/etc/dracut.conf.d/plymouth.conf"
	print_step "Configurando tema plymouth : voidbr"
	#chroot "$ROOTFS" env -i plymouth-set-default-theme fade-in
	#chroot "$ROOTFS" env -i plymouth-set-default-theme voidx
	chroot "$ROOTFS" env -i PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" plymouth-set-default-theme voidbr
	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Falha ao configurar tema"

	print_step "Criando wrapper plymouth : $ROOTFS/usr/bin/plymouth-show-log-voidlinux.sh"
	mkdir -p "$ROOTFS/usr/bin"
	cat <<'EOF' >"$ROOTFS/usr/bin/plymouth-show-log-voidlinux.sh"
#!/usr/bin/env bash

file=/var/log/boot.log
# Exibe uma mensagem inicial usando o Plymouth
plymouth display-message --text="Booting Void Linux"
dmesg -f daemon,user,auth | while read -r line; do
  # Exibe as últimas 50 caracteres da linha usando o Plymouth
  plymouth display-message --text="${line:0:50}"
  echo "${line:0:50}"
  sleep 0.2
  if ! plymouth --ping; then
    echo "Plymouth morreu, saindo..."
    break
  fi
done
# Exibe uma mensagem de encerramento caso o Plymouth morra
plymouth display-message --text="Initialization completed"
EOF

	# Torna o script executável
	chmod +x "$ROOTFS/usr/bin/plymouth-show-log-voidlinux.sh"
	file="$ROOTFS/etc/runit/1"
	grep -q plymouth-show-log-voidlinux "$file" || sed -i '/^#!/a\
[ -r /usr/bin/plymouth-show-log-voidlinux.sh ] && . /usr/bin/plymouth-show-log-voidlinux.sh
    ' "$file"

}

configure_service_boot_logger() {
	print_step "Configurando serviço boot-logger : $ROOTFS/etc/sv/"
	mkdir -p "$ROOTFS/etc/sv/boot-logger"
	tee "$ROOTFS/etc/sv/boot-logger/run" >/dev/null <<'EOF'
#!/bin/sh
LOG_FILE="/var/log/boot.log"
# garante diretório
mkdir -p /var/log
# evita sobrescrever sempre (append)
exec dmesg -w >> "$LOG_FILE" 2>&1
EOF
	chmod +x "$ROOTFS/etc/sv/boot-logger/run"
	# link simbólico no runit
	ln -sf "/etc/sv/boot-logger" "$ROOTFS/etc/runit/runsvdir/default/"
}

configure_service_plymouth_log() {
	print_step "Configurando serviço plymouth-log : $ROOTFS/etc/sv/"
	mkdir -p "$ROOTFS/etc/sv/plymouth-log"
	tee "$ROOTFS/etc/sv/plymouth-log/run" >/dev/null <<EOF
#!/bin/sh
[ -r ./conf ] && . ./conf
exec /usr/bin/plymouth-show-log-voidlinux.sh
EOF
	chmod +x "$ROOTFS/etc/sv/plymouth-log/run"
	ln -sf "/etc/sv/plymouth-log" "$ROOTFS/etc/runit/runsvdir/default/"
}

configure_service_plymouth_stop() {
	print_step "Configurando serviço plymouth-stop : $ROOTFS/etc/sv"
	mkdir -p "$ROOTFS/etc/sv/plymouth-stop"
  tee "$ROOTFS/etc/sv/plymouth-stop/run" >/dev/null <<'EOF'
#!/bin/sh
[ -r ./conf ] && . ./conf
/usr/bin/plymouth --quit
# "plymouth --quit" às vezes retorna antes do daemon (plymouthd) ter
# terminado de verdade -- e ao morrer, ele reseta a fonte/console,
# sobrescrevendo qualquer coisa que a gente aplique logo em seguida.
# Espera o processo sumir de fato antes de mexer na fonte.
for i in $(seq 1 20); do
    pgrep -x plymouthd >/dev/null 2>&1 || break
    sleep 0.1
done
# O plymouth, ao sair do modo gráfico, costuma resetar a fonte do
# console pro padrão embutido do kernel -- reaplica a fonte configurada
# no rc.conf (ex: terminus via vconsole.font=/locale.sh) depois dele.
. /etc/rc.conf 2>/dev/null
[ -n "$FONT" ] && setfont "$FONT" 2>/dev/null
exit 0
EOF
	chmod +x "$ROOTFS/etc/sv/plymouth-stop/run"
	ln -sf "/etc/sv/plymouth-stop" "$ROOTFS/etc/runit/runsvdir/default/"
}

configure_etc_runit_core_services_quit_plymouth() {
	print_step "Configurando script plymouth-stop : $ROOTFS/etc/runit/core-services/"
	tee "$ROOTFS/etc/runit/core-services/99-voidbr-plymouth-quit.sh" >/dev/null <<'EOF'
#!/bin/sh
if command -v plymouth >/dev/null; then
    plymouth quit
    # "plymouth quit" às vezes retorna antes do daemon (plymouthd) ter
    # terminado de verdade -- e ao morrer, ele reseta a fonte/console,
    # sobrescrevendo qualquer coisa que a gente aplique logo em seguida.
    # Espera o processo sumir de fato antes de mexer na fonte.
    for i in $(seq 1 20); do
        pgrep -x plymouthd >/dev/null 2>&1 || break
        sleep 0.1
    done
fi
# O plymouth, ao sair do modo gráfico, costuma resetar a fonte do
# console pro padrão embutido do kernel -- reaplica a fonte configurada
# no rc.conf (ex: terminus via vconsole.font=/locale.sh) depois dele.
. /etc/rc.conf 2>/dev/null
[ -n "$FONT" ] && setfont "$FONT" 2>/dev/null
EOF
	chmod +x "$ROOTFS/etc/runit/core-services/99-voidbr-plymouth-quit.sh"
}

sh_global_audio_cleaning() {
	local root="${ROOTFS:?ROOTFS não definido}"
	local file

	print_step "Ajustando Pipewire (sound global)"

	# Autostarts globais e do usuário
	for file in \
		pipewire.desktop \
		pipewire-pulse.desktop \
		wireplumber.desktop \
		pulseaudio.desktop \
		pulseaudio-kde.desktop; do
		rm -f \
			"$root/etc/xdg/autostart/$file" \
			"$root/etc/skel/.config/autostart/$file"
	done

	# Configurações globais do ALSA
	rm -f \
		"$root/etc/alsa/conf.d/50-pipewire.conf" \
		"$root/etc/alsa/conf.d/99-pipewire-default.conf" \
		"$root/etc/alsa/conf.d/50-pulseaudio.conf" \
		"$root/etc/asound.conf"

	# Configurações de áudio do usuário
	rm -rf \
		"$root/etc/skel/.config/pipewire" \
		"$root/etc/skel/.config/wireplumber" \
		"$root/etc/skel/.config/pulse" \
		"$root/etc/skel/.config/alsa"
}

sh_activating_pipewire() {
	sh_global_audio_cleaning
	print_step "Ajustando Pipewire (user autostart)"

	# DESATIVAR AUTOSPAWN DO PULSEAUDIO (usuário)
	# impede PulseAudio iniciar automaticamente
	mkdir -p ${ROOTFS}/etc/skel/.config/pulse
	mkdir -p ${ROOTFS}/etc/skel/.config/autostart
	mkdir -p ${ROOTFS}/etc/skel/.config/pipewire/pipewire.conf.d
	mkdir -p ${ROOTFS}/etc/alsa/conf.d

	cat >"${ROOTFS}/etc/skel/.config/pulse/client.conf" <<'EOF'
autospawn = no
daemon-binary = /bin/true
EOF

	#AUTOSTART CORRETO (SÓ USUÁRIO)
	chroot ${ROOTFS} ln -sf /usr/share/applications/pipewire.desktop /etc/skel/.config/autostart/pipewire.desktop
	chroot ${ROOTFS} ln -sf /usr/share/examples/wireplumber/10-wireplumber.conf /etc/skel/.config/pipewire/pipewire.conf.d/10-wireplumber.conf
	chroot ${ROOTFS} ln -sf /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/skel/.config/pipewire/pipewire.conf.d/20-pipewire-pulse.conf

	# ---- integração ALSA → PipeWire ----
	chroot ${ROOTFS} ln -sf /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d/50-pipewire.conf
	chroot ${ROOTFS} ln -sf /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/99-pipewire-default.conf
}

sh_configure_lightdm_default_session() {
	local cpath=${ROOTFS}/var/lib/lightdm/.cache/lightdm-gtk-greeter

	print_step "Ajustando sessao default no lightdm (user e session)"
	mkdir -p ${cpath}

	cat >"${cpath}/state" <<EOF
[greeter]
last-user=anon
last-session=$name
EOF
}

generate_initramfs() {
	local _args

	# Garantia de segurança: verifica se KERNELVERSION está definida e se o diretório de módulos existe no ROOTFS
	if [ -z "$KERNELVERSION" ] || [ ! -d "$ROOTFS/lib/modules/$KERNELVERSION" ]; then
		# Tenta autodetectar a versão real instalada no chroot para não quebrar o script
		local detected_kver=$(ls "$ROOTFS/lib/modules" | head -n1)
		if [ -n "$detected_kver" ]; then
			KERNELVERSION="$detected_kver"
		else
			die "Erro: Kernel não foi encontrado instalado em $ROOTFS/lib/modules!"
		fi
	fi

	print_step "Gerando imagem initramfs (${INITRAMFS_COMPRESSION}) : ${yellow}${BOOT_DIR}/initrd"

	copy_dracut_files "$ROOTFS"
	copy_autoinstaller_files "$ROOTFS"

	# NOTA: o comando abaixo mantém o log via tee, mas a checagem de $result e o
	# die ficam FORA do pipe -- um 'die' dentro de um bloco à esquerda de um
	# pipe roda em subshell e NÃO interrompe o script principal.
	chroot "$ROOTFS" env PYTHONWARNINGS="ignore::SyntaxWarning" \
		/usr/bin/dracut \
		-N \
		--"${INITRAMFS_COMPRESSION}" \
		--add-drivers "ahci" \
		--force-add "vmklive autoinstaller" \
		--omit systemd "/boot/initrd" \
		$KERNELVERSION 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER

	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Failed to generate the initramfs"

	if [ ! -f "$ROOTFS/boot/initrd" ]; then
		die "Erro crítico: O arquivo $ROOTFS/boot/initrd não foi gerado pelo dracut!"
	fi

	mv "$ROOTFS"/boot/initrd "$BOOT_DIR"
	cp "$ROOTFS"/boot/vmlinuz-$KERNELVERSION "$BOOT_DIR"/vmlinuz
	cp -Rpva "$ROOTFS"/boot/grub/themes "$BOOT_DIR/grub/"
}

cleanup_rootfs() {
	print_step "Limpando rootfs : $ROOTFS"
	for f in ${INITRAMFS_PKGS}; do
		revdeps=$(xbps-query -r "$ROOTFS" -X $f)
		if [ -n "$revdeps" ]; then
			xbps-pkgdb -r "$ROOTFS" -m auto $f
		else
			xbps-remove -r "$ROOTFS" -Ry ${f} >/dev/null 2>&1
		fi
	done
	rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01vmklive
	rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01autoinstaller
}

generate_isolinux_boot() {
	print_step "Gerando suporte isolinux para sistema : PC-BIOS"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/isolinux.bin "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/ldlinux.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/libcom32.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/vesamenu.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/libutil.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/chain.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/reboot.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f "$SYSLINUX_DATADIR"/poweroff.c32 "$ISOLINUX_DIR"
	run_cmd_new cp -f isolinux/isolinux.cfg.in "$ISOLINUX_DIR"/isolinux.cfg
	run_cmd_new cp -f ${SPLASH_IMAGE} "$ISOLINUX_DIR"

	run_cmd_new sed -i -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
		-e "s|@@KERNVER@@|${KERNELVERSION}|" \
		-e "s|@@KEYMAP@@|${KEYMAP}|" \
		-e "s|@@ARCH@@|$BASE_ARCH|" \
		-e "s|@@LOCALE@@|${LOCALE}|" \
		-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
		-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
		"$ISOLINUX_DIR"/isolinux.cfg

	# include memtest86+
	#run_cmd_new cp -f "$HOSTDIR"/boot/memtest.bin "$BOOT_DIR"
	run_cmd_new cp -f "$HOSTDIR"/boot/memtest86+/memtest.bin "$BOOT_DIR"
}

generate_limine_boot() {
	print_step "Gerando suporte Limine para sistema : BIOS + UEFI"
	{
		run_cmd_new cp -f limine/limine.conf.in "$LIMINE_DIR"/limine.conf
		run_cmd_new sed -i -e "s|@@KERNVER@@|${KERNELVERSION}|" \
			-e "s|@@KEYMAP@@|${KEYMAP}|" \
			-e "s|@@ARCH@@|$BASE_ARCH|" \
			-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
			-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
			-e "s|@@LOCALE@@|${LOCALE}|" "$LIMINE_DIR"/limine.conf

		# Wallpaper do tema (referenciado no limine.conf via
		# "boot():/boot/limine/voidbr-tokyonight.png"). O pacote
		# voidbr-limine-config já instala esse arquivo no ROOTFS, em
		# /boot/efi/limine/ (pensado pro sistema instalado) -- aqui só
		# copiamos ele de lá pro lugar novo, dentro da própria ISO.
		if [ -f "$ROOTFS/boot/efi/limine/voidbr-tokyonight.png" ]; then
			run_cmd_new cp -f "$ROOTFS/boot/efi/limine/voidbr-tokyonight.png" "$LIMINE_DIR"/
		else
			info_msg "AVISO: $ROOTFS/boot/efi/limine/voidbr-tokyonight.png não encontrado (voidbr-limine-config instalado?) -- Limine vai usar fundo padrão."
		fi

		# Binários do bootloader em si (ambos os modos, BIOS e UEFI, num
		# único conjunto de arquivos -- Limine não separa isolinux/grub).
		run_cmd_new cp -f "$LIMINE_DATADIR"/limine-bios.sys "$LIMINE_DIR"
		run_cmd_new cp -f "$LIMINE_DATADIR"/limine-bios-cd.bin "$LIMINE_DIR"
		run_cmd_new cp -f "$LIMINE_DATADIR"/limine-uefi-cd.bin "$LIMINE_DIR"

		# EFI/BOOT/ pra permitir boot direto de pendrive/HD gravado cru
		# (fora do El Torito, útil se a mídia for regravada como disco raw).
		run_cmd_new mkdir -p "$IMAGEDIR"/EFI/BOOT
		run_cmd_new cp -f "$LIMINE_DATADIR"/BOOTX64.EFI "$IMAGEDIR"/EFI/BOOT/
		run_cmd_new cp -f "$LIMINE_DATADIR"/BOOTIA32.EFI "$IMAGEDIR"/EFI/BOOT/

		# include memtest86+ (multiboot1, referenciado no limine.conf)
		run_cmd_new cp -f "$HOSTDIR"/boot/memtest86+/memtest.bin "$BOOT_DIR"
	}
}

generate_grub_efi_boot() {
	print_step "Gerando suporte GRUB para sistema : EFI"
	{
		run_cmd_new cp -f grub/grub.cfg "$GRUB_DIR"
		run_cmd_new cp -f grub/grub_void.cfg.in "$GRUB_DIR"/grub_void.cfg
		run_cmd_new sed -i -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
			-e "s|@@KERNVER@@|${KERNELVERSION}|" \
			-e "s|@@KEYMAP@@|${KEYMAP}|" \
			-e "s|@@ARCH@@|$BASE_ARCH|" \
			-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
			-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
			-e "s|@@LOCALE@@|${LOCALE}|" "$GRUB_DIR"/grub_void.cfg
		run_cmd_new mkdir -p "$GRUB_DIR"/fonts
		run_cmd_new cp -f "$GRUB_DATADIR"/unicode.pf2 "$GRUB_DIR"/fonts

		run_cmd_new modprobe -q loop || :

		# Create EFI vfat image.
		run_cmd_new truncate -s 32M "$GRUB_DIR"/efiboot.img
		run_cmd_new mkfs.vfat -F12 -S 512 -n "GRUB_UEFI" "$GRUB_DIR/efiboot.img"

		GRUB_EFI_TMPDIR="$(mktemp --tmpdir="$HOME" -d)"
		LOOP_DEVICE="$(losetup --show --find "${GRUB_DIR}"/efiboot.img)"
		run_cmd_new mount -o rw,flush -t vfat "${LOOP_DEVICE}" "${GRUB_EFI_TMPDIR}"

		run_cmd_new cp -a "$IMAGEDIR"/boot "$HOSTDIR"

		# Os dois grub-mkstandalone abaixo (i386-efi e x86_64-efi) sao
		# independentes entre si (saidas e diretorios de origem diferentes),
		# entao rodam em paralelo para ganhar tempo, em vez de sequencialmente.
		msg "${cyan}[⚙  ]${rst} grub-mkstandalone i386-efi + x86_64-efi (em paralelo)"
		if $QUIET; then
			xbps-uchroot "$HOSTDIR" grub-mkstandalone -- \
				--directory="/usr/lib/grub/i386-efi" \
				--format="i386-efi" \
				--output="/tmp/bootia32.efi" \
				"boot/grub/grub.cfg" &>/dev/null &
		else
			xbps-uchroot "$HOSTDIR" grub-mkstandalone -- \
				--directory="/usr/lib/grub/i386-efi" \
				--format="i386-efi" \
				--output="/tmp/bootia32.efi" \
				"boot/grub/grub.cfg" &
		fi
		pid_i386=$!

		if $QUIET; then
			xbps-uchroot "$HOSTDIR" grub-mkstandalone -- \
				--directory="/usr/lib/grub/x86_64-efi" \
				--format="x86_64-efi" \
				--output="/tmp/bootx64.efi" \
				"boot/grub/grub.cfg" &>/dev/null &
		else
			xbps-uchroot "$HOSTDIR" grub-mkstandalone -- \
				--directory="/usr/lib/grub/x86_64-efi" \
				--format="x86_64-efi" \
				--output="/tmp/bootx64.efi" \
				"boot/grub/grub.cfg" &
		fi
		pid_x86_64=$!

		wait "$pid_i386"
		result_i386=$?
		wait "$pid_x86_64"
		result_x86_64=$?

		if [ "$result_i386" -ne 0 ] || [ "$result_x86_64" -ne 0 ]; then
			run_cmd_new umount "$GRUB_EFI_TMPDIR"
			run_cmd_new losetup --detach "${LOOP_DEVICE}"
			die "Failed to generate EFI loader"
		fi

		run_cmd_new mkdir -p "${GRUB_EFI_TMPDIR}"/EFI/BOOT
		run_cmd_new cp -f "$HOSTDIR"/tmp/bootia32.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTIA32.EFI
		run_cmd_new cp -f "$HOSTDIR"/tmp/bootx64.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTX64.EFI
		run_cmd_new umount "$GRUB_EFI_TMPDIR"
		run_cmd_new losetup --detach "${LOOP_DEVICE}"
		run_cmd_new rm -rf "$GRUB_EFI_TMPDIR"

		# include memtest86+
		run_cmd_new cp -f "$HOSTDIR"/boot/memtest86+/memtest.efi "$BOOT_DIR"
	}
	#	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

get_compression_options() {
	local param
	case $1 in
	gzip) param=" -noappend -comp gzip -Xcompression-level 1" ;;
	xz) param=" -noappend -b 1048576 -comp xz -Xdict-size 100%" ;;
	zstd) param=" -noappend -b 1M -comp zstd -Xcompression-level 3" ;;
	lzma) param=" -noappend -b 1M -comp lzma" ;;
	lz4) param=" -noappend -b 1M -comp lz4 -Xhc" ;;
	bzip2) param=" -noappend -b 1M -comp bzip2" ;;
	lzo) param=" -noappend -b 1M -comp lzo" ;;
	*) die "Tipo de compressão squashfs desconhecido: '$1' (use lz4|gzip|bzip2|xz|zstd|lzma|lzo)" ;;
	esac
	echo "$param"
}

generate_squashfs() {
	local options=$(get_compression_options "$SQUASHFS_COMPRESSION")

	umount_pseudofs
	print_step "Gerando image squashfs ($SQUASHFS_COMPRESSION) de rootfs: ${yellow}$IMAGEDIR/LiveOS/squashfs.img"
	{
		ROOTFS_SIZE=$(du --apparent-size -sm "$ROOTFS" | awk '{print $1}')
		run_cmd_new mkdir -p "$BUILDDIR/tmp/LiveOS"
		# Folga reduzida de 2x para ~1.15x + margem fixa de 256M (a imagem antiga
		# usava o dobro do tamanho do rootfs sem necessidade real).
		EXT3_IMG_SIZE=$(((ROOTFS_SIZE * 115 / 100) + 256))
		run_cmd_new truncate -s "${EXT3_IMG_SIZE}M" "$BUILDDIR"/tmp/LiveOS/rootfs.img
		# mke2fs -d popula o filesystem DIRETO a partir do ROOTFS, sem precisar
		# montar via loop + cp -a + umount (evita uma copia inteira do rootfs
		# passando por I/O de mount de loop device). Journal desabilitado
		# (^has_journal) porque essa imagem só existe para ser lida uma vez
		# pelo mksquashfs logo em seguida e depois é apagada -- journaling é
		# overhead puro aqui.
		run_cmd_new mkfs.ext3 -F -q -O ^has_journal -d "$ROOTFS" -m1 "$BUILDDIR/tmp/LiveOS/rootfs.img" 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		run_cmd_new mkdir -p "$IMAGEDIR/LiveOS"

		run_cmd_new "$HOSTDIR"/usr/bin/mksquashfs "$BUILDDIR"/tmp "$IMAGEDIR"/LiveOS/squashfs.img -noappend -b 1M -comp zstd -Xcompression-level 1 -processors "$(nproc)" || die "Failed to generate squashfs image"

		run_cmd_new chmod 444 "$IMAGEDIR/LiveOS/squashfs.img"
		#[ -z "$KEEP_BUILDDIR" ] && rm -rf "$ROOTFS"
		run_cmd_new rm -rf "$BUILDDIR/tmp"
	}
	#	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

generate_iso_image() {
	print_step "Gerando imagem ISO : ${yellow}$OUTPUT_FILE"
	{
		if [ "$BOOTLOADER" = "limine" ]; then
			run_cmd_new "$HOSTDIR"/usr/bin/xorriso \
				-as mkisofs \
				-iso-level 3 \
				-rock \
				-joliet \
				-max-iso9660-filenames \
				-omit-period \
				-omit-version-number \
				-relaxed-filenames \
				-allow-lowercase \
				-volid "$VOL_ID" \
				-b boot/limine/limine-bios-cd.bin \
				-no-emul-boot -boot-load-size 4 -boot-info-table \
				--efi-boot boot/limine/limine-uefi-cd.bin \
				-efi-boot-part --efi-boot-image --protective-msdos-label \
				-output "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"

			# Grava o stage BIOS/MBR direto no arquivo da ISO -- necessário
			# pro boot funcionar de verdade quando a ISO for regravada crua
			# num pendrive (dd/Rufus/etc), não só em CD/DVD virtual.
			run_cmd_new "$HOSTDIR"/usr/bin/limine bios-install "$OUTPUT_FILE" || die "Failed to install Limine BIOS stage"
		else
			run_cmd_new "$HOSTDIR"/usr/bin/xorriso \
				-as mkisofs \
				-iso-level 3 \
				-rock \
				-joliet \
				-max-iso9660-filenames \
				-omit-period \
				-omit-version-number \
				-relaxed-filenames \
				-allow-lowercase \
				-volid "$VOL_ID" \
				-eltorito-boot boot/isolinux/isolinux.bin \
				-eltorito-catalog boot/isolinux/boot.cat \
				-no-emul-boot \
				-boot-load-size 4 -boot-info-table \
				-eltorito-alt-boot -e boot/grub/efiboot.img \
				-isohybrid-gpt-basdat \
				-no-emul-boot \
				-isohybrid-mbr "$SYSLINUX_DATADIR"/isohdpfx.bin \
				-output "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"
		fi
	}
	#	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	hsize=$(du -sh "$OUTPUT_FILE" | awk '{print $1}')
	chili-make-md5-iso "$OUTPUT_FILE"
	rm kernel-${name}.txt
	info_msg "Iso file created: ${green}$(readlink -f "$OUTPUT_FILE") ($hsize) successfully.${reset}"
}

usage() {
	sh_setVarColors
	cat <<EOF
${bold}Usage:${rst} $PROGNAME [options]

${green}Generates a basic live ISO image of Void Linux.${rst}
This ISO image can be written to a CD/DVD-ROM or any USB stick.
To generate a more complete live ISO image, use build-x86-images.sh.${rst}

${bold}OPTIONS${rst}
  -a <arch>          ${cyan}Set XBPS_ARCH in the ISO image${rst}
  -b <system-pkg>    ${cyan}Set an alternative base package${rst} (default: base-system)
  -r <repo>          ${cyan}Use this XBPS repository${rst} (can be used multiple times)
  -c <cachedir>      ${cyan}XBPS cache directory${rst} (default: ./xbps-cachedir-<arch>)
  -D <dir>           ${cyan}Build root directory${rst} (default: /lfs/voidbr, sobrescrevível também via \$ROOTDIR)
  -k <keymap>        ${cyan}Default keymap${rst} (default: us)
  -l <locale>        ${cyan}Default locale${rst} (default: en_US.UTF-8)

  -i <type>          ${cyan}Initramfs compression${rst} (lz4|gzip|bzip2|xz|zstd|lzma|lzo)
  -s <type>          ${cyan}Squashfs compression${rst} (lz4|gzip|bzip2|xz|zstd|lzma|lzo)

  -o <file>          ${cyan}Output ISO filename${rst}
  -p "<pkg> ..."     ${cyan}Additional packages${rst}
  -g "<pkg> ..."     ${cyan}Ignore packages${rst}
  -I <dir>           ${cyan}Include directory into ROOTFS${rst}

  -Z "<service> ..." ${cyan}Enable services${rst}
  -C "<arg> ..."     ${cyan}Extra kernel cmdline args${rst}
  -T <title>         ${cyan}Bootloader title${rst} (default: Void Linux)
  -v linux<ver>      ${cyan}Custom kernel version${rst}
  --bootloader=<x>    ${cyan}Bootloader${rst} (grub|limine, default: grub)

  -K                 ${yellow}Do not remove builddir${rst}
  -n                 ${yellow}Reuse existing squashfs${rst}
  -Q                 ${yellow}Quiet mode${rst}

${bold}Desktop presets:${rst}
  -W|awesome        ${green}AWESOME${rst}
  -N|cinnamon       ${green}CINNAMON${rst}
  -E|enlightenment  ${green}ENLIGHTENMENT${rst}
  -F|fluxbox        ${green}FLUXBOX${rst}
  -G|gnome          ${green}GNOME${rst}
  -P|plasma|kde     ${green}KDE PLASMA${rst}
  -L|plasma-louvorja-piano     ${green}PLASMA LOUVORJA-PIANO${rst}
  -X|xfce-base      ${green}XFCE (base)${rst}
  -Y|xfce           ${green}XFCE${rst}
  -M|mate           ${green}MATE${rst}
  -S|sway           ${green}SWAY${rst}
  -O|mango          ${green}MANGO${rst}
  -H|hyprland       ${green}HYPRLAND${rst}
  -A|fullx          ${green}ALL X${rst}

  -h                 Show this help and exit
  -V                 Show version and exit
EOF
}

sh_config_distroname() {
	declare -ga name
	if $MAKE_FULL_X; then
		title='VoidBR Linux Live Full X'
		VOL_ID='VOIDBR_LIVE_FULLX'
		name='fullx'
	elif $MAKE_ENLIGHTENMENT; then
		title='VoidBR Linux Live Enlightenment'
		VOL_ID='VOIDBR_LIVE_ENLIGHTENMENT'
		name='enlightenment'
	elif $MAKE_AWESOME; then
		title='VoidBR Linux Live Awesome'
		VOL_ID='VOIDBR_LIVE_AWESOME'
		name='awesome'
	elif $MAKE_FLUXBOX; then
		title='VoidBR Linux Live Fluxbox'
		VOL_ID='VOIDBR_LIVE_FLUXBOX'
		name='fluxbox'
	elif $MAKE_PLASMA; then
		title='VoidBR Linux Live KDE Plasma'
		VOL_ID='VOIDBR_LIVE_PLASMA'
		name='plasma'
	elif $MAKE_PLASMA_LOUVORJA_PIANO; then
		title='VoidBR Linux Live Plasma with LouvorJa-Piano'
		VOL_ID='VOIDBR_LIVE_LOUVORJA'
		name='louvorja-piano'
	elif $MAKE_GNOME; then
		title='VoidBR Linux Live GNOME'
		VOL_ID='VOIDBR_LIVE_GNOME'
		name='gnome'
	elif $MAKE_XFCE_BASE; then
		title='VoidBR Linux Live Xfce Base'
		VOL_ID='VOIDBR_LIVE_XFCE_BASE'
		name='xfce-base'
	elif $MAKE_XFCE; then
		title='VoidBR Linux Live XFCE'
		VOL_ID='VOIDBR_LIVE_XFCE'
		name='xfce'
	elif $MAKE_CINNAMON; then
		title='VoidBR Linux Live Cinnamon'
		VOL_ID='VOIDBR_LIVE_CINNAMON'
		name='cinnamon'
	elif $MAKE_MATE; then
		title='VoidBR Linux Live Mate'
		VOL_ID='VOIDBR_LIVE_MATE'
		name='mate'
	elif $MAKE_SWAY; then
		title='VoidBR Linux Live Sway'
		VOL_ID='VOIDBR_LIVE_SWAY'
		name='sway'
	elif $MAKE_MANGO; then
		title='VoidBR Linux Live Mango'
		VOL_ID='VOIDBR_LIVE_MANGO'
		name='mango'
	elif $MAKE_HYPRLAND; then
		title='VoidBR Linux Live Hyprland'
		VOL_ID='VOIDBR_LIVE_HYPRLAND'
		name='hyprland'
	elif $MAKE_ONLY_XORG; then
		title='VoidBR Linux Live Install'
		VOL_ID='VOIDBR_LIVE_INSTALL'
		name='install'
	else
		title='VoidBR Linux Live Base'
		VOL_ID='VOIDBR_LIVE_BASE'
		name='base'
	fi
	print_step "Configurando distroname : $name"
}

sh_print_resume() {
	replicate
	for mirror in "${public_repos[@]}"; do
		print_step "Repository ${cyan}#$((++count))${rst}    => ${yellow}${mirror}${reset}"
	done
	replicate
	print_step "Building ISO     => ${yellow}${title}${reset}"
	print_step "Versao app       => ${yellow}${APP} v${_VERSION_}${reset}"
	print_step "Profile         => ${yellow}${name}${reset}"
	print_step "Bootloader      => ${yellow}${BOOTLOADER}${reset}"
	print_step "ROOTDIR         => ${yellow}${ROOTDIR}${reset}"
	print_step "ROOTFS          => ${yellow}${ROOTFS}${reset}"
	print_step "HOSTDIR         => ${yellow}${HOSTDIR}${reset}"
	print_step "ARCH            => ${yellow}${ARCH}${reset}"
	print_step "Output file ISO => ${yellow}${OUTPUT_FILE}${reset}"
	print_step "Compression SFS => ${yellow}${SQUASHFS_COMPRESSION}${reset}"
	print_step "Compression RAM => ${yellow}${INITRAM_COMPRESSION}${reset}"
	print_step "ISO LABEL       => ${yellow}${VOL_ID}${reset}"
	replicate
}

sh_configure_packages() {
	#	sh_config_distroname

	sh_choose_packages_base

	if $MAKE_X; then
		##########################################################################
		# Hyprland, Sway, Mango, Fluxbox, Plasma e XFCE já têm meta-pacote próprio
		# (voidbr-<de>), que já declara depends="voidbr-gui-common voidbr-xorg-common"
		# ou depends="voidbr-gui-common voidbr-wayland-common" — e voidbr-gui-common
		# por sua vez depende de voidbr-base-common. O xbps-install resolve essa
		# cadeia inteira sozinho a partir de UM nome só; não precisa mais listar
		# pacote solto nem chamar as funções common_* pra essas 6 DEs.
		##########################################################################
		if $MAKE_FULL_X; then
			# Imagem "tudo em um": inclui todo mundo.
			STEP_COUNT=72
			ADISTRO_PKGS+=" voidbr-xfce voidbr-plasma voidbr-fluxbox voidbr-sway voidbr-mango voidbr-hyprland voidbr-gnome"

			# Cinnamon, MATE, Awesome e Enlightenment ainda não têm
			# meta-pacote — usa a seleção manual (legado) até serem criados.
			sh_choose_packages_common_gui_base
			sh_choose_packages_common_x11
			sh_choose_voidbr_x11_themes
			sh_choose_packages_display_manager
			sh_choose_packages_common_advanced
			sh_choose_packages_cinnamon
			sh_choose_packages_mate
			sh_choose_packages_awesome
			sh_choose_packages_enlightenment
		elif $MAKE_HYPRLAND; then
			ADISTRO_PKGS+=" voidbr-hyprland"
		elif $MAKE_SWAY; then
			ADISTRO_PKGS+=" voidbr-sway"
		elif $MAKE_MANGO; then
			ADISTRO_PKGS+=" voidbr-mango"
		elif $MAKE_FLUXBOX; then
			ADISTRO_PKGS+=" voidbr-fluxbox"
		elif $MAKE_XFCE_BASE || $MAKE_XFCE; then
			ADISTRO_PKGS+=" voidbr-xfce"
		elif $MAKE_GNOME; then
			ADISTRO_PKGS+=" voidbr-gnome"
		elif $MAKE_PLASMA; then
			ADISTRO_PKGS+=" voidbr-plasma"
		elif $MAKE_PLASMA_LOUVORJA_PIANO; then
			ADISTRO_PKGS+=" voidbr-plasma"
      ASKEL_PKGS+=(voidbr-plasma-config-louvorja-piano)
		elif $MAKE_ONLY_XORG; then
			# Sessão X mínima, sem DE (--xorg/install): só a base Xorg
			# + infra comum, sem nenhum meta-pacote de DE.
			ADISTRO_PKGS+=" voidbr-base-common voidbr-xorg-common"
		else
			##########################################################################
			# Cinnamon, MATE, Awesome, Enlightenment: ainda sem meta-pacote
			# próprio, mantém o pipeline antigo (legado) até serem criados.
			##########################################################################
			sh_choose_packages_common_gui_base
			sh_choose_packages_common_x11
			sh_choose_voidbr_x11_themes
			sh_choose_packages_display_manager
			sh_choose_packages_common_advanced
			if $MAKE_ENLIGHTENMENT; then
				sh_choose_packages_enlightenment
			elif $MAKE_AWESOME; then
				sh_choose_packages_awesome
			elif $MAKE_CINNAMON; then
				sh_choose_packages_cinnamon
			elif $MAKE_MATE; then
				sh_choose_packages_mate
			fi
		fi
	fi
}

sh_configure_rootfs() {
	# Configure dracut to use overlayfs for the writable overlay.
	print_step "Configurando rootfs : $ROOTFS"
	BOOT_CMDLINE="$BOOT_CMDLINE rd.overlay=1 "
	ARCH=$(xbps-uhelper arch)

	# Set defaults
	: ${BASE_ARCH:=$(xbps-uhelper arch 2>/dev/null || uname -m)}
	: ${XBPS_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${BASE_ARCH}}
	: ${XBPS_HOST_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${ARCH}}
	: ${KEYMAP:=br-abnt2}
	: ${LOCALE:=pt_BR.UTF-8}
	: ${INITRAMFS_COMPRESSION:=xz}
	: ${SQUASHFS_COMPRESSION:=zstd}
	: ${BASE_SYSTEM_PKG:=base-container-full}
	# : ${BASE_SYSTEM_PKG:=base-system}
	: ${BOOT_TITLE:="$title"}

	# Required packages in the image for a working system.
	PACKAGE_LIST="$BASE_SYSTEM_PKG $PACKAGE_LIST"

	#mount -o remount,size=18G,mode=1777 tmpfs /tmp
	#ROOTDIR='/tmp'
	#mount -o remount,size=18G,mode=1777 tmpfs /dev/shm
	#ROOTDIR='/dev/shm'
	#mount /dev/nvme0n1p2 /mnt/voidlinux
	#ROOTDIR='/mnt/voidlinux/@/lixo'
	: "${ROOTDIR:=/lfs/voidbr}"

	if [ -n "$ROOTDIR" ]; then
		BUILDDIR="$ROOTDIR/$name"
		#		[ -d "$BUILDDIR" ] && [ -z "$KEEP_BUILDDIR" ] && rm -rf --one-file-system "$BUILDDIR"
		mkdir -p "$BUILDDIR"
	else
		BUILDDIR=$(mktemp --tmpdir="$(pwd -P)" -d)
	fi

	BUILDDIR=$(readlink -f "$BUILDDIR")
	IMAGEDIR="$BUILDDIR/image"
	ROOTFS="$BUILDDIR/rootfs"
	HOSTDIR="$ROOTDIR/hostdir"
	BOOT_DIR="$IMAGEDIR/boot"
	ISOLINUX_DIR="$BOOT_DIR/isolinux"
	GRUB_DIR="$BOOT_DIR/grub"
	LIMINE_DIR="$BOOT_DIR/limine"
	ISOLINUX_CFG="$ISOLINUX_DIR/isolinux.cfg"

	sh_create_etc_xbps_d_conf_00_repository_main_conf "$ROOTFS/etc/xbps.d/00-repository-main.conf"

	[ "${#INCLUDE_DIRS[@]}" -gt 0 ] && STEP_COUNT=$((STEP_COUNT + 1))
	[ -n "${IGNORE_PKGS}" ] && STEP_COUNT=$((STEP_COUNT + 1))

	: ${SYSLINUX_DATADIR:="$HOSTDIR"/usr/lib/syslinux}
	: ${GRUB_DATADIR:="$HOSTDIR"/usr/share/grub}
	: ${LIMINE_DATADIR:="$HOSTDIR"/usr/share/limine}
	: ${SPLASH_IMAGE:=data/splash.png}
	: ${XBPS_INSTALL_UNPACK_ONLY:=xbps-install --unpack-only --yes --ignore-file-conflicts}
	: ${XBPS_INSTALL_CMD:=xbps-install}
	: ${VINSTALL_CMD:=vinstall}
	: ${XBPS_REMOVE_CMD:=xbps-remove}
	: ${XBPS_QUERY_CMD:=xbps-query}
	: ${XBPS_RINDEX_CMD:=xbps-rindex}
	: ${XBPS_UHELPER_CMD:=xbps-uhelper}
	: ${XBPS_RECONFIGURE_CMD:=xbps-reconfigure}
	: ${OUTPUT_FILE="voidbr-live-$name-${BASE_ARCH}-$(uname -r)-$(sh_diahora).iso"}
	mkdir -p "$ROOTFS" "$HOSTDIR" "$ISOLINUX_DIR" "$GRUB_DIR" "$LIMINE_DIR"

	# Validação de espaço em disco inserida antes do resumo e do início das instalações
	verificar_espaco_livre

	sh_print_resume

}

sh_configure_linux() {
	#	print_step "Configurando kernel"
	# Get linux version for ISO - If linux version option specified use
	if [ -n "$LINUX_VERSION" ]; then
		if ! echo "$LINUX_VERSION" | grep "linux[0-9._]\+"; then
			die "-v option must be in format linux<version>"
		fi
		_linux_series="$LINUX_VERSION"
		PACKAGE_LIST="$PACKAGE_LIST $LINUX_VERSION"
	else # Otherwise find latest stable version from linux meta-package
		_linux_series=$(
			XBPS_ARCH=$BASE_ARCH $XBPS_QUERY_CMD \
				--rootdir "$ROOTFS" ${XBPS_REPOSITORY:=-R} \
				--deps linux |
				grep 'linux[0-9._]\+'
		)
	fi

	_kver=$(
		XBPS_ARCH=$BASE_ARCH $XBPS_QUERY_CMD \
			--rootdir "$ROOTFS" ${XBPS_REPOSITORY:=-R} \
			--property pkgver ${_linux_series}
	)
	KERNELVERSION=$(
		$XBPS_UHELPER_CMD getpkgversion ${_kver}
	)
	if [ "$?" -ne "0" ]; then
		die "Failed to find kernel package version"
	fi
	OUTPUT_FILE="voidbr-live-$name-${BASE_ARCH}-${KERNELVERSION}-$(sh_diahora).iso"
	{
		echo "KERNELVERSION=$KERNELVERSION"
		echo "OUTPUT_FILE=$OUTPUT_FILE"
	} >kernel-${name}.txt

	print_step "Kernel Version: $KERNELVERSION"

}

install_prereqs() {
	#        --unpack-only \
	cmd_logger "Instalando pacote: voidbr-xbps" "
    LC_ALL=C \
      XBPS_ARCH=$ARCH "$XBPS_INSTALL_CMD" \
        --rootdir "$HOSTDIR" ${XBPS_REPOSITORY} \
        --cachedir "$XBPS_HOST_CACHEDIR" \
        --update \
        --ignore-file-conflicts \
        --sync \
        --yes \
        voidbr-xbps
  "

	cmd_logger "Instalando grupo de pacotes : REQUIRED_PKGS -> $HOSTDIR" "
    LC_ALL=C \
      XBPS_ARCH=$ARCH "$XBPS_INSTALL_CMD" \
        --rootdir "$HOSTDIR" ${XBPS_REPOSITORY} \
        --cachedir "$XBPS_HOST_CACHEDIR" \
        --update \
        --ignore-file-conflicts \
        --sync \
        --yes \
        $REQUIRED_PKGS
  "
	replicate '-'

	cmd_logger "Instalando grupo de pacotes : BASE_PKGS -> $HOSTDIR" "
    LC_ALL=C \
      XBPS_ARCH=$ARCH "$XBPS_INSTALL_CMD" \
        --rootdir "$HOSTDIR" ${XBPS_REPOSITORY} \
        --cachedir "$XBPS_HOST_CACHEDIR" \
        --update \
        --ignore-file-conflicts \
        --sync \
        --yes \
        $BASE_PKGS
  "
	replicate '-'
}

sh_install_rootfs() {
	replicate

	copy_void_keys "$ROOTFS"
	copy_void_keys "$HOSTDIR"
	install_prereqs

	cmd_logger "Sincronizando dados do repositório : $ROOTFS" "
		LC_ALL=C XBPS_ARCH=$BASE_ARCH $XBPS_INSTALL_CMD \
		  -Syu \
		  -r "$ROOTFS" \
		  -R ${XBPS_REPOSITORY}

  "
	cmd_logger "Sincronizando dados do repositório : $HOSTDIR" "
		LC_ALL=C XBPS_ARCH=$ARCH $XBPS_INSTALL_CMD \
		  -Syu \
		  -r "$HOSTDIR" \
		  -R ${XBPS_REPOSITORY}
  "
	replicate '-'

	sh_configure_linux

	#	: ${OUTPUT_FILE="voidbr-live-$name-${BASE_ARCH}-${KERNELVERSION}-$(sh_diahora).iso"}
	#  install_prereqs

	mkdir -p "$ROOTFS"/etc
	[ -s data/motd ] && cp data/motd "$ROOTFS"/etc
	[ -s data/issue ] && cp data/issue "$ROOTFS"/etc

	if [ -n "$IGNORE_PKGS" ]; then
		print_step "Ignoring packages in the rootfs: ${IGNORE_PKGS} ..."
		ignore_packages
	fi

	print_step "Instalando pacotes void em : $ROOTFS"
	install_packages
	install_skel_root
	sh_configure_void_install_desktop
	sh_reconfigure_pass2
	finish_clean
}

enable_services() {
	local SERVICE_LIST="$*"
	local service link

	for service in $SERVICE_LIST; do
		link="$ROOTFS/etc/runit/runsvdir/default/$service"
		print_step "Ativando serviço: $service"

		#		if [[ -L "$link" ]] &&
		#			[[ "$(readlink "$link")" == "/etc/sv/$service" ]]; then
		#			info_msg "service $service já está habilitado"
		#			continue
		#		fi

		if [[ ! -d "$ROOTFS/etc/sv/$service" ]]; then
			info_msg "service $service not found in $ROOTFS/etc/sv"
			continue
		fi

		run_cmd_new ln -snf "/etc/sv/$service" "$link"
		if [[ ! -L "$link" && ! -e "$link" ]] &&
			[[ ! "$(readlink "$link")" == "/etc/sv/$service" ]]; then
			info_msg "failed to enable service $service (broken symlink)"
		fi
	done
}

sh_make_iso() {
	mount_pseudofs

	#dica: No Void, com dbus ativo, o elogind e o polkitd sobem automaticamente.
	#      Você não precisa ativar os serviços deles no runit.
	: ${DEFAULT_SERVICE_LIST:=agetty-tty1 agetty-tty2 agetty-tty3 agetty-tty4 agetty-tty5 agetty-tty6 dbus socklog-unix nanoklogd udevd sshd NetworkManager dhcpcd chronyd}
	if $MAKE_X; then
		if $MAKE_HYPRLAND || $MAKE_MANGO || $MAKE_SWAY || $MAKE_GNOME; then
			: ${ADDITIONAL_SERVICE_LIST:=sddm}
		else
			: ${ADDITIONAL_SERVICE_LIST:=lightdm}
		fi
	fi

	if $MAKE_ENLIGHTENMENT; then
		: ${EXTRA_SERVICE_LIST:=acpid connmand}
	fi

	replicate '-'
	enable_services ${DEFAULT_SERVICE_LIST} ${SERVICE_LIST} ${ADDITIONAL_SERVICE_LIST} ${EXTRA_SERVICE_LIST}
	replicate '-'

	if [ "${#INCLUDE_DIRS[@]}" -gt 0 ]; then
		print_step "Copying directory structures into the rootfs ..."
		copy_include_directories
	fi

	# Dispara o void-install sozinho, mas SOMENTE quando a entrada
	# "Instalar" do menu de boot foi escolhida (identificada pelo
	# parâmetro exclusivo voidbr.autoinstall no cmdline — não usar
	# live.autologin sozinho aqui, pois a entrada de acessibilidade
	# (linuxa11y) também usa live.autologin e NÃO deve abrir o instalador).
	# Qualquer outra entrada de boot (linux, linuxram, linuxa11y, sessão
	# gráfica normal) continua se comportando exatamente como antes.
	print_step "Configurando autoexec do void-install (tty1) : $ROOTFS/etc/skel/.bash_profile"
	mkdir -p "$ROOTFS/etc/skel"
	cat >"$ROOTFS/etc/skel/.bash_profile" <<-'EOF'
		    #
		    # ~/.bash_profile
		    #

		    [[ -f ~/.bashrc ]] && . ~/.bashrc

				# Instalado pelo mkiso — dispara o void-install SOMENTE quando o
				# boot veio da entrada "Instalar" do menu (isolinux/GRUB), marcada
				# pelo parâmetro voidbr.autoinstall no cmdline do kernel. Qualquer
				# outra entrada de boot cai num shell normal, como sempre foi.
				if [ "$(tty)" = "/dev/tty1" ] && grep -qw 'voidbr.autoinstall' /proc/cmdline; then
					sudo /usr/bin/void-install
					echo
					echo "Instalador encerrado. Você está num shell bash normal agora."
					echo "Para rodar o instalador de novo: sudo void-install"
				fi
	EOF
	chmod 644 "$ROOTFS/etc/skel/.bash_profile"

	for file in ./grub/grub_void.cfg.in ./isolinux/isolinux.cfg.in ./limine/limine.conf.in; do
		print_step "Ajustando CDLABEL=$VOL_ID : ${file}"
		sudo sed -i "s/CDLABEL=[^ ]*/CDLABEL=${VOL_ID}/g" "$file"
	done

	#	configure_plymouth
	#configure_service_boot_logger
	#configure_service_plymouth_log
	#configure_service_plymouth_stop
	configure_etc_runit_core_services_quit_plymouth
	generate_initramfs
	if [ "$BOOTLOADER" = "limine" ]; then
		generate_limine_boot
	else
		generate_isolinux_boot
		generate_grub_efi_boot
	fi
	cleanup_rootfs
	local conf="$ROOTFS/etc/xbps.d/00-repository-main.conf"
	sh_remove_etc_xbps_00_repository_main_conf "$conf"
	sh_activating_pipewire
	if $MAKE_X && ! $MAKE_GNOME && ! $MAKE_HYPRLAND && ! $MAKE_MANGO && ! $MAKE_SWAY; then
		sh_configure_lightdm_default_session
	fi

  sh_set_edition_os_release() {
    local name="$1"
    name="${name^}"
    sed -i "s/^EDITION=.*/EDITION=\"$name\"/" "$ROOTFS"/etc/os-release
  }
  sh_set_edition_os_release "$name"

	# generate_squashfs
	#	generate_iso_image
}

sh_remove_etc_xbps_00_repository_main_conf() {
	local conf="$1"
	cmd_logger "Removendo arquivo: $conf" '
   	rm -f -- "$conf" >/dev/null 2>&1
 	'
}

for arg in "$@"; do
	case "$arg" in
	-h | --help)
		usage
		exit 0
		;;
	--version)
		sh_version
		exit 0
		;;
	esac
done

# main()
#
sh_setVarColors
sh_setEnvironment
sh_setLanguage
sh_checkDependencies

while getopts "a:b:r:c:C:T:Kk:l:i:I:s:o:p:g:v:VhXxYyQqWwNnEeFfAGOHPmMSZ:D:" opt; do
	case $opt in
	a) BASE_ARCH="$OPTARG" ;;
	D) ROOTDIR="$OPTARG" ;;
	b) BASE_SYSTEM_PKG="$OPTARG" ;;
	r) EXTRA_REPOSITORY="--repository=$OPTARG $EXTRA_REPOSITORY" ;;
	c) XBPS_CACHEDIR="$OPTARG" ;;
	g) IGNORE_PKGS="$IGNORE_PKGS $OPTARG" ;;
	K) KEEP_BUILDDIR=1 ;;
	k) KEYMAP="$OPTARG" ;;
	l) LOCALE="$OPTARG" ;;
	I) INCLUDE_DIRS+=("$OPTARG") ;;
	i) INITRAMFS_COMPRESSION="$OPTARG" ;;
	s) SQUASHFS_COMPRESSION="$OPTARG" ;;
	Z) SERVICE_LIST="$SERVICE_LIST $OPTARG" ;;
	o) OUTPUT_FILE="$OPTARG" ;;
	p) PACKAGE_LIST="$PACKAGE_LIST $OPTARG" ;;
	C) BOOT_CMDLINE="$OPTARG" ;;
	T) BOOT_TITLE="$OPTARG" ;;
	x | X)
		MAKE_X=true
		MAKE_XFCE_BASE=true
		;;
	y | Y)
		MAKE_X=true
		MAKE_XFCE=true
		;;
	n | N)
		MAKE_X=true
		MAKE_CINNAMON=true
		;;
	m | M)
		MAKE_X=true
		MAKE_MATE=true
		;;
	S)
		MAKE_X=true
		MAKE_SWAY=true
		;;
	O)
		MAKE_X=true
		MAKE_MANGO=true
		;;
	H)
		MAKE_X=true
		MAKE_HYPRLAND=true
		;;
	w | W)
		MAKE_X=true
		MAKE_AWESOME=true
		;;
	e | E)
		MAKE_X=true
		MAKE_ENLIGHTENMENT=true
		;;
	f | F)
		MAKE_X=true
		MAKE_FLUXBOX=true
		;;
	G)
		MAKE_X=true
		MAKE_GNOME=true
		;;
	P)
		MAKE_X=true
		MAKE_PLASMA=true
		;;
	L)
		MAKE_X=true
		MAKE_PLASMA_LOUVORJA_PIANO=true
		;;
	A)
		MAKE_X=true
		MAKE_FULL_X=true
		;;
	q | Q) QUIET=true ;;
	v) LINUX_VERSION="$OPTARG" ;;
	V)
		sh_version
		exit 0
		;;
	h)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

for arg in "$@"; do
	case "${arg,,}" in
	xorg | install)
		MAKE_X=true
		MAKE_ONLY_XORG=true
		;;
	fluxbox)
		MAKE_X=true
		MAKE_FLUXBOX=true
		;;

	xfce)
		MAKE_X=true
		MAKE_XFCE=true
		;;

	xfce-base)
		MAKE_X=true
		MAKE_XFCE_BASE=true
		;;

	plasma | kde)
		MAKE_X=true
		MAKE_PLASMA=true
		;;
	plasma-louvorja-piano)
		MAKE_X=true
		MAKE_PLASMA_LOUVORJA_PIANO=true
		;;

	gnome)
		MAKE_X=true
		MAKE_GNOME=true
		;;

	mate)
		MAKE_X=true
		MAKE_MATE=true
		;;

	sway)
		MAKE_X=true
		MAKE_SWAY=true
		;;

	mango)
		MAKE_X=true
		MAKE_MANGO=true
		;;

	hyprland)
		MAKE_X=true
		MAKE_HYPRLAND=true
		;;

	cinnamon)
		MAKE_X=true
		MAKE_CINNAMON=true
		;;

	awesome)
		MAKE_X=true
		MAKE_AWESOME=true
		;;

	enlightenment)
		MAKE_X=true
		MAKE_ENLIGHTENMENT=true
		;;

	fullx)
		MAKE_X=true
		MAKE_FULL_X=true
		;;
	*)
		MAKE_X=false
		MAKE_FULL_X=false
		;;
	esac
done

# Check for root permissions.
if [ "$(id -u)" -ne 0 ]; then
	die "Must be run as root, exiting..."
fi

# Seleção de mirrors: chamada explicitamente aqui (não mais automática ao dar
# source em lib.sh), para não disparar em opções rápidas como -h/-V, e para
# não sobrescrever o que -r já tiver definido em EXTRA_REPOSITORY.
select_mirrors_dialog
XBPS_REPOSITORY="$EXTRA_REPOSITORY $XBPS_REPOSITORY"

sh_config_distroname
sh_configure_rootfs
LBIND=true
umount_pseudofs
sh_configure_packages
sh_install_rootfs
sh_make_iso
generate_squashfs
generate_iso_image
umount_pseudofs
exit 0
