#!/usr/bin/env bash
#
# vim: set ts=4 sw=4 et:
#
#-
# Copyright (c) 2009-2015 Juan Romero Pardines.
# Copyright (c) 2023-2024 Vilmar Catafesta <vcatafesta@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#-
#xbps-install -U -r /tmp/fakeroot --repository=https://repo-fastly.voidlinux.org/current bash -S

#export LANGUAGE=pt_BR
export TERM=${TERM:-xterm}
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=void-install
# flag languages
declare -gA Alanguage=([pt_BR]=0 [en_US]=1 [de_DE]=2 [fr_FR]=3 [es_ES]=4 [it_IT]=5)
declare -gA Alocale=([0]=pt_BR [1]=en_US [2]=de_DE [3]=fr_FR [4]=es_ES [5]=it_IT)

# Armazenar os aliases atuais em uma variável
OLD_ALIASES=$(alias)

# Armazenar os aliases atuais em uma variável
OLD_ALIASES=$(alias)

# Desativar todos os aliases
unalias -a

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
#set -x
#set -e
shopt -s extglob

#system
readonly APP="${0##*/}"
readonly _VERSION_='1.0.28-20240228'
readonly distro=$(uname -n)
readonly DEPENDENCIES=(rsync sed cat cp umount losetup grep chroot mkfs.vfat tee)

# Restaurar os aliases quando o script terminar
trap "eval \"$OLD_ALIASES\"" EXIT
trap 'error_out $? $LINENO' INT TERM 0

umask 022
declare -gi MAKE_X=false
declare -gi MAKE_XFCE_BASE=false
declare -gi MAKE_XFCE_CUSTOM=false
declare -gi MAKE_AWESOME=false
declare -gi MAKE_ENLIGHTENMENT=false
declare -gi MAKE_FLUXBOX=false
declare -gi MAKE_KDE=false
declare -gi MAKE_GNOME=false
declare -gi MAKE_FULL_X=false
#declare -gi KEEP_BUILDDIR=false
declare -gi LBIND=false
declare -gi QUIET=false
declare -gi STEP_COUNT=72
declare -g VOL_ID='VOID_LIVE'
declare -g title
declare -g name
declare -g SQUASHFS_COMPRESSION=xz
declare -g INITRAM_COMPRESSION=xz

sh_choose_packages_base() {
	print_step "Selecionando pacotes essenciais"
	declare -a INCLUDE_DIRS=()
	declare -g PROGNAME=$(basename "$0")
	declare -g REQUIRED_PKGS="base-files libgcc dash coreutils sed tar gawk syslinux grub-i386-efi grub-x86_64-efi memtest86+ squashfs-tools xorriso"
	declare -g INITRAMFS_PKGS="binutils device-mapper dhclient dracut-network openresolv"
	declare -g ADDITIONAL_PKGS="dialog gettext curl wget git pv nano parted"
	ADDITIONAL_PKGS+=" btop htop"
	ADDITIONAL_PKGS+=" tree rsync lynx parallel tmate gpm evtest acpi acpid"
	ADDITIONAL_PKGS+=" xz zstd cryptsetup lvm2 wireless_tools wpa_supplicant socklog-void openntpd"
	ADDITIONAL_PKGS+=" bc geoip geoipupdate iputils"
	ADDITIONAL_PKGS+=" xtools vpm vsv neofetch pfetch"
	ADDITIONAL_PKGS+=" bash-completion"
	ADDITIONAL_PKGS+=" grub-btrfs-runit"
	ADDITIONAL_PKGS+=" duf"
	ADDITIONAL_PKGS+=" dfc"
	ADDITIONAL_PKGS+=" cifs-utils ntfs-3g"
	ADDITIONAL_PKGS+=" bubblewrap"
	#--repository=https://chililinux.com/void/current
	#ADDITIONAL_PKGS+=" chili-grub-void-theme"
	ADDITIONAL_PKGS+=" grub-void-theme"
	ADDITIONAL_PKGS+=" nano-syntax-highlighting"
	ADDITIONAL_PKGS+=" blueberry"
	ADDITIONAL_PKGS+=" porg"
	#   ADDITIONAL_PKGS+=" wifi-firmware"
	#   ADDITIONAL_PKGS+=" rtl8812au-dkms rtl8821cu-dkms rtl8822bu-dkms"
	#	#pacman
	ADDITIONAL_PKGS+=" pacman fakeroot bsdtar"
}

sh_choose_packages_common_X() {
	print_step "Selecionando pacotes X Common"
	#xorg
	ADDITIONAL_PKGS+=" xorg xinit xterm dbus dbus-x11 dbus-elogind polkit-elogind xdg-user-dirs xrdb"
	#file manager
	ADDITIONAL_PKGS+=" Thunar"
	#browser
	ADDITIONAL_PKGS+=" firefox firefox-i18n-pt-BR"
	#fonts
	ADDITIONAL_PKGS+=" noto-fonts-emoji ttf-ubuntu-font-family font-iosevka nerd-fonts-symbols-ttf"
	#themes
	ADDITIONAL_PKGS+=" Adapta"
	#network
	ADDITIONAL_PKGS+=" NetworkManager network-manager-applet"
	#terminal
	ADDITIONAL_PKGS+=" xfce4-terminal"
	ADDITIONAL_PKGS+=" cool-retro-term"
	ADDITIONAL_PKGS+=" rxvt-unicode"
	#bluetooth
	ADDITIONAL_PKGS+=" bluez bluez-deprecated bluez-alsa bluedevil blueman bluez-cups gnome-bluetooth1"
	#audio
	ADDITIONAL_PKGS+=" pulseaudio pavucontrol pasystray gst-plugins-bad1 gst-plugins-good1 gst-plugins-ugly1 gst-plugins-base1"
	ADDITIONAL_PKGS+=" xfce4-pulseaudio-plugin"
	#	#ADDITIONAL_PKGS+=" pipewire wireplumber pulseaudio-utils alsa-pipewire libspa-bluetooth libjack-pipewire"
	ADDITIONAL_PKGS+=" gnome-keyring"
	ADDITIONAL_PKGS+=" orca"
	ADDITIONAL_PKGS+=" setxkbmap"
	ADDITIONAL_PKGS+=" numlockx"
	ADDITIONAL_PKGS+=" nitrogen"
	ADDITIONAL_PKGS+=" evtest-qt"
	ADDITIONAL_PKGS+=" gparted"
	ADDITIONAL_PKGS+=" connman"
	ADDITIONAL_PKGS+=" inxi"
	ADDITIONAL_PKGS+=" octoxbps"
	#login manager
	ADDITIONAL_PKGS+=" lxdm lxdm-theme-vdojo"
	#ADDITIONAL_PKGS+=" lxappearance lxinput lxrandr lxtask"
	#ADDITIONAL_PKGS+=" slim"
	#ADDITIONAL_PKGS+=" lightdm"
}

sh_choose_packages_awesome() {
	print_step "Selecionando pacotes Awesome Custom"
	#awesome
	ADDITIONAL_PKGS+=" awesome polybar"
	ADDITIONAL_PKGS+=" pcmanfm"
	ADDITIONAL_PKGS+=" font-awesome"
}

sh_choose_packages_kde() {
	print_step "Selecionando pacotes Kde Custom"
	#kde5
	ADDITIONAL_PKGS+=" kde5"
}

sh_choose_packages_gnome() {
	print_step "Selecionando pacotes Gnome Custom"
	#gnome
	ADDITIONAL_PKGS+=" gnome"
}

sh_choose_packages_fluxbox() {
	print_step "Selecionando pacotes Fluxbox Custom"
	#fluxbox
	ADDITIONAL_PKGS+=" fluxbox polybar"
	ADDITIONAL_PKGS+=" pcmanfm"
}

sh_choose_packages_enlightenment() {
	print_step "Selecionando pacotes Enlightenment Custom"
	#enlightenment
	ADDITIONAL_PKGS+=" enlightenment efl exquisite"
}

sh_choose_packages_xfce_base() {
	print_step "Selecionando pacotes XFCE Base"
	ADDITIONAL_PKGS+=" xfce4"
	ADDITIONAL_PKGS+=" firefox firefox-i18n-pt-BR"
}

sh_choose_packages_xfce_custom() {
	print_step "Selecionando pacotes XFCE Custom"
	ADDITIONAL_PKGS+=" xfce4-screenshooter xfce4-dict"
	ADDITIONAL_PKGS+=" xfce4-battery-plugin"
	ADDITIONAL_PKGS+=" xfce4-clipman-plugin"
	ADDITIONAL_PKGS+=" xfce4-cpufreq-plugin"
	ADDITIONAL_PKGS+=" xfce4-sensors-plugin"
	ADDITIONAL_PKGS+=" xfce4-systemload-plugin"
	ADDITIONAL_PKGS+=" xfce4-cpugraph-plugin"
	ADDITIONAL_PKGS+=" xfce4-datetime-plugin"
	ADDITIONAL_PKGS+=" xfce4-diskperf-plugin"
	ADDITIONAL_PKGS+=" xfce4-fsguard-plugin"
	ADDITIONAL_PKGS+=" xfce4-genmon-plugin"
	ADDITIONAL_PKGS+=" xfce4-mailwatch-plugin"
	ADDITIONAL_PKGS+=" xfce4-mpc-plugin"
	ADDITIONAL_PKGS+=" xfce4-netload-plugin"
	ADDITIONAL_PKGS+=" xfce4-time-out-plugin"
	ADDITIONAL_PKGS+=" xfce4-timer-plugin"
	ADDITIONAL_PKGS+=" xfce4-verve-plugin"
	ADDITIONAL_PKGS+=" xfce4-whiskermenu-plugin"
	ADDITIONAL_PKGS+=" xfce4-weather-plugin"
	ADDITIONAL_PKGS+=" xfce4-wavelan-plugin"
	ADDITIONAL_PKGS+=" xfce4-xkb-plugin"
	ADDITIONAL_PKGS+=" xfce4-plugins"
	ADDITIONAL_PKGS+=" mate-notification-daemon"
	ADDITIONAL_PKGS+=" plank"
	ADDITIONAL_PKGS+=" adwaita-icon-theme"
	ADDITIONAL_PKGS+=" xarchiver unrar zip unzip 7zip p7zip bzip2 file-roller"
	#	#ADDITIONAL_PKGS+=" fonts-roboto-ttf liberation-fonts-ttf dejavu-fonts-ttf fonts-droid-ttf fonts-croscore-ttf terminus-font font-emoji-one-color google-fonts-ttf"
	ADDITIONAL_PKGS+=" avahi irqbalance"
	ADDITIONAL_PKGS+=" cups system-config-printer system-config-printer-udev splix samsung-unified-driver"
	ADDITIONAL_PKGS+=" brother-brlaser cups-pdf"
	ADDITIONAL_PKGS+=" gvfs gvfs-smb gvfs-cdda inetutils iputils"
	ADDITIONAL_PKGS+=" bat"
	ADDITIONAL_PKGS+=" vlc celluloid"
	ADDITIONAL_PKGS+=" evince"
	ADDITIONAL_PKGS+=" mate-calc cmatrix xkill menulibre mugshot ocs-url"
	ADDITIONAL_PKGS+=" nvme-cli"
	ADDITIONAL_PKGS+=" remmina remmina-kwallet"
	#--repository=https://chililinux.com/void/current
	ADDITIONAL_PKGS+=" xfwm-axiom-theme"
	#	#office
	ADDITIONAL_PKGS+=" libreoffice libreoffice-i18n-pt-BR"
	#
}

debug() {
	whiptail \
		--fb \
		--clear \
		--backtitle "[debug]$0" \
		--title "[debug]$0" \
		--yesno "${*}\n" \
		0 40
	result=$?
	if ((result)); then
		exit
	fi
	return $result
}

sh_diahora() {
	DIAHORA=$(date +"%Y%m%d-%H%M")
	printf "%s\n" "$DIAHORA"
}

sh_setEnvironment() {
	declare -g BOOTLOG="/tmp/void-mklive-$(sh_diahora).log"
	declare -g LOGGER='/dev/tty8'

	# flag languages
	: PT_BR=0
	: "${EN_US=1}"
	: "${DE_DE=2}"
	: "${FR_FR=3}"
	: "${LC_DEFAULT=$(sh_getLocale)}"
}

sh_setLanguage() {
	#   langmsg=('lang=("pt_BR" "en_US" "de_DE" "fr_FR" "es_ES" "it_IT")')
	#   for xmsg in "${langmsg[@]}"; do eval "$xmsg"; done
	#   #echo "lang       ${#lang[@]} ${lang[@]} ${lang[$PT_BR]} ${lang[$EN_US]}"
	#   #echo "cmsg_ERRO ${#cmsg_ERRO[@]} ${cmsg_ERRO[@]} ${cmsg_ERRO[$PT_BR]} ${cmsg_ERRO[$EN_US]}"

	#   cmsg_LABEL[pt_BR]=$(gettext "Usar as teclas ${RED}↑ PARA CIMA ${RESET}e ${RED}↓ PARA BAIXO ${RESET}para navegar.\nUsar ${RED}T>
	#   cmsg_LBL_check[pt_BR]=$(gettext "Usar as teclas ${RED}PARA CIMA ${RESET}e ${RED}PARA BAIXO ${RESET}para navegar.\nUsar ${RED}B>
	#   cmsg_Tarball_Corrompido[pt_BR]=$(gettext "\n${RED}Aparentemente o tarball rootfs ${_TARBALL_ROOTFS} está corrompido.\n\n${BOLD>
	cmsg_CommandNotFound[pt_BR]=$(gettext "não encontrei o comando")
	cmsg_ImpossivelContinuar[pt_BR]=$(gettext "IMPOSSÍVEL CONTINUAR")
	cmsg_ImpossivelContinuar1[pt_BR]=$(gettext "Esse script precisa dos comandos listados acima")
	cmsg_ImpossivelContinuar2[pt_BR]=$(gettext "Instale-os e/ou verifique se estão no seu")
	cmsg_InstCommand[pt_BR]=$(gettext "Instalar o(s) comando(s)")
	cmsg_RunNew[pt_BR]=$(gettext "INFO: Rode novamente o aplicativo")
	cmsg_RunNewErro[pt_BR]=$(gettext "ERRO na instalação dos comandos. Tente manualmente")
}
readconf() {
	if [[ $LC_DEFAULT -eq 0 ]]; then
		read -r -p "$@ [S/n]"
	else
		read -r -p "$@ [Y/n]"
	fi
	[[ ${REPLY^} == "" ]] && return 0
	[[ ${REPLY^} == N ]] && return 1 || return 0
}

sh_checkDependencies() {
	local d
	local errorFound=false
	declare -a missing

	for d in "${DEPENDENCIES[@]}"; do
		if [[ -z $(command -v "$d") ]]; then
		  missing+=("$d")
		  errorFound=true
		  printf '%s\n' "${red}${cmsg_ERRO[$LC_DEFAULT]}${reset}: ${cmsg_CommandNotFound[$LC_DEFAULT]} ${cyan}'$d'${reset}"
    fi
	done
	if $errorFound; then
		echo "${yellow}--------------${cmsg_ImpossivelContinuar[$LC_DEFAULT]}-------------${reset}"
		echo "${cmsg_ImpossivelContinuar1[$LC_DEFAULT]}" >&2
		echo "${cmsg_ImpossivelContinuar2[$LC_DEFAULT]} \$PATH" >&2
		echo "${yellow}-----------------------------------------------${reset}"

		if [[ "$distro" = @(void|void-live|voidlinux) ]]; then
			echo
			if readconf "${yellow}${cmsg_InstCommand[$LC_DEFAULT]} '${cyan}${missing[*]}${reset}' ?"; then
				if xbps-install -Sy "${missing[@]}"; then
					errorFound=false
					sh_checkDependencies
				else
					die "${cmsg_RunNewErro[$LC_DEFAULT]}"
				fi
			fi
		else
			die "${cmsg_ERRO[$LC_DEFAULT]}: ${cmsg_InstalacaoAbortada[$LC_DEFAULT]}..."
		fi
	fi
}

sh_setAsciiLines() {
	if [[ "$LANG" =~ 'UTF-8' ]]; then
		export NCURSES_NO_UTF8_ACS=0
	else
		export NCURSES_NO_UTF8_ACS=1
	fi
}

sh_setVarColors() {
	reset=$(tput sgr0)
	# Definir os estilos de texto como variáveis
	bold=$(tput bold)
	underline=$(tput smul)   # Início do sublinhado
	nounderline=$(tput rmul) # Fim do sublinhado
	reverse=$(tput rev)      # Inverte as cores de fundo e texto
	# Definir as cores ANSI como variáveis
	black=$(tput bold)$(tput setaf 0)
	red=$(tput bold)$(tput setaf 196)
	green=$(tput bold)$(tput setaf 2)
	yellow=$(tput bold)$(tput setaf 3)
	blue=$(tput setaf 4)
	pink=$(tput setaf 5)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	gray=$(tput setaf 8)
	orange=$(tput setaf 202)
	purple=$(tput setaf 125)
	violet=$(tput setaf 61)
	light_red=$(tput setaf 9)
	light_green=$(tput setaf 10)
	light_yellow=$(tput setaf 11)
	light_blue=$(tput setaf 12)
	light_magenta=$(tput setaf 13)
	light_cyan=$(tput setaf 14)
	bright_white=$(tput setaf 15)
}

sh_getLocale() {
	local lc

	LC_DEFAULT="${Alanguage[pt_BR]}"
	LOCALE="pt_BR"
	#   if lc=$(grep _ <(locale -a) | head -1 | cut -c1-5); then
	#       LOCALE="$lc"
	#       LC_DEFAULT="${Alanguage[$lc]}"
	#   fi
}

die() {
	local script_name0="${0##*/}[${FUNCNAME[0]}]:${BASH_LINENO[0]}"
	local script_name1="${0##*/}[${FUNCNAME[1]}]:${BASH_LINENO[1]}"
	local script_name2="${0##*/}[${FUNCNAME[2]}]:${BASH_LINENO[2]}"
	info_msg "ERROR: ${script_name0} $@"
	error_out 1 $LINENO
}

info_msg() {
	printf "${red}$@${reset}\n"
}

print_step() {
	local script_name0="${0##*/}[${FUNCNAME[0]}]:${BASH_LINENO[0]}"
	local script_name1="${0##*/}[${FUNCNAME[1]}]:${BASH_LINENO[1]}"
	local script_name2="${0##*/}[${FUNCNAME[2]}]:${BASH_LINENO[2]}"
	CURRENT_STEP=$((CURRENT_STEP + 1))
	#info_msg "$script_name1=>$cyan[${CURRENT_STEP}/${STEP_COUNT}]$reset $@"
	info_msg "=>$cyan[${CURRENT_STEP}/${STEP_COUNT}]$reset $@"
}

mount_pseudofs() {
	for f in sys dev proc; do
		mkdir -p "$ROOTFS"/$f
		mount --rbind /$f "$ROOTFS"/$f
		LBIND=true
	done
}

umount_pseudofs() {
	for f in sys dev proc; do
		if ! umount -R -f "$ROOTFS/$f" >/dev/null 2>&-; then
			if $LBIND; then
				info_msg "ERROR: failed to unmount $ROOTFS/$f/"
				return 1
			fi
		fi
		LBIND=true
	done
}

error_out() {
	trap - INT TERM 0
	umount_pseudofs || exit "${1:-0}"
	[ -d "$BUILDDIR" ] && [ -z "$KEEP_BUILDDIR" ] && rm -rf --one-file-system "$BUILDDIR"
	exit "${1:-0}"
}

sh_chroot_job() {
	local cmsg="$1"
	local cjob="$2"
	local shell='/bin/bash'

	print_step "$cmsg"
	{
		bwrap --bind "$ROOTFS" / \
			--dev /dev \
			--proc /proc \
			--bind /sys /sys \
			--bind /run /run \
			--ro-bind /etc/resolv.conf /etc/resolv.conf \
			--ro-bind /etc/passwd /etc/passwd \
			--ro-bind /etc/group /etc/group \
			"$shell" -c "$cjob"
		#chroot "$ROOTFS" "$shell" -c "$cjob"  2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

copy_void_keys() {
	mkdir -p "$1"/var/db/xbps/keys
	cp keys/*.plist "$1"/var/db/xbps/keys
}

copy_dracut_files() {
	mkdir -p "$1"/usr/lib/dracut/modules.d/01vmklive
	cp dracut/vmklive/* "$1"/usr/lib/dracut/modules.d/01vmklive/
	# autologin none
	if $MAKE_FULL_X; then
		touch "$1"/usr/lib/dracut/modules.d/01vmklive/noautologin
	fi
}

copy_autoinstaller_files() {
	mkdir -p "$1"/usr/lib/dracut/modules.d/01autoinstaller
	cp dracut/autoinstaller/* "$1"/usr/lib/dracut/modules.d/01autoinstaller/
}

install_prereqs() {
	{
		LC_ALL=C XBPS_ARCH=$ARCH "$XBPS_INSTALL_CMD" -r "$VOIDHOSTDIR" ${XBPS_REPOSITORY} -c "$XBPS_HOST_CACHEDIR" -y $REQUIRED_PKGS -S
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Failed to install required software, exiting..."
}

install_packages() {
	print_step "Running dry-run for packages list selected..."
	{
		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -r "$ROOTFS" ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -yn $PACKAGE_LIST $INITRAMFS_PKGS
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Missing required binary packages, exiting..."

	mount_pseudofs

	#    print_step "Atualizando pacotes essenciais em $ROOTFS..."
	#    {
	#		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -Sf -r "$ROOTFS" ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -y xbps cryptsetup linux
	#	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	#	result="${PIPESTATUS[0]}"
	#	[ $result -ne 0 ] && die "Failed to install $PACKAGE_LIST"

	print_step "Instalando void meta pkgs BASE INITRAMFS em $ROOTFS..."
	{
		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -U -r "$ROOTFS" ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -y $PACKAGE_LIST $INITRAMFS_PKGS
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Failed to install $PACKAGE_LIST"

	print_step "Instalando void meta pkgs ADDITIONAL em rootfs..."
	{
		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -U -r "$ROOTFS" ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -y $ADDITIONAL_PKGS
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	result="${PIPESTATUS[0]}"
	[ $result -ne 0 ] && die "Failed to install $ADDITIONAL_PKGS"

	print_step "Reconfigurando o ambiente - pass 1"
	{
		xbps-reconfigure -r "$ROOTFS" -f base-files >/dev/null 2>&1
		chroot "$ROOTFS" env -i xbps-reconfigure -f base-files

		# Enable choosen UTF-8 locale and generate it into the target rootfs.
		if [ -f "$ROOTFS"/etc/default/libc-locales ]; then
			sed -e "s/\#\(${LOCALE}.*\)/\1/g" -i "$ROOTFS"/etc/default/libc-locales
		fi
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

ignore_packages() {
	mkdir -p "$ROOTFS"/etc/xbps.d
	for pkg in $IGNORE_PKGS; do
		echo "ignorepkg=$pkg" >>"$ROOTFS"/etc/xbps.d/mklive-ignore.conf
	done
}

get_conf_path() {
	local path="config-$name"
	echo "$path"
}

install_skel_user() {
	local path

	#skel
	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando user skel de ${cyan}$path${reset} into $ROOTFS/etc/skel"
			{
				[ -d "$ROOTFS/etc/skel/" ] && mkdir -p "$ROOTFS"/etc/skel/
				cp -Rpva $path/etc/. "$ROOTFS/etc/"
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_skel_root() {
	local path='config-common'

	#skel root
	if [[ -d "$path" ]]; then
		print_step "Copiando root skel de ${cyan}$path${reset} para $ROOTFS/root/"
		{
			cp -Rpva $path/etc/skel/.bash* $ROOTFS/root/
			cp -Rpva $path/etc/skel/.git-prompt.sh $ROOTFS/root/
			cp -Rpva $path/etc/skel/.dircolors $ROOTFS/root/
			rsync -a $path/etc/skel/.config/neofetch/config.conf $ROOTFS/root/.config/neofetch/
		} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
	fi
}

install_wallpapers() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando wallpapers from $path into $ROOTFS/usr/share/backgrounds"
			{
				[ -d "$ROOTFS/usr/share/" ] && mkdir -p "$ROOTFS"/usr/share/
				cp -Rpva $path/usr/share/backgrounds -t "$ROOTFS/usr/share/"
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_installer() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando installer from $path into $ROOTFS/usr/share/applications"
			{
				[ -d "$ROOTFS/usr/share/" ] && mkdir -p "$ROOTFS"/usr/share/
				cp -Rpva $path/usr/share/applications -t "$ROOTFS/usr/share/"
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_usr() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando /usr from $path into $ROOTFS/usr/"
			{
				[ -d "$ROOTFS/usr" ] && mkdir -p "$ROOTFS"/usr/
				rsync -a $path/usr/ $ROOTFS/usr/
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_common() {
	local common_path='config-common'

	print_step "Copiando config-common para $ROOTFS/"
	{
		rsync -a --copy-links $common_path/ $ROOTFS/
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

install_themes() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando themes from $path into $ROOTFS/usr/share/themes"
			{
				[ -d "$ROOTFS/usr/share/" ] && mkdir -p "$ROOTFS"/usr/share/
				cp -Rpva $path/usr/share/themes -t "$ROOTFS/usr/share/"
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_icons() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando icons from $path into $ROOTFS/usr/share/icons"
			{
				[ -d "$ROOTFS/usr/share/" ] && mkdir -p "$ROOTFS"/usr/share/
				cp -Rpva $path/usr/share/icons -t "$ROOTFS/usr/share/"
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_grub_themes() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando grub themes from $path into $ROOTFS/boot/grub/themes"
			{
				[ -d "$ROOTFS/boot/grub/themes/" ] && mkdir -p "$ROOTFS"/boot/grub/
				cp -Rpva $path/boot/grub/themes -t "$ROOTFS/boot/grub/"
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_chili_apps() {
	local path

	for path in "${aname[@]}"; do
		if [[ -d "$path" ]]; then
			print_step "Copiando apps binarios de $path para $ROOTFS/usr/bin"
			{
				[ -d "$ROOTFS/usr/bin/" ] && mkdir -p "$ROOTFS"/usr/bin/
				for x in $path/usr/bin/*; do
					install -Dm755 $x "$ROOTFS"/usr/bin/
				done
			} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		fi
	done
}

install_pacman() {
	sh_chroot_job "Instalando pacman App" "/usr/bin/pacman -Sydd pacman-contrib paru --noconfirm --overwrite \*"
	if $MAKE_X; then
		sh_chroot_job "Instalando Brave-Browser" "/usr/bin/pacman -Sdd brave-browser --noconfirm --overwrite \*"
		sh_chroot_job "Instalando Google Chrome" "/usr/bin/paru -Sdd google-chrome --noconfirm --overwrite \*"
	fi
	sh_chroot_job "Removendo Cache" "/usr/bin/paccache -k0 -r -v"
}

reconfigure_packages() {
	print_step "Reconfigurando o ambiente - pass 2"
	{
		chroot "$ROOTFS" env -i xbps-reconfigure -a
		#	sh_chroot_job "Reconfigurando o ambiente - pass 2" 'xbps-reconfigure -a'
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

finish_clean() {
	# Cleanup and remove useless stuff.
	xbps-remove -r "$ROOTFS" -Ooy >/dev/null 2>&1
	rm -rf "$ROOTFS"/var/cache/* "$ROOTFS"/run/* "$ROOTFS"/var/run/*
}

enable_services() {
	SERVICE_LIST="$*"
	for service in $SERVICE_LIST; do
		if ! [ -e $ROOTFS/etc/sv/$service ]; then
			die "service $service not in /etc/sv"
		fi
		ln -sf /etc/sv/$service $ROOTFS/etc/runit/runsvdir/default/
	done
}

copy_include_directories() {
	for includedir in "${INCLUDE_DIRS[@]}"; do
		info_msg "=> copying include directory '$includedir' ..."
		find "$includedir" -mindepth 1 -maxdepth 1 -exec cp -rfpPv {} "$ROOTFS"/ \;
	done
}

generate_initramfs() {
	local _args

	print_step "Gerando initramfs into $ROOTFS"
	{
		copy_dracut_files "$ROOTFS"
		copy_autoinstaller_files "$ROOTFS"
		chroot "$ROOTFS" env -i /usr/bin/dracut -N --"${INITRAMFS_COMPRESSION}" --add-drivers "ahci" --force-add "vmklive autoinstaller" --omit systemd "/boot/initrd" $KERNELVERSION
		result="${PIPESTATUS[0]}"
		[ $result -ne 0 ] && die "Failed to generate the initramfs"
		mv "$ROOTFS"/boot/initrd "$BOOT_DIR"
		cp "$ROOTFS"/boot/vmlinuz-$KERNELVERSION "$BOOT_DIR"/vmlinuz
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

cleanup_rootfs() {
	for f in ${INITRAMFS_PKGS}; do
		revdeps=$(xbps-query -r "$ROOTFS" -X $f)
		if [ -n "$revdeps" ]; then
			xbps-pkgdb -r "$ROOTFS" -m auto $f
		else
			xbps-remove -r "$ROOTFS" -Ry ${f} >/dev/null 2>&1
		fi
	done
	rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01vmklive
	rm -r "$ROOTFS"/usr/lib/dracut/modules.d/01autoinstaller
}

generate_isolinux_boot() {
	cp -f "$SYSLINUX_DATADIR"/isolinux.bin "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/ldlinux.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/libcom32.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/vesamenu.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/libutil.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/chain.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/reboot.c32 "$ISOLINUX_DIR"
	cp -f "$SYSLINUX_DATADIR"/poweroff.c32 "$ISOLINUX_DIR"
	cp -f isolinux/isolinux.cfg.in "$ISOLINUX_DIR"/isolinux.cfg
	cp -f ${SPLASH_IMAGE} "$ISOLINUX_DIR"

	sed -i -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
		-e "s|@@KERNVER@@|${KERNELVERSION}|" \
		-e "s|@@KEYMAP@@|${KEYMAP}|" \
		-e "s|@@ARCH@@|$BASE_ARCH|" \
		-e "s|@@LOCALE@@|${LOCALE}|" \
		-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
		-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
		"$ISOLINUX_DIR"/isolinux.cfg

	# include memtest86+
	cp -f "$VOIDHOSTDIR"/boot/memtest.bin "$BOOT_DIR"
}

generate_grub_efi_boot() {
	{
		cp -f grub/grub.cfg "$GRUB_DIR"
		cp -f grub/grub_void.cfg.in "$GRUB_DIR"/grub_void.cfg
		sed -i -e "s|@@SPLASHIMAGE@@|$(basename "${SPLASH_IMAGE}")|" \
			-e "s|@@KERNVER@@|${KERNELVERSION}|" \
			-e "s|@@KEYMAP@@|${KEYMAP}|" \
			-e "s|@@ARCH@@|$BASE_ARCH|" \
			-e "s|@@BOOT_TITLE@@|${BOOT_TITLE}|" \
			-e "s|@@BOOT_CMDLINE@@|${BOOT_CMDLINE}|" \
			-e "s|@@LOCALE@@|${LOCALE}|" "$GRUB_DIR"/grub_void.cfg
		mkdir -p "$GRUB_DIR"/fonts
		cp -f "$GRUB_DATADIR"/unicode.pf2 "$GRUB_DIR"/fonts

		modprobe -q loop || :

		# Create EFI vfat image.
		truncate -s 32M "$GRUB_DIR"/efiboot.img
		mkfs.vfat -F12 -S 512 -n "grub_uefi" "$GRUB_DIR/efiboot.img"

		GRUB_EFI_TMPDIR="$(mktemp --tmpdir="$HOME" -d)"
		LOOP_DEVICE="$(losetup --show --find "${GRUB_DIR}"/efiboot.img)"
		mount -o rw,flush -t vfat "${LOOP_DEVICE}" "${GRUB_EFI_TMPDIR}"

		cp -a "$IMAGEDIR"/boot "$VOIDHOSTDIR"
		xbps-uchroot "$VOIDHOSTDIR" grub-mkstandalone -- \
			--directory="/usr/lib/grub/i386-efi" \
			--format="i386-efi" \
			--output="/tmp/bootia32.efi" \
			"boot/grub/grub.cfg"
		if [ $? -ne 0 ]; then
			umount "$GRUB_EFI_TMPDIR"
			losetup --detach "${LOOP_DEVICE}"
			die "Failed to generate EFI loader"
		fi
		mkdir -p "${GRUB_EFI_TMPDIR}"/EFI/BOOT
		cp -f "$VOIDHOSTDIR"/tmp/bootia32.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTIA32.EFI
		xbps-uchroot "$VOIDHOSTDIR" grub-mkstandalone -- \
			--directory="/usr/lib/grub/x86_64-efi" \
			--format="x86_64-efi" \
			--output="/tmp/bootx64.efi" \
			"boot/grub/grub.cfg"
		if [ $? -ne 0 ]; then
			umount "$GRUB_EFI_TMPDIR"
			losetup --detach "${LOOP_DEVICE}"
			die "Failed to generate EFI loader"
		fi
		cp -f "$VOIDHOSTDIR"/tmp/bootx64.efi "${GRUB_EFI_TMPDIR}"/EFI/BOOT/BOOTX64.EFI
		umount "$GRUB_EFI_TMPDIR"
		losetup --detach "${LOOP_DEVICE}"
		rm -rf "$GRUB_EFI_TMPDIR"

		# include memtest86+
		cp -f "$VOIDHOSTDIR"/boot/memtest.efi "$BOOT_DIR"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

get_compression_options() {
	local param
	case $1 in
	gzip) param=" -noappend -ef exclude_dir -comp gzip -Xcompression-level 1" ;;
	xz) param=" -noappend -ef exclude_dir -b 1048576 -comp xz -Xdict-size 100%" ;;
	zstd) param=" -noappend -ef exclude_dir -b 1M -comp zstd -Xcompression-level 1" ;;
	lzma) param=" -noappend -ef exclude_dir -b 1M -comp lzma" ;;
	lz4) param=" -noappend -ef exclude_dir -b 1M -comp lz4 -Xhc" ;;
	esac
	echo "$param"
}

generate_squashfs() {
	local options=$(get_compression_options "$SQUASHFS_COMPRESSION")

	umount_pseudofs
	{
		# Find out required size for the rootfs and create an ext3fs image off it.
		ROOTFS_SIZE=$(du --apparent-size -sm "$ROOTFS" | awk '{print $1}')
		mkdir -p "$BUILDDIR/tmp/LiveOS"
		truncate -s "$((ROOTFS_SIZE + ROOTFS_SIZE))M" "$BUILDDIR"/tmp/LiveOS/ext3fs.img
		mkdir -p "$BUILDDIR/tmp-rootfs"
		mkfs.ext3 -F -m1 "$BUILDDIR/tmp/LiveOS/ext3fs.img" 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
		mount -o loop "$BUILDDIR/tmp/LiveOS/ext3fs.img" "$BUILDDIR/tmp-rootfs"
		cp -a "$ROOTFS"/* "$BUILDDIR"/tmp-rootfs/
		umount -f "$BUILDDIR/tmp-rootfs"
		mkdir -p "$IMAGEDIR/LiveOS"

		#       "$options" || die "Failed to generate squashfs image"
		"$VOIDHOSTDIR"/usr/bin/mksquashfs "$BUILDDIR/tmp" "$IMAGEDIR/LiveOS/squashfs.img" \
			-comp "${SQUASHFS_COMPRESSION}" || die "Failed to generate squashfs image"
		chmod 444 "$IMAGEDIR/LiveOS/squashfs.img"

		# Remove rootfs and temporary dirs, we don't need them anymore.
		[ -z "$KEEP_BUILDDIR" ] && rm -rf "$ROOTFS"
		rm -rf "$BUILDDIR/tmp-rootfs"
		rm -rf "$BUILDDIR/tmp"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

generate_iso_image() {
	{
		"$VOIDHOSTDIR"/usr/bin/xorriso \
			-as mkisofs \
			-iso-level 3 -rock -joliet \
			-max-iso9660-filenames -omit-period \
			-omit-version-number -relaxed-filenames -allow-lowercase \
			-volid "$VOL_ID" \
			-eltorito-boot boot/isolinux/isolinux.bin \
			-eltorito-catalog boot/isolinux/boot.cat \
			-no-emul-boot -boot-load-size 4 -boot-info-table \
			-eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot \
			-isohybrid-mbr "$SYSLINUX_DATADIR"/isohdpfx.bin \
			-output "$OUTPUT_FILE" "$IMAGEDIR" || die "Failed to generate ISO image"
	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
}

usage() {
	cat <<-EOF
		        Usage: $PROGNAME [options]

		        Generates a basic live ISO image of Void Linux. This ISO image can be written
		        to a CD/DVD-ROM or any USB stick.

		        To generate a more complete live ISO image, use build-x86-images.sh.

		        OPTIONS
		                -a <arch>          Set XBPS_ARCH in the ISO image
		                -b <system-pkg>    Set an alternative base package (default: base-system)
		                -r <repo>          Use this XBPS repository. May be specified multiple times
		                -c <cachedir>      Use this XBPS cache directory (default: ./xbps-cachedir-<arch>)
		                -k <keymap>        Default keymap to use (default: us)
		                -l <locale>        Default locale to use (default: en_US.UTF-8)
		                -i <lz4|gzip|bzip2|xz|zstd|lzma|lzo> Compression type for the initramfs image (default: xz)
		                -s <lz4|gzip|bzip2|xz|zstd|lzma|lz4|lzo>   Compression type for the squashfs image (default: xz)
		                -o <file>          Output file name for the ISO image (default: automatic)
		                -p "<pkg> ..."     Install additional packages in the ISO image
		                -g "<pkg> ..."     Ignore packages when building the ISO image
		                -I <includedir>    Include directory structure under given path in the ROOTFS
		                -S "<service> ..." Enable services in the ISO image
		                -C "<arg> ..."     Add additional kernel command line arguments
		                -T <title>         Modify the bootloader title (default: Void Linux)
		                -v linux<version>  Install a custom Linux version on ISO image (default: linux metapackage)
		                -K                 Do not remove builddir
		                -h                 Show this help and exit
		                -V                 Show version and exit
		                -n                 NAO cria squashfs, usa antigo
		                -X                 Make XFCE iso base.
		                -Y                 Make XFCE iso custom.
		                -W                 Make AWESOME iso custom.
		                -E                 Make ENLIGHTNMENT iso custom.
		                -F                 Make FLUXBOX iso custom.
		                -G                 Make GNOME X iso custom.
		                -P                 Make KDE PLASM X iso custom.
		                -A                 Make ALL X iso custom.
		                -Q                 Quiet mode (default: 0)

	EOF
}

set_config_distro() {
	declare -ga name

	if $MAKE_FULL_X; then
		title='Void Linux Full X Custom'
		name='fullx-custom'
		aname=(config-fullx-custom
			config-enlightenment-custom
			config-awesome-custom
			config-fluxbox-custom
			config-xfce-base
			config-xfce-custom
			config-kde-custom
			config-gnome-custom)
	elif $MAKE_ENLIGHTENMENT; then
		title='Void Linux Enlightenment Custom'
		name='enlightenment-custom'
		aname=('config-enlightenment-custom')
		aname=('config-enlightenment-custom')
	elif $MAKE_AWESOME; then
		title='Void Linux Awesome Custom'
		name='awesome-custom'
		aname=('config-awesome-custom')
	elif $MAKE_FLUXBOX; then
		title='Void Linux Fluxbox Custom'
		name='fluxfox-custom'
		aname=('config-fluxbox-custom')
	elif $MAKE_KDE; then
		title='Void Linux Kde Custom'
		name='kde-custom'
		aname=('config-kde-custom')
	elif $MAKE_GNOME; then
		title='Void Linux Gnome Custom'
		name='gnome-custom'
		aname=('config-gnome-custom')
	elif $MAKE_XFCE_BASE; then
		title='Void Linux Xfce Base'
		name='xfce-base'
		aname=('config-xfce-base')
	elif $MAKE_XFCE_CUSTOM; then
		title='Void Linux Xfce Custom'
		name='xfce-custom'
		aname=('config-xfce-custom')
	else
		title='Void Linux Base Custom'
		name='base-custom'
	fi
	print_step "Building ISO    => ${yellow}$title${reset}"
	print_step "Output file ISO => ${yellow}$OUTPUT_FILE${reset}"
	print_step "Compression SFS => ${yellow}$SQUASHFS_COMPRESSION${reset}"
	print_step "Compression RAM => ${yellow}$INITRAM_COMPRESSION${reset}"
	print_step "ISO LABEL       => ${yellow}$VOL_ID${reset}"
}

#
# main()
#
sh_setVarColors
sh_setEnvironment
sh_getLocale
sh_setLanguage
sh_checkDependencies
sh_setAsciiLines

while getopts "a:b:r:c:C:T:Kk:l:i:I:S:s:o:p:g:v:VhXxYyQqWwNnEeFfAGP" opt; do
	case $opt in
	a) BASE_ARCH="$OPTARG" ;;
	b) BASE_SYSTEM_PKG="$OPTARG" ;;
	r) XBPS_REPOSITORY="--repository=$OPTARG $XBPS_REPOSITORY" ;;
	c) XBPS_CACHEDIR="$OPTARG" ;;
	g) IGNORE_PKGS="$IGNORE_PKGS $OPTARG" ;;
	K) KEEP_BUILDDIR=1 ;;
	k) KEYMAP="$OPTARG" ;;
	l) LOCALE="$OPTARG" ;;
	I) INCLUDE_DIRS+=("$OPTARG") ;;
	i) INITRAMFS_COMPRESSION="$OPTARG" ;;
	s) SQUASHFS_COMPRESSION="$OPTARG" ;;
	S) SERVICE_LIST="$SERVICE_LIST $OPTARG" ;;
	o) OUTPUT_FILE="$OPTARG" ;;
	p) PACKAGE_LIST="$PACKAGE_LIST $OPTARG" ;;
	C) BOOT_CMDLINE="$OPTARG" ;;
	T) BOOT_TITLE="$OPTARG" ;;
	x | X)
		MAKE_X=true
		MAKE_XFCE_BASE=true
		;;
	y | Y)
		MAKE_X=true
		MAKE_XFCE_CUSTOM=true
		;;
	w | W)
		MAKE_X=true
		MAKE_AWESOME=true
		;;
	e | E)
		MAKE_X=true
		MAKE_ENLIGHTENMENT=true
		;;
	f | F)
		MAKE_X=true
		MAKE_FLUXBOX=true
		;;
	G)
		MAKE_X=true
		MAKE_GNOME=true
		;;
	P)
		MAKE_X=true
		MAKE_KDE=true
		;;
	A)
		MAKE_X=true
		MAKE_FULL_X=true
		;;
	q | Q) QUIET=true ;;
	v) LINUX_VERSION="$OPTARG" ;;
	V)
		version
		exit 0
		;;
	h)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

# Check for root permissions.
if [ "$(id -u)" -ne 0 ]; then
	die "Must be run as root, exiting..."
fi

set_config_distro
sh_choose_packages_base
if $MAKE_X; then
	sh_choose_packages_common_X
	if $MAKE_FULL_X; then
		STEP_COUNT=72
		sh_choose_packages_awesome
		sh_choose_packages_enlightenment
		sh_choose_packages_fluxbox
		sh_choose_packages_xfce_base
		sh_choose_packages_xfce_custom
		sh_choose_packages_gnome
		sh_choose_packages_kde
	elif $MAKE_ENLIGHTENMENT; then
		sh_choose_packages_enlightenment
	elif $MAKE_AWESOME; then
		sh_choose_packages_awesome
	elif $MAKE_FLUXBOX; then
		sh_choose_packages_fluxbox
	elif $MAKE_KDE; then
		sh_choose_packages_kde
	elif $MAKE_GNOME; then
		sh_choose_packages_gnome
	elif $MAKE_XFCE_BASE; then
		sh_choose_packages_xfce_base
	elif $MAKE_XFCE_CUSTOM; then
		sh_choose_packages_xfce_base
		sh_choose_packages_xfce_custom
	fi
fi

#XBPS_REPOSITORY="$XBPS_REPOSITORY --repository=http://void.chililinux.com/voidlinux/current"
#XBPS_REPOSITORY="$XBPS_REPOSITORY --repository=http://100.97.0.15:92/voidlinux/current --repository=http://100.97.0.15:92/voidlinux/current/extras"
#XBPS_REPOSITORY="$XBPS_REPOSITORY --repository=https://mirrors.servercentral.com/voidlinux/current""\
# --repository=https://mirrors.servercentral.com/voidlinux/current/nonfree""\
# --repository=https://mirrors.servercentral.com/voidlinux/current/multilib""\
# --repository=https://mirrors.servercentral.com/voidlinux/current/multilib/nonfree""\
# --repository=https://chililinux.com/void/current""\
# --repository=/github/void-packages/hostdir/binpkgs"
# --repository=/home/vcatafesta/github/void-packages/hostdir/binpkgs"
XBPS_REPOSITORY="$XBPS_REPOSITORY --repository=https://repo-fastly.voidlinux.org/current""\
 --repository=https://repo-fastly.voidlinux.org/current/nonfree""\
 --repository=https://repo-fastly.voidlinux.org/current/multilib""\
 --repository=https://repo-fastly.voidlinux.org/current/multilib/nonfree""\
 --repository=https://chililinux.com/void/current"

# Configure dracut to use overlayfs for the writable overlay.
BOOT_CMDLINE="$BOOT_CMDLINE rd.live.overlay.overlayfs=1 "
ARCH=$(xbps-uhelper arch)

# Set defaults
: ${BASE_ARCH:=$(xbps-uhelper arch 2>/dev/null || uname -m)}
: ${XBPS_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${BASE_ARCH}}
: ${XBPS_HOST_CACHEDIR:="$(pwd -P)"/xbps-cachedir-${ARCH}}
#: ${KEYMAP:=us}
#: ${LOCALE:=en_US.UTF-8}
: ${KEYMAP:=br-abnt2}
: ${LOCALE:=pt_BR.UTF-8}
: ${INITRAMFS_COMPRESSION:=xz}
: ${SQUASHFS_COMPRESSION:=xz}
: ${BASE_SYSTEM_PKG:=base-system}
: ${BOOT_TITLE:="$title"}

# Required packages in the image for a working system.
PACKAGE_LIST="$BASE_SYSTEM_PKG $PACKAGE_LIST"

#mount -o remount,size=18G,mode=1777 tmpfs /tmp
#ROOTDIR='/tmp'
#mount -o remount,size=18G,mode=1777 tmpfs /dev/shm
#ROOTDIR='/dev/shm'
ROOTDIR="/lfs/voidlinux"
#mount /dev/nvme0n1p2 /mnt/voidlinux
#ROOTDIR='/mnt/voidlinux/@/lixo'

if [ -n "$ROOTDIR" ]; then
	#	BUILDDIR=$(mktemp --tmpdir="$ROOTDIR" -d)
	BUILDDIR="$ROOTDIR/$name"
	[ -d "$BUILDDIR" ] && [ -z "$KEEP_BUILDDIR" ] && rm -rf --one-file-system "$BUILDDIR"
	mkdir -p "$BUILDDIR"
else
	BUILDDIR=$(mktemp --tmpdir="$(pwd -P)" -d)
fi
BUILDDIR=$(readlink -f "$BUILDDIR")
IMAGEDIR="$BUILDDIR/image"
ROOTFS="$IMAGEDIR/rootfs"
VOIDHOSTDIR="$BUILDDIR/void-host"
BOOT_DIR="$IMAGEDIR/boot"
ISOLINUX_DIR="$BOOT_DIR/isolinux"
GRUB_DIR="$BOOT_DIR/grub"
ISOLINUX_CFG="$ISOLINUX_DIR/isolinux.cfg"
#CURRENT_STEP=0
#STEP_COUNT=16

[ "${#INCLUDE_DIRS[@]}" -gt 0 ] && STEP_COUNT=$((STEP_COUNT + 1))
[ -n "${IGNORE_PKGS}" ] && STEP_COUNT=$((STEP_COUNT + 1))

: ${SYSLINUX_DATADIR:="$VOIDHOSTDIR"/usr/lib/syslinux}
: ${GRUB_DATADIR:="$VOIDHOSTDIR"/usr/share/grub}
: ${SPLASH_IMAGE:=data/splash.png}
: ${XBPS_INSTALL_CMD:=xbps-install}
: ${XBPS_REMOVE_CMD:=xbps-remove}
: ${XBPS_QUERY_CMD:=xbps-query}
: ${XBPS_RINDEX_CMD:=xbps-rindex}
: ${XBPS_UHELPER_CMD:=xbps-uhelper}
: ${XBPS_RECONFIGURE_CMD:=xbps-reconfigure}

mkdir -p "$ROOTFS" "$VOIDHOSTDIR" "$ISOLINUX_DIR" "$GRUB_DIR"

print_step "Sincronizando dados do repositório XBPS..."
{
	copy_void_keys "$ROOTFS"
	copy_void_keys "$VOIDHOSTDIR"
	LC_ALL=C XBPS_ARCH=$BASE_ARCH $XBPS_INSTALL_CMD -Sy -r "$ROOTFS" ${XBPS_REPOSITORY}
	LC_ALL=C XBPS_ARCH=$ARCH $XBPS_INSTALL_CMD -Sy -r "$VOIDHOSTDIR" ${XBPS_REPOSITORY}
} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
result="${PIPESTATUS[0]}"
[ $result -ne 0 ] && die "Failed to synchronizing, exiting..."

# Get linux version for ISO
# If linux version option specified use
if [ -n "$LINUX_VERSION" ]; then
	if ! echo "$LINUX_VERSION" | grep "linux[0-9._]\+"; then
		die "-v option must be in format linux<version>"
	fi

	_linux_series="$LINUX_VERSION"
	PACKAGE_LIST="$PACKAGE_LIST $LINUX_VERSION"
else # Otherwise find latest stable version from linux meta-package
	_linux_series=$(XBPS_ARCH=$BASE_ARCH $XBPS_QUERY_CMD -r "$ROOTFS" ${XBPS_REPOSITORY:=-R} -x linux | grep 'linux[0-9._]\+')
fi

_kver=$(XBPS_ARCH=$BASE_ARCH $XBPS_QUERY_CMD -r "$ROOTFS" ${XBPS_REPOSITORY:=-R} -p pkgver ${_linux_series})
KERNELVERSION=$($XBPS_UHELPER_CMD getpkgversion ${_kver})

if [ "$?" -ne "0" ]; then
	die "Failed to find kernel package version"
fi
: ${OUTPUT_FILE="void-live-$name-${BASE_ARCH}-${KERNELVERSION}-$(sh_diahora).iso"}
print_step "Instalando software para gerar a imagem de disco..."
install_prereqs

mkdir -p "$ROOTFS"/etc
[ -s data/motd ] && cp data/motd "$ROOTFS"/etc
[ -s data/issue ] && cp data/issue "$ROOTFS"/etc

if [ -n "$IGNORE_PKGS" ]; then
	print_step "Ignoring packages in the rootfs: ${IGNORE_PKGS} ..."
	ignore_packages
fi

print_step "Instalando pacotes void em $ROOTFS..."
install_packages
install_skel_user
install_skel_root
if $MAKE_X; then
	#   install_installer
	:
fi
if $MAKE_XFCE_CUSTOM; then
	install_wallpapers
	install_themes
	install_icons
fi
install_usr
install_common
#install_chili_apps
#install_grub_themes
reconfigure_packages
install_pacman
finish_clean

: ${DEFAULT_SERVICE_LIST:=agetty-tty1 agetty-tty2 agetty-tty3 agetty-tty4 agetty-tty5 agetty-tty6 udevd dhcpcd}
if $MAKE_X; then
	: ${ADDITIONAL_SERVICE_LIST:=NetworkManager dbus elogind lxdm polkitd bluetoothd connmand acpid}
	if $MAKE_XFCE_CUSTOM; then
		ADDITIONAL_SERVICE_LIST+=' avahi-daemon cupsd irqbalance sshd uuidd'
	fi
else # tty
	ADDITIONAL_SERVICE_LIST+=' gpm'
fi
print_step "Enabling services... ${DEFAULT_SERVICE_LIST} ${SERVICE_LIST} ${ADDITIONAL_SERVICE_LIST}"
enable_services ${DEFAULT_SERVICE_LIST} ${SERVICE_LIST} ${ADDITIONAL_SERVICE_LIST}

if [ "${#INCLUDE_DIRS[@]}" -gt 0 ]; then
	print_step "Copying directory structures into the rootfs ..."
	copy_include_directories
fi

print_step "Generating initramfs image ($INITRAMFS_COMPRESSION)..."
generate_initramfs

print_step "Generating isolinux support for PC-BIOS systems..."
generate_isolinux_boot

print_step "Generating GRUB support for EFI systems..."
generate_grub_efi_boot

print_step "Cleaning up rootfs..."
cleanup_rootfs

print_step "Generating squashfs image ($SQUASHFS_COMPRESSION) from rootfs..."
generate_squashfs

print_step "Generating ISO image..."
generate_iso_image

hsize=$(du -sh "$OUTPUT_FILE" | awk '{print $1}')
info_msg "${green}Created $(readlink -f "$OUTPUT_FILE") ($hsize) successfully.${reset}"
