#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166,SC2034
#
#  rmake
#  Created: 2023/09/18 - 09:05
#  Updated: qua 16 set 2026 00:52:14 -04
#
#  Copyright (c) 2019-2026, Vilmar Catafesta <vcatafesta@gmail.com>
#  Copyright (c) 2019-2026, ChiliLinux Development Team <https://chililinux.com> <https://github.com/chililinux>
#  Copyright (c) 2026-2026, VoidBR Development Team <https://voidbr.org> <https://github.com/voidlinuxbr>
#  Assembled By Vilmar Catafesta for the ChiliLinux project.
#  Assembled By Vilmar Catafesta for the VoidBR project.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY Vilmar Catafesta ''AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
red="$(printf '\033[1;31m')"
green="$(printf '\033[1;32m')"
yellow="$(printf '\033[1;33m')"
cyan="$(printf '\033[1;36m')"
reset="$(printf '\033[0m')"

VERSION="linux7.2"

FLAVORS=(
	base
	bspwm
	cinnamon
	enlightenment
	fluxbox
	fullx
	gnome
	hyprland
	i3
	install
	lxde
	mango
	mate
	plasma
	plasma-louvorja-piano
	river
	sway
	xfce
)

msg() {
	printf '[rmake] %s\n' "$*"
}

usage() {
	cat <<EOF
${cyan}VoidBR ISO Builder${reset}

${yellow}Usage:${reset}
    $0 ${green}<flavor> [flavor ...] [--flag=valor ...]${reset}

${yellow}Examples:${reset}
    $0 base
    $0 base --bootloader=limine
    $0 xfce --bootloader=grub
    $0 xfce lxde plasma --bootloader=limine

${yellow}Available flavors:${reset}
    ${green}all ${FLAVORS[*]}${reset}

${yellow}Flags (repassadas direto pro mkiso):${reset}
    ${green}--automatic --bootloader=grub|limine${reset}   Bootloader da ISO
EOF
	exit 1
}

[[ $# -eq 0 ]] && usage

REQUESTED=()
EXTRA_ARGS=()

for arg in "$@"; do
	if [[ "$arg" == --* ]]; then
		EXTRA_ARGS+=("$arg")
		continue
	fi

	flavor="${arg,,}"

	case "$flavor" in
		hypr) flavor="hyprland" ;;
		louvor) flavor="plasma-louvorja-piano" ;;
		all)
			REQUESTED=("${FLAVORS[@]}")
			break
			;;
	esac

	if [[ ! " ${FLAVORS[*]} " =~ " ${flavor} " ]]; then
		msg "${red}Error:${reset} Invalid flavor '${yellow}${arg}${reset}'."
		echo
		usage
	fi

	REQUESTED+=("$flavor")
done

BUILD_ARGS=(
	'--automatic'
	'--bootloader=limine'
	"${EXTRA_ARGS[@]}"
)

msg "${cyan}Kernel   :${reset} ${green}${VERSION}${reset}"
[[ ${#EXTRA_ARGS[@]} -gt 0 ]] &&
	msg "${cyan}Flags    :${reset} ${green}${EXTRA_ARGS[*]}${reset}"

for flavor in "${REQUESTED[@]}"; do
	msg "${cyan}Building :${reset} ${green}${flavor}${reset}"

	build_flavor="$flavor"
	[[ "$build_flavor" == "base" ]] && build_flavor=""

	msg "${cyan}Running  :${reset} ${green}sudo bash mkiso ${BUILD_ARGS[*]} -v ${VERSION} ${build_flavor}${reset}"

	if sudo bash mkiso "${BUILD_ARGS[@]}" -v "${VERSION}" "${build_flavor}"; then
		echo
		msg "${green}✓ ${flavor} completed.${reset}"
	else
		echo
		msg "${red}✗ Failed to build ${flavor}.${reset}"
		exit 1
	fi
done

msg "${green}✓ All requested builds completed successfully.${reset}"
