#!/usr/bin/env bash

red="$(printf '\033[1;31m')"
green="$(printf '\033[1;32m')"
yellow="$(printf '\033[1;33m')"
cyan="$(printf '\033[1;36m')"
reset="$(printf '\033[0m')"

VERSION="linux7.0"

usage() {
	cat <<EOF

${cyan}VoidBR ISO Builder${reset}

${yellow}Usage:${reset}
    $0 ${green}<flavor>${reset}

${yellow}Examples:${reset}
    $0 all
    $0 base
    $0 install
    $0 xfce
    $0 gnome
    $0 plasma
    $0 cinnamon
    $0 mate
    $0 sway

${yellow}Available flavors:${reset}
    ${green}all${reset}        Build all images
    ${green}base${reset}       Build Base ISO
    ${green}install${reset}    Build Installer ISO
    ${green}xfce${reset}       Build XFCE ISO
    ${green}gnome${reset}      Build GNOME ISO
    ${green}plasma${reset}     Build KDE Plasma ISO
    ${green}cinnamon${reset}   Build Cinnamon ISO
    ${green}mate${reset}       Build MATE ISO
    ${green}sway${reset}       Build SWAY ISO
EOF
	exit 1
}

# É obrigatório informar um parâmetro
[[ $# -eq 0 ]] && usage

FLAVOR="$1"

case "$FLAVOR" in
all)
	FLAVORS=(
		base
		install
		xfce
		gnome
		plasma
		cinnamon
		mate
		sway
	)
	;;
base | install | xfce | gnome | plasma | cinnamon | mate | sway)
	FLAVORS=("$FLAVOR")
	;;
*)
	echo -e "${red}Error:${reset} Invalid flavor '${yellow}${FLAVOR}${reset}'."
	echo
	usage
	;;
esac

echo -e "${cyan}Kernel :${reset} ${green}${VERSION}${reset}"
echo

for flavor in "${FLAVORS[@]}"; do
	echo -e "${yellow}==>${reset} Building ${green}${flavor}${reset}..."

	[ "${flavor}" == 'base' ] && flavor=
	if sudo bash mkiso --automatic -v "${VERSION}" "${flavor}"; then
		echo -e "${green}✓ ${flavor} completed.${reset}"
	else
		echo -e "${red}✗ Failed to build ${flavor}.${reset}"
		exit 1
	fi

	echo
done

echo -e "${green}All requested builds completed successfully.${reset}"
