#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166,SC2034
#
#  rmake
#  Created: 2023/09/18 - 09:05
#  Updated: sex 24 jul 2026 12:02:29 -04
#
#  Copyright (c) 2019-2026, Vilmar Catafesta <vcatafesta@gmail.com>
#  Copyright (c) 2019-2026, ChiliLinux Development Team <https://chililinux.com> <https://github.com/chililinux>
#  Assembled By Vilmar Catafesta for the ChiliLinux project.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY Vilmar Catafesta ''AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################

#!/usr/bin/env bash

red="$(printf '\033[1;31m')"
green="$(printf '\033[1;32m')"
yellow="$(printf '\033[1;33m')"
cyan="$(printf '\033[1;36m')"
reset="$(printf '\033[0m')"
rst="$(printf '\033[0m')"

VERSION="linux7.2"

msg() {
	echo -e "[rmake]$*"
}

usage() {
	cat <<EOF

${cyan}VoidBR ISO Builder${reset}

${yellow}Usage:${reset}
    $0 ${green}<flavor> [flavor ...]${reset}

${yellow}Examples:${reset}
    $0 all
    $0 base
    $0 cinnamon
    $0 fluxbox
    $0 gnome
    $0 hypr
    $0 install
    $0 plasma
    $0 mango
    $0 mate
    $0 sway
    $0 xfce
    #
    $0 hypr plasma
    $0 sway plasma xfce

${yellow}Available flavors:${reset}
    ${green}all${reset}             Build all images
    ${green}base${reset}            Build Base ISO
    ${green}cinnamon${reset}        Build Cinnamon ISO
    ${green}fluxbox${reset}         Build FLUXBOX ISO
    ${green}gnome${reset}           Build GNOME ISO
    ${green}hyprland/hypr${reset}   Build Hyprland ISO
    ${green}install${reset}         Build Installer ISO
    ${green}mango${reset}           Build Mango ISO
    ${green}mate${reset}            Build MATE ISO
    ${green}plasma${reset}          Build KDE Plasma ISO
    ${green}sway${reset}            Build Sway ISO
    ${green}xfce${reset}            Build XFCE ISO
    ${green}fullx${reset}           Build FullX ISO
EOF
	exit 1
}

[[ $# -eq 0 ]] && usage

FLAVORS=()

for arg in "$@"; do
	flavor="${arg,,}"

	case "$flavor" in
	all)
		FLAVORS=(
			base
			cinnamon
			fluxbox
			gnome
			hyprland
			install
			mango
			mate
			plasma
			sway
			xfce
			fullx
		)
		break
		;;
	base|install|xfce|fluxbox|gnome|plasma|cinnamon|mate|mango|sway|hypr|hyprland|fullx)
		[[ "$flavor" == "hypr" ]] && flavor="hyprland"
		FLAVORS+=("$flavor")
		;;
	*)
		msg "${red}Error:${reset} Invalid flavor '${yellow}${arg}${reset}'."
		echo
		usage
		;;
	esac
done

msg "${cyan}Kernel   :${rst} ${green}${VERSION}${rst}"

for flavor in "${FLAVORS[@]}"; do
	msg "${cyan}Building :${rst} ${green}${flavor}${rst}"
	msg "${cyan}Running  :${rst} ${green}sudo bash mkiso --automatic -v ${VERSION} ${flavor}${rst}"

	build_flavor="$flavor"
	[[ "$build_flavor" == "base" ]] && build_flavor=""

	if sudo bash mkiso --automatic -v "${VERSION}" "${build_flavor}"; then
		echo
		msg "${green}✓ ${flavor} completed.${reset}"
	else
		echo
		msg "${red}✗ Failed to build ${flavor}.${reset}"
		exit 1
	fi
done

msg "${green}✓ All requested builds completed successfully.${reset}"
