export declare const getFeatureFlag: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getStaticFile: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const checkCustomerIsLogged: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const requestBffExtension: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const partnerGetByDomain: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getConfiguration: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const featureControllerSubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const featureControllerUnsubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const checkFeaturesInExecutionByTab: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getCardStatus: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const sendGA4: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const sendBigQuery: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getSearchNiche: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const featureControllerChangeStatus: {
    dispatch: (status: boolean, tab: any) => Promise<any>;
};
declare const _default: {
    getFeatureFlag: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getStaticFile: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    checkCustomerIsLogged: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    requestBffExtension: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    partnerGetByDomain: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getConfiguration: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    featureControllerSubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    featureControllerUnsubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    checkFeaturesInExecutionByTab: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getCardStatus: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    sendGA4: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    sendBigQuery: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getSearchNiche: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
};
export default _default;
