export declare const configGetSettings: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getStaticFile: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getFeatureFlag: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const checkCashbackIsActivated: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const partnerGetByDomain: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const partnerGetById: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const redirectOpenRedirect: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const sendGA4: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const sendBigQuery: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const cashbackOfferCached: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getConfiguration: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const getABTestSide: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const sendABtest: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const featureControllerSubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const featureControllerUnsubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const checkFeaturesInExecutionByTab: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
export declare const featureControllerChangeStatus: {
    dispatch: (status: boolean, tab: any) => Promise<any>;
};
declare const _default: {
    configGetSettings: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getStaticFile: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getFeatureFlag: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    checkCashbackIsActivated: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    partnerGetByDomain: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    partnerGetById: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    redirectOpenRedirect: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getConfiguration: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    getABTestSide: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    sendGA4: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    sendBigQuery: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    sendABtest: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    cashbackOfferCached: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    featureControllerChangeStatus: {
        dispatch: (status: boolean, tab: any) => Promise<any>;
    };
    featureControllerSubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    featureControllerUnsubscribe: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
    checkFeaturesInExecutionByTab: import("../../../../shared/lib/message/feature_message_dispatch").default<any>;
};
export default _default;
