#!/bin/bash
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Uključite fotoaparat. Aktivirajte kameru.\"},\"appDesc\": {\"message\": \"Uključite fotoaparat. Aktivirajte kameru.\",\"description\":\"Uključite fotoaparat. Aktivirajte kameru.\"}}" > hr/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Bật máy ảnh. Kích hoạt webcam của bạn.\"},\"appDesc\": {\"message\": \"Bật máy ảnh. Kích hoạt webcam của bạn.\",\"description\":\"Bật máy ảnh. Kích hoạt webcam của bạn.\"}}" > vi/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Fotoğraf makinesini açın. Web kameranızı etkinleştirin.\"},\"appDesc\": {\"message\": \"Fotoğraf makinesini açın. Web kameranızı etkinleştirin.\",\"description\":\"Fotoğraf makinesini açın. Web kameranızı etkinleştirin.\"}}" > tr/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Slå på kameran. Aktivera din webbkamera.\"},\"appDesc\": {\"message\": \"Slå på kameran. Aktivera din webbkamera.\",\"description\":\"Slå på kameran. Aktivera din webbkamera.\"}}" > sv/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Turn on the camera. Activate your webcam.\"},\"appDesc\": {\"message\": \"Turn on the camera. Activate your webcam.\",\"description\":\"Turn on the camera. Activate your webcam.\"}}" > en/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Turn on the camera. Activate your webcam.\"},\"appDesc\": {\"message\": \"Turn on the camera. Activate your webcam.\",\"description\":\"Turn on the camera. Activate your webcam.\"}}" > en_GB/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Turn on the camera. Activate your webcam.\"},\"appDesc\": {\"message\": \"Turn on the camera. Activate your webcam.\",\"description\":\"Turn on the camera. Activate your webcam.\"}}" > en_US/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Allumez l'appareil photo. Activez votre webcam.\"},\"appDesc\": {\"message\": \"Allumez l'appareil photo. Activez votre webcam.\",\"description\":\"Allumez l'appareil photo. Activez votre webcam.\"}}" > fr/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Hidupkan kamera. Mengaktifkan webcam anda.\"},\"appDesc\": {\"message\": \"Hidupkan kamera. Mengaktifkan webcam anda.\",\"description\":\"Hidupkan kamera. Mengaktifkan webcam anda.\"}}" > ms/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Ligue a câmera. Ative sua webcam.\"},\"appDesc\": {\"message\": \"Ligue a câmera. Ative sua webcam.\",\"description\":\"Ligue a câmera. Ative sua webcam.\"}}" > pt_BR/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Ligue a câmera. Ative sua webcam.\"},\"appDesc\": {\"message\": \"Ligue a câmera. Ative sua webcam.\",\"description\":\"Ligue a câmera. Ative sua webcam.\"}}" > pt_PT/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Porniți camera. Activați webcam-ul.\"},\"appDesc\": {\"message\": \"Porniți camera. Activați webcam-ul.\",\"description\":\"Porniți camera. Activați webcam-ul.\"}}" > ro/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Włącz aparat. Włącz kamerę internetową.\"},\"appDesc\": {\"message\": \"Włącz aparat. Włącz kamerę internetową.\",\"description\":\"Włącz aparat. Włącz kamerę internetową.\"}}" > pl/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"I-on ang camera. Buhayin ang iyong webcam.\"},\"appDesc\": {\"message\": \"I-on ang camera. Buhayin ang iyong webcam.\",\"description\":\"I-on ang camera. Buhayin ang iyong webcam.\"}}" > fil/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Encienda la cámara. Activar tu webcam.\"},\"appDesc\": {\"message\": \"Encienda la cámara. Activar tu webcam.\",\"description\":\"Encienda la cámara. Activar tu webcam.\"}}" > es/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Encienda la cámara. Activar tu webcam.\"},\"appDesc\": {\"message\": \"Encienda la cámara. Activar tu webcam.\",\"description\":\"Encienda la cámara. Activar tu webcam.\"}}" > es_419/messages.json
echo "{\"appName\": {\"message\": \"Càmera web\",\"description\": \"Enceneu la càmera. Activar la teva webcam.\"},\"appDesc\": {\"message\": \"Enceneu la càmera. Activar la teva webcam.\",\"description\":\"Enceneu la càmera. Activar la teva webcam.\"}}" > ca/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Tænd kameraet. Aktiver din webcam.\"},\"appDesc\": {\"message\": \"Tænd kameraet. Aktiver din webcam.\",\"description\":\"Tænd kameraet. Aktiver din webcam.\"}}" > da/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Slå på kameraet. Aktiver webkameraet ditt.\"},\"appDesc\": {\"message\": \"Slå på kameraet. Aktiver webkameraet ditt.\",\"description\":\"Slå på kameraet. Aktiver webkameraet ditt.\"}}" > no/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Hidupkan kamera. Aktifkan webcam Anda.\"},\"appDesc\": {\"message\": \"Hidupkan kamera. Aktifkan webcam Anda.\",\"description\":\"Hidupkan kamera. Aktifkan webcam Anda.\"}}" > id/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Ieslēdziet kameru. Aktivizējiet savu webcam.\"},\"appDesc\": {\"message\": \"Ieslēdziet kameru. Aktivizējiet savu webcam.\",\"description\":\"Ieslēdziet kameru. Aktivizējiet savu webcam.\"}}" > lv/messages.json
echo "{\"appName\": {\"message\": \"Spletna kamera\",\"description\": \"Vklopite fotoaparat. Aktivirajte svojo spletno kamero.\"},\"appDesc\": {\"message\": \"Vklopite fotoaparat. Aktivirajte svojo spletno kamero.\",\"description\":\"Vklopite fotoaparat. Aktivirajte svojo spletno kamero.\"}}" > sl/messages.json
echo "{\"appName\": {\"message\": \"Webkamera\",\"description\": \"Zapnite fotoaparát. Aktivujte si kameru.\"},\"appDesc\": {\"message\": \"Zapnite fotoaparát. Aktivujte si kameru.\",\"description\":\"Zapnite fotoaparát. Aktivujte si kameru.\"}}" > sk/messages.json
echo "{\"appName\": {\"message\": \"Webkamera\",\"description\": \"Zapněte fotoaparát. Aktivujte si kameru.\"},\"appDesc\": {\"message\": \"Zapněte fotoaparát. Aktivujte si kameru.\",\"description\":\"Zapněte fotoaparát. Aktivujte si kameru.\"}}" > cs/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Schalten Sie die Kamera ein. Aktivieren Sie Ihre Webcam.\"},\"appDesc\": {\"message\": \"Schalten Sie die Kamera ein. Aktivieren Sie Ihre Webcam.\",\"description\":\"Schalten Sie die Kamera ein. Aktivieren Sie Ihre Webcam.\"}}" > de/messages.json
echo "{\"appName\": {\"message\": \"Veebikaamera\",\"description\": \"Lülitage kaamera sisse. Aktiveeri oma veebikaamera.\"},\"appDesc\": {\"message\": \"Lülitage kaamera sisse. Aktiveeri oma veebikaamera.\",\"description\":\"Lülitage kaamera sisse. Aktiveeri oma veebikaamera.\"}}" > et/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Kytke kameraan. Aktivoi webcam.\"},\"appDesc\": {\"message\": \"Kytke kameraan. Aktivoi webcam.\",\"description\":\"Kytke kameraan. Aktivoi webcam.\"}}" > fi/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Kurejea kwenye kamera. Kuamsha webcam yako.\"},\"appDesc\": {\"message\": \"Kurejea kwenye kamera. Kuamsha webcam yako.\",\"description\":\"Kurejea kwenye kamera. Kuamsha webcam yako.\"}}" > sw/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Accendere la fotocamera. Attiva la tua webcam.\"},\"appDesc\": {\"message\": \"Accendere la fotocamera. Attiva la tua webcam.\",\"description\":\"Accendere la fotocamera. Attiva la tua webcam.\"}}" > it/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Zet de camera aan. Activeer uw webcam.\"},\"appDesc\": {\"message\": \"Zet de camera aan. Activeer uw webcam.\",\"description\":\"Zet de camera aan. Activeer uw webcam.\"}}" > nl/messages.json
echo "{\"appName\": {\"message\": \"Kamera\",\"description\": \"Įjunkite fotoaparatą. Aktyvuokite savo kamera.\"},\"appDesc\": {\"message\": \"Įjunkite fotoaparatą. Aktyvuokite savo kamera.\",\"description\":\"Įjunkite fotoaparatą. Aktyvuokite savo kamera.\"}}" > lt/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Kapcsolja be a fényképezőgépet. Aktiválja a webkamerát.\"},\"appDesc\": {\"message\": \"Kapcsolja be a fényképezőgépet. Aktiválja a webkamerát.\",\"description\":\"Kapcsolja be a fényképezőgépet. Aktiválja a webkamerát.\"}}" > hu/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Ενεργοποιήστε τη φωτογραφική μηχανή. Ενεργοποίηση της κάμερας σας.\"},\"appDesc\": {\"message\": \"Ενεργοποιήστε τη φωτογραφική μηχανή. Ενεργοποίηση της κάμερας σας.\",\"description\":\"Ενεργοποιήστε τη φωτογραφική μηχανή. Ενεργοποίηση της κάμερας σας.\"}}" > el/messages.json
echo "{\"appName\": {\"message\": \"Вебцам\",\"description\": \"Укључите камеру. Активирајте веб камеру.\"},\"appDesc\": {\"message\": \"Укључите камеру. Активирајте веб камеру.\",\"description\":\"Укључите камеру. Активирајте веб камеру.\"}}" > sr/messages.json
echo "{\"appName\": {\"message\": \"Веб-камера\",\"description\": \"Увімкніть камеру. Активуйте веб-камери.\"},\"appDesc\": {\"message\": \"Увімкніть камеру. Активуйте веб-камери.\",\"description\":\"Увімкніть камеру. Активуйте веб-камери.\"}}" > uk/messages.json
echo "{\"appName\": {\"message\": \"Webcam\",\"description\": \"Включете камерата. Активирайте вашата уеб камера.\"},\"appDesc\": {\"message\": \"Включете камерата. Активирайте вашата уеб камера.\",\"description\":\"Включете камерата. Активирайте вашата уеб камера.\"}}" > bg/messages.json
echo "{\"appName\": {\"message\": \"Веб-камера\",\"description\": \"Включите камеру. Активируйте веб-камеры.\"},\"appDesc\": {\"message\": \"Включите камеру. Активируйте веб-камеры.\",\"description\":\"Включите камеру. Активируйте веб-камеры.\"}}" > ru/messages.json
echo "{\"appName\": {\"message\": \"מצלמת אינטרנט\",\"description\": \"הפעל את המצלמה. הפעל את מצלמת אינטרנט.\"},\"appDesc\": {\"message\": \"הפעל את המצלמה. הפעל את מצלמת אינטרנט.\",\"description\":\"הפעל את המצלמה. הפעל את מצלמת אינטרנט.\"}}" > he/messages.json
echo "{\"appName\": {\"message\": \"وب کم\",\"description\": \"دوربین را روشن کنید. وب کم خود را فعال کنید.\"},\"appDesc\": {\"message\": \"دوربین را روشن کنید. وب کم خود را فعال کنید.\",\"description\":\"دوربین را روشن کنید. وب کم خود را فعال کنید.\"}}" > fa/messages.json
echo "{\"appName\": {\"message\": \"كاميرا ويب\",\"description\": \"تشغيل الكاميرا. تنشيط كاميرا ويب الخاص بك.\"},\"appDesc\": {\"message\": \"تشغيل الكاميرا. تنشيط كاميرا ويب الخاص بك.\",\"description\":\"تشغيل الكاميرا. تنشيط كاميرا ويب الخاص بك.\"}}" > ar/messages.json
echo "{\"appName\": {\"message\": \"वेब कैमरा\",\"description\": \"कैमरा चालू करें. अपने वेबकैम को सक्रिय करें.\"},\"appDesc\": {\"message\": \"कैमरा चालू करें. अपने वेबकैम को सक्रिय करें.\",\"description\":\"कैमरा चालू करें. अपने वेबकैम को सक्रिय करें.\"}}" > hi/messages.json
echo "{\"appName\": {\"message\": \"เว็บแคม\",\"description\": \"เปิดสวิตช์กล้อง เปิดใช้งานเว็บแคมของคุณ\"},\"appDesc\": {\"message\": \"เปิดสวิตช์กล้อง เปิดใช้งานเว็บแคมของคุณ\",\"description\":\"เปิดสวิตช์กล้อง เปิดใช้งานเว็บแคมของคุณ\"}}" > th/messages.json
echo "{\"appName\": {\"message\": \"웹캠\",\"description\": \"카메라를 켭니다. 웹캠을 활성화합니다.\"},\"appDesc\": {\"message\": \"카메라를 켭니다. 웹캠을 활성화합니다.\",\"description\":\"카메라를 켭니다. 웹캠을 활성화합니다.\"}}" > ko/messages.json
echo "{\"appName\": {\"message\": \"ウェブカメラ\",\"description\": \"カメラの電源を入れます。あなたのウェブカメラをアクティブにします。\"},\"appDesc\": {\"message\": \"カメラの電源を入れます。あなたのウェブカメラをアクティブにします。\",\"description\":\"カメラの電源を入れます。あなたのウェブカメラをアクティブにします。\"}}" > ja/messages.json
echo "{\"appName\": {\"message\": \"摄像头\",\"description\": \"打开相机上。激活你的摄像头。\"},\"appDesc\": {\"message\": \"打开相机上。激活你的摄像头。\",\"description\":\"打开相机上。激活你的摄像头。\"}}" > zh_CN/messages.json
echo "{\"appName\": {\"message\": \"攝像頭\",\"description\": \"打開相機上。激活你的攝像頭。\"},\"appDesc\": {\"message\": \"打開相機上。激活你的攝像頭。\",\"description\":\"打開相機上。激活你的攝像頭。\"}}" > zh_TW/messages.json
