remote_id = '1700358878'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-left = '0.0'
remote-menubar-drag-right = '1.0'

[ui_flutter]
peer-sorting = 'Remote ID'
wm_RemoteDesktop = '{"width":1300.0,"height":740.0,"offsetWidth":30.0,"offsetHeight":122.0,"isMaximized":true}'
