export function addInfo(browser: any, version: any): void;
export function getSiteRoot(): string;
export function matchMeliuzUrl(url: any): any;
export function matchMeliuzRedirect(url: any): false | "offer";
export function urlIsValid(url: any): any;
export function domainName(url: any): {
    domain: string;
    path: string[];
};
export function checkForBlacklist(rawUrl: any): string | false;
export function getPartnerUrl(partner: any): string;
export function getCategoryUrl(partner: any): string;
export function getOfferUrl(mainOfferId: any): string;
export function getDetailsUrl(partnerDetailsUrl: any): any;
export function browserFormat(broserName: any): any;
export function formatUrl(url: any, campaign: any): any;
export function getQueryParameters(campaign: any): string;
export function convertToSlug(stringInput: any): any;
export function formatDomain(domain: any): string | false;
export function getUtmCampaign(partner: any, type: any): string;
export function getWithdrawalUrl(): string;
export function getStatementUrl(): string;
export function getEditUrl(): string;
export function getRateUrl(): string;
export function getRateUrlFirefox(): string;
export function getRateUrlSafari(): string;
export function getAllHelpingTopicsUrl(): string;
export function getFullUrlOffer(id: any): any;
export function extractDomain(url: any): any;
export function getDomainWithoutSubdomain(url: any): string;
