import { Palette } from 'styled-components';
declare const palette: Palette;
export declare const colors: {
    'primary-01': string;
    'primary-02': string;
    'primary-03': string;
    'primary-04': string;
    'primary-05': string;
    'primary-06': string;
    'grayScale-01': string;
    'grayScale-02': string;
    'grayScale-03': string;
    'grayScale-04': string;
    'grayScale-05': string;
    'grayScale-06': string;
    'grayScale-07': string;
    'success-01': string;
    'success-02': string;
    'success-03': string;
    'warning-01': string;
    'warning-02': string;
    'warning-03': string;
    'error-01': string;
    'error-02': string;
    'error-03': string;
    'info-01': string;
    'info-02': string;
    'info-03': string;
    'support-01': string;
};
export default palette;
