export declare const fontSizes: {
    'display-01': string;
    'display-02': string;
    'display-03': string;
    'title-01': string;
    'title-02': string;
    'title-03': string;
    'title-04': string;
    'title-05': string;
    'title-06': string;
    'title-07': string;
    'body-01': string;
    'body-02': string;
    'caption-01': string;
    'caption-02': string;
    'caption-03': string;
    'captionLink-01': string;
    'captionLink-02': string;
    'iconDisplay-01': string;
    'iconDisplay-02': string;
    'iconTitle-01': string;
    'iconTitle-02': string;
    'iconBody-01': string;
    'iconBody-02': string;
    'iconCaption-01': string;
    'iconCaption-02': string;
    'iconCaption-03': string;
};
export declare const fonts: {
    heroNew: string;
};
export declare const fontWeights: {
    regular: number;
    bold: number;
};
export declare const lineHeights: {
    'display-01': string;
    'display-02': string;
    'display-03': string;
    'title-01': string;
    'title-02': string;
    'title-03': string;
    'title-04': string;
    'title-05': string;
    'title-06': string;
    'title-07': string;
    'body-01': string;
    'body-02': string;
    'caption-01': string;
    'caption-02': string;
    'caption-03': string;
    'captionLink-01': string;
    'captionLink-02': string;
    'iconDisplay-01': string;
    'iconDisplay-02': string;
    'iconTitle-01': string;
    'iconTitle-02': string;
    'iconBody-01': string;
    'iconBody-02': string;
    'iconCaption-01': string;
    'iconCaption-02': string;
    'iconCaption-03': string;
};
export declare const iconSizes: {
    'iconDisplay-01': string;
    'iconDisplay-02': string;
    'iconTitle-01': string;
    'iconTitle-02': string;
    'iconBody-01': string;
    'iconBody-02': string;
    'iconCaption-01': string;
    'iconCaption-02': string;
    'iconCaption-03': string;
};
